### ISSUE TITLE
Can't make

### ISSUE THREAD

**Issue by AcarBurak** [jonaski/strawberry#1]
(In my Arch/Fluxbox/Qt5.10 system)

Before `make`, `cmake .. /strawberry` doesn't work as there's no `…/strawberry/strawberry` directory. `cmake ..` works, but only after installing `boost` so it would be convenivent to list `boost` dependencies in  the README.

And `make` fails with:

> [ 44%] Generating ui_transcoderoptionswma.h
> Scanning dependencies of target strawberry_lib
> [ 44%] Building CXX object src/CMakeFiles/strawberry_lib.dir/core/mainwindow.cpp.o
> In file included from /home/burak/Downloads/strawberry/src/core/mainwindow.cpp:111:0:
> /home/burak/Downloads/strawberry/src/widgets/stylehelper.h:34:10: fatal error: QtGui/QStyle: No such file or directory
>  #include <QtGui/QStyle>
>           ^~~~~~~~~~~~~~
> compilation terminated.
> make[2]: *** [src/CMakeFiles/strawberry_lib.dir/build.make:1662: src/CMakeFiles/strawberry_lib.dir/core/mainwindow.cpp.o] Error 1
> make[1]: *** [CMakeFiles/Makefile2:478: src/CMakeFiles/strawberry_lib.dir/all] Error 2
> make: *** [Makefile:130: all] Error 2

By the way, my favourite is Autumn, though Dave Cousins could probably make rather mediocre songs sound beautiful as well!

**Comment by jonaski** [comment]
It's trying to include some headers that are not available in Qt5, I've fixed it now.
Update your source with git pull and try to build again.
