### ISSUE TITLE
grouping shows several folders for one same album with different release year per track

### ISSUE THREAD

**Issue by sylvainsab** [jonaski/strawberry#100]
I enjoyed tagging my music files with quite specific genres, so I use a "Genre/Year - Album" grouping.
Unfortunately this results in several sub-sections for a single album when tracks do not feature the same release date (see attached picture for instance).

Could this be fixed perhaps by removing the year display when an album features this ?
Or maybe there is a tag identifier like "album_year" or something that I'm unaware of ?

![Screenshot_20190403_024114](https://user-images.githubusercontent.com/34339895/55445109-f3da6e00-55b9-11e9-9b0a-15898638694f.png)

**Comment by jonaski** [comment]
There is only 2 tags "original year" and "year". I was not aware that some albums were released with different songs with different years, whats the point of the album title then?
Anyway I think the correct behavior is the way it is now where they would be listed like this.

**Comment by sylvainsab** [comment]
Indeed this is quite odd, but it happens in some peculiar albums such as compilations, "bests of", etcætera.
