### ISSUE TITLE
snap desktop issues on Ubuntu 18.04

### ISSUE THREAD

**Issue by mattiaswerner** [jonaski/strawberry#102]
Launching the app via desktop search starts the systray icon, but doesn't put a launcher in the Dock.

In order to get it to launch the main window I have to put it in the dock manually and click on it again.

The launcher icon is also missing.

**Comment by derEremit** [comment]
Another edge case maybe.
Snap can't access my network-mounted directory.
deb package with same mount setup can

**Comment by mattiaswerner** [comment]
> Another edge case maybe.
> Snap can't access my network-mounted directory.
> deb package with same mount setup can

That I believe you can solve by "snap connect plug:removable-media strawberry

**Comment by jonaski** [comment]
Can you try the latest revision now (495) and see if it solves it.
You should also as a minimum connect these 3 plugs like this:
```
sudo snap connect strawberry:alsa
sudo snap connect strawberry:udisks2
sudo snap connect strawberry:network-manager

```

**Comment by mattiaswerner** [comment]
Launcher icon issue fixed.

Previously described behaviour unchanged.

**Comment by jonaski** [comment]
It works here, but it's very slow to start when starting as a snap.

**Comment by salmmm22** [comment]
I just installed it in Snap on my Ubuntu 18.04 LTS and it does not launch. I included the 3 commands but it still does not open OR appear in system tray.

**Comment by jonaski** [comment]
I tested on Ubuntu 18.04 in a VirtualBox and it works here.
I opened a topic on the snap forum to see if anyone there can look at it:
https://forum.snapcraft.io/t/snap-of-strawberry-music-player/11255

**Comment by salmmm22** [comment]
I just installed the deb and it worked so something is missing that is required. However, some users may already have those files and that could be why it works for them and for you on 18.04 virtual box.

**Comment by jonaski** [comment]
You are probably right.

**Comment by jonaski** [comment]
Just did a clean install of Ubuntu 18.04 in virtualbox, first thing I did was to go to the software centre and install strawberry, then pressed launch, started right up. Closed it and started it normally from the start menu, works too.
