### ISSUE TITLE
Moodbar integration?

### ISSUE THREAD

**Issue by desputinski** [jonaski/strawberry#103]
Hi, is this a clementine fork?
Does Strawberry include moodbars?
best regards
desputin

**Comment by jonaski** [comment]
No. The same question was asked a month ago.

**Comment by desputinski** [comment]
Is it planned for the future or can I place a feature request for that?

**Comment by jonaski** [comment]
If more contributors join this project it might get added.

**Comment by ccoenen** [comment]
duplicate of #87

**Comment by jonaski** [comment]
I've added the moodbar now.
https://github.com/jonaski/strawberry/commit/907d18a83a692ed95d44961f7cdce56033564564

**Comment by desputinski** [comment]
Thank you, thank you!!!!!

PS for everyone who doesn't know the project:
https://en.wikipedia.org/wiki/Moodbar
