### ISSUE TITLE
Bad background color in Context tab

### ISSUE THREAD

**Issue by JGoutin** [jonaski/strawberry#105]
The background colour of the "Context" tab is white instead of the theme colour.

Changing "Appearances" settings does not fix the issue.

Strawberry Version: 0.5.2 (From package manager)
System info: Fedora 29 x86_64,  KDE Plasma 5.14.5

![Screenshot_20190406_131218](https://user-images.githubusercontent.com/13535894/55668710-f6a8bd80-585c-11e9-8a06-1715c5cf3cc1.png)

**Comment by jonaski** [comment]
Fixed https://github.com/jonaski/strawberry/commit/d2ef0a996fda75c3dea2e3d61da3f6f1bba569fa
Sorry this took so long, I had forced white background in css file and forgot about it.
