### ISSUE TITLE
Playback sometime block at song end instead of switching to next song

### ISSUE THREAD

**Issue by JGoutin** [jonaski/strawberry#106]
Sometime, when the song end occur the playback is blocking instead of switching to next song (Icon still show it is playing, not stopped or paused). If I manually click on the next track button, the playback continue as normal.

Strawberry Version: 0.5.2 (From package manager)
System info: Fedora 29 x86_64, KDE Plasma 5.14.5

**Comment by jonaski** [comment]
What file format?

**Comment by JGoutin** [comment]
Flac format.

**Comment by jonaski** [comment]
I'm playing 99% flac and have never seen this issue. But I use a specific customized setup with a custom low-latency kernel and without pulseaudio. But no-one else has reported this. So I think it may be related to something specific with your files or your system.
Do you use pulseaudio? Does is occur with random flac files, or the same ones?

**Comment by JGoutin** [comment]
The problem occurred when playing my collection in shuffle mode.
I didn't check if the problem occur on particular files, but I'll do it next time the problem occur.

The system  is configured to use Pulseaudio (I use the basic sound Fedora configuration), but I configured Strawberry to use ALSA with a specific output.

Here is my full "backend" configuration:
![backend](https://user-images.githubusercontent.com/13535894/55754382-0c280e00-5a3c-11e9-96b6-70d5c602ee70.png)

**Comment by jonaski** [comment]
You can run strawberry --verbose on the terminal, but its a lot of output.
I think it is more likely related to the replay gain than the shuffling, but I use neither, I can try to enable both and see if I can reproduce the problem.

**Comment by JGoutin** [comment]
I tried `strawberry --verbose`, but I didn't get any output in the terminal.

**Comment by jonaski** [comment]
https://brendanwhitfield.wordpress.com/2016/06/08/enabling-qdebug-on-fedora/

**Comment by JGoutin** [comment]
That worked, thanks.
I played music with logging enabled and there is no specific output when the problem occur.

I have this error that appear on each song change:
`ERROR logging:60                       Source ID 11 was not found when attempting to remove it`
(with `11` as an increasing value each time).

I tried to change my backend configuration (Disabled replay gain and set audio output to pulseaudio) and restart strawberry: the problem still occur.

**Comment by jonaski** [comment]
The logline is normal and unrelated to this
Perhaps you could test with a builtin soundcard if you got it and see if you have the same problem.

**Comment by tholin** [comment]
Could be the same as this problem in clementine? https://github.com/clementine-player/Clementine/issues/6062

The hang can happen when switching between tracks with different sample rates. Clementine got a commit to fix the problem in https://github.com/clementine-player/Clementine/commit/2b280de663bc53b4f37dbb3f875cd630bad22c82 but that fix is also broken. See comment https://github.com/clementine-player/Clementine/issues/6062#issuecomment-406064064 for details.

**Comment by jonaski** [comment]
Yeah, it might be the same, I can try to switch to queue2

**Comment by jonaski** [comment]
@tholin I can confirm that pause gets stuck when using queue2, so we need to find another fix.

**Comment by gavinhoward** [comment]
Just switched to Strawberry myself from Clementine. I can reproduce this issue in both players with the same songs.

I will look into this starting tomorrow. (The "help wanted" tag helps.)

**Comment by jonaski** [comment]
@gavinhoward Did you figure out anything?

**Comment by gavinhoward** [comment]
Unfortunately, not. I got swamped with staying a new job and one user of a FOSS project I run demanding time and changes. It is still on my TODO list, though, along with a few other bugs that I have noticed.

**Comment by jonaski** [comment]
I tried to use queue2 for the probe queue again and I can't reproduce any problems with pause anymore.
So let's give it try. Try with this change and also test to pause for 15 minutes and unpause and verify thay pause isn't stuck.
https://github.com/jonaski/strawberry/commit/a9c162476cd4750737056585ebb1ccfd23403813

**Comment by gavinhoward** [comment]
Works for me!

**Comment by dermamred** [comment]
Maybe I miss something but there's some patch to apply othen than downloading/installing the latest buildversione available for xenial?... I'm askin 'cos I still have this issue that's a playback stopping where the next song has a different bit/samplerate.

**Comment by jonaski** [comment]
Yes, you just go to the commit link on github than add .path after the url path and you get a patch:
https://github.com/jonaski/strawberry/commit/a9c162476cd4750737056585ebb1ccfd23403813.patch

However I have to revert it because I can reproduce the problems with unpause again. But if it works for you, you can use it.
The solution is probably to use queue2 but we need to fix the unpause thing first.

**Comment by jonaski** [comment]
@gavinhoward try https://github.com/jonaski/strawberry/pull/204
It has something to do with the properties on the queue and the buffering.
Not sure if this is 100% correct though.

**Comment by jonaski** [comment]
Fixed https://github.com/jonaski/strawberry/commit/aec9df1882dab94944be86d80ddffcd1cf47bf6a
