### ISSUE TITLE
Feature : Collection viewer selection playlist

### ISSUE THREAD

**Issue by JGoutin** [jonaski/strawberry#107]
A feature that automatically provides a playlist that is a view of selected collection items (or full collection if nothing selected). [See original Foobar2000 "Library Viewer Selection Playlist" feature](http://wiki.hydrogenaud.io/index.php?title=Foobar2000:Preferences:Media_Library#Library_Viewer_Selection_Playlist).

I used this feature during years in Foobar2000, and this really improve and speed up song navigation with large collections and avoid to have to manually update one or more playlists to reflect the collection or some parts of it. This simply make the navigation more natural.

**Comment by jonaski** [comment]
I assume this is somewhat the same as in: https://github.com/jonaski/strawberry/issues/81 where you would show entire albums in the playlist view.
In any case the answer is the same for this.
