### ISSUE TITLE
Lyrics not displayed reliably

### ISSUE THREAD

**Issue by tla2k12** [jonaski/strawberry#110]
Strawberry version 0.5.3-12-g77903a5
Environment: Fedora release 29 (Twenty Nine); Linux 5.0.5-200.fc29.x86_64 #1 SMP Wed Mar 27 20:58:04 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

Lyrics are not displayed reliably in the context window. I don't know where Strawberry searches for lyrics (the configuration options Clementine had don't seem to be present in Strawberry).  I know the lyrics are present at (for example) https://lyrics.wikia.com/wiki/Kristin_Hersh:Serene

I will debug and provide info if you tell me what you need.

**Comment by jonaski** [comment]
You need to right click and select lyrics.
It uses AudD (It's written in the readme) and if there is no match for the song there is no lyrics.
It does not use the site your referer to.
AuD is the only reliable site I found that has a API. I had API Seeds too be before but it's a paid service.
You can run strawberry on the terminal to see output, there should be a line saying no match when there are no lyrics from AuD.

**Comment by jonaski** [comment]
If you find another site that provides a API I can implement it. But parsing lyrics from html is a mess.

**Comment by tla2k12** [comment]
Thanks for the reply. I hadn't looked at README.md and didn't realise getting lyrics via HTML was difficult.

Oddly, running strawberry from the terminal produced no output with: no options, --quiet, --log-levels *:2 or --verbose

**Comment by jonaski** [comment]
Your right there is no output on no match, I removed it, forgot about it.
You can test it here:
https://api.audd.io/findLyrics/?q=Kristin%20Hersh%20Serene

I'd rather wait for additional lyrics API's to arrive, than parse by html. But the support for multiple lyrics providers is there, so it will be improved in time.

**Comment by tla2k12** [comment]
I tried the test and it returned someone completely different (rather than Not Found or whatever). I appreciate this is nothing to do with Strawberry!

{"status":"success","result":[{"song_id":"3680685","artist_id":"390344","title":"I Rise","title_with_featured":"I Rise (Ft. Angela  Brown)","full_title":"I Rise by Angela  Brown (Ft. Angela  Brown)","artist":"Angela  Brown","lyrics":"","media":"[]"}]}
