### ISSUE TITLE
tracks playcount doesn't get updated

### ISSUE THREAD

**Issue by sylvainsab** [jonaski/strawberry#111]
As it says in the title : I would play some file for the library, and have the #Playcount columns at the end of the main playlist, supposed to show how many times I've played the track.
The number is not always blank or zero as it seems that Clementine, which I used prior to Strawberry, has stored the playcount in the files, but Strawberry does not update it.

**Comment by jonaski** [comment]
Fixed https://github.com/jonaski/strawberry/commit/40db9f702037b7c824da584c7e67780e4f2eb434
