### ISSUE TITLE
Can't add secondary drive folder to collection (Ubuntu 18.04)

### ISSUE THREAD

**Issue by educhastenier** [jonaski/strawberry#112]
All my collection is stored on a secondary drive.
The "Add folder..." file browser filters out secondary drives and symbolic links pointing to them, leading to impossibility to add my music to the collection.
I see no workaround, so my collection remains empty :disappointed: 
I remain available to any additional information that you may need to investigate the issue.

**Comment by jonaski** [comment]
Are you using the snap (through software centre in ubuntu) or normal .deb installation?
If it's the snap, I suggest you try one of the deb packages from: https://builds.strawbs.net/
They don't have the same limitations as when running as a snap.
What filesystem?
Does it output any errors if you run it in a terminal?

**Comment by jonaski** [comment]
Haven't heard anything back from you, so closing this.

**Comment by educhastenier** [comment]
Indeed, it does work using https://builds.strawbs.net/ instead of Ubuntu software center). :grinning: 
Thanks for you help.
