### ISSUE TITLE
New Themes 

### ISSUE THREAD

**Issue by Ashutosh-Kukreti** [jonaski/strawberry#113]
Hi,
Is it possible to have a dark Spotify theme for strawberry?It will be very cool

If you wan some theme ideas you can look at https://getmusicbee.com/addons/s/?type=1

**Comment by jonaski** [comment]
Strawberry is Qt based so it should follow the themes on the system, It works KDE, not very well on some other desktops perhaps though. I'm not sure about Windows.
There is an Appearance setting where you can change colors, but it does not work very well in my opinion, and I actually considered removing it, but I've kept it.
I don't plan to extend it, or have the time for it, but if someone contribute improvements it's welcomed.
