### ISSUE TITLE
Possible regression in audio player shortcuts, 0.52=>0.53

### ISSUE THREAD

**Issue by NucleaPeon** [jonaski/strawberry#116]
Strawberry version 0.52 fixed all my shortcut issues. After upgrading to 0.53, shortcuts still work with one exception:

Pressing the start/pause key will pause a playing song, but pressing it again no longer starts the song up again. It will blink, letting me know that the keypress was detected, but doesn't do anything. Maybe it's an issue with strawberry not understanding the state of playback, where once a song is paused, it keeps pausing when the button is pressed instead of playing.

This is detected even in most recent git master version: `Version 0.5.3-47-gd2fc5a6`

Gentoo+KDE5 18.12.3+Plasma 5.14.5+QT5 5.11.3
Both with X11 shortcut option enabled and disabled this occurs.

![Screenshot_20190418_154325](https://user-images.githubusercontent.com/1475151/56395758-c2d07f00-61f0-11e9-86fc-e13d9ce4d63c.png)

**Comment by jonaski** [comment]
I can confirm this an the arch linux / KDE machine I just set up. But it works with the same keyboard on my opensuse/XFCE  desktop.
MPRIS seem to play / pause each time also: qdbus org.mpris.MediaPlayer2.strawberry /org/mpris/MediaPlayer2 PlayPause

**Comment by jonaski** [comment]
Fixed https://github.com/jonaski/strawberry/commit/dffc46551e85e0ebdb039522729d6675baaf82c7

**Comment by NucleaPeon** [comment]
Many thanks! :)
