### ISSUE TITLE
"Apply" button of settings window has no effect

### ISSUE THREAD

**Issue by glaubersm** [jonaski/strawberry#117]
Hi

I use strawberry-full-git on Arch Linux running KDE Plasma 5.15.4, installed from AUR.
We can see the problem described in the title changing "Background image" settings
in "Appearance" tab. Select any radio button and click "Apply" button: the selected option was not applied. Now click "Ok" button: the selected setting was applied.

**Comment by jonaski** [comment]
I know about this. Some settings do not work with apply. I will check if it's possible to make it apply.

**Comment by jonaski** [comment]
Fixed https://github.com/jonaski/strawberry/commit/2d3509ae56a09960c51bb98535951d00b9f2b8df
