### ISSUE TITLE
"Include album art in the notification" does not work if selected "Notitication type" is "Show a popup from a system tray"

### ISSUE THREAD

**Issue by glaubersm** [jonaski/strawberry#118]
Hi

I use strawberry-full-git on Arch Linux running KDE Plasma 5.15.4, installed from AUR.

Open strawberry settings, click "Notifications" section in the left side.
Set "Show a popup from a system tray" as "Notitication type", make sure that
"Include album art in the notification" option is checked, click "Ok" button.
Notice that when a notification appears, album art is missing.

**Comment by jonaski** [comment]
There isn't album art for the popup setting, I will make the option disabled when it's selected.

**Comment by jonaski** [comment]
Fixed https://github.com/jonaski/strawberry/commit/4cc926a627cffc4dc1e89efc38c4a47de5943ed6
