### ISSUE TITLE
Immediately crashes if "Complete Tags Automatically" is chosen

### ISSUE THREAD

**Issue by alongdecline** [jonaski/strawberry#120]
I just upgraded to the newest Pop!_OS (19.04) and encountered this problem with both Strawberry as well as Clementine. It happens as soon as the window for automatic tags opens up - the whole program crashes and shuts down. I can open it again as if nothing happened, but it doesn't seem to matter whether I choose the "complete tags automatically" as a right click on a track or within the edit tracks window.

**Comment by jonaski** [comment]
How did you install strawberry? Do Pop!_OS include strawberry in their repository? Or do you use it from the software centre as a snap?

**Comment by alongdecline** [comment]
Pop!_OS is built from Ubuntu repositories - so it has all the same stuff, I was able to tackle installation via terminal thanks to your easy instructions (and a bit of searching). Clementine (which has the same issue) is available in their software centre, so installing that was zero work - just a click. 

(I'm relatively new to linux, so apologies if some of the terminology I use is confusing or incorrect!)

**Comment by jonaski** [comment]
OK. I see. I've tested on Ubuntu in a VirtualBox, but it does not crash here.
You can try the following to get some more debug data:
Install gdb
From the terminal run the following in the build directory:
```
gdb ./strawberry
run
```
Do what you do to make it crash.
When it crashes, type bt and enter on the gdb terminal window

**Comment by jonaski** [comment]
I installed Pop Os in a virtualbox and I got the crash. They are using gstreamer 1.15.90. It might be related to that version.

```

05:02:10.212 WARN  logging:61                       free_priv_data: object finalizing but still has parent (object:0x7f85b400e360, parent:0x7f85b8227360)
05:02:10.212 WARN  logging:61                       free_priv_data: object finalizing but still has 1 parents (object:0x7f85b400e360)

(strawberry:2065): GStreamer-CRITICAL **: 05:02:10.212: gst_mini_object_unlock: assertion 'GST_MINI_OBJECT_IS_LOCKABLE (object)' failed

(strawberry:2065): GStreamer-CRITICAL **: 05:02:10.212: gst_mini_object_unref: assertion 'GST_MINI_OBJECT_REFCOUNT_VALUE (mini_object) > 0' failed

```

**Comment by jonaski** [comment]
It crashes here:
https://github.com/jonaski/strawberry/blob/master/src/musicbrainz/chromaprinter.cpp#L135
Unsure whether this is gtsreamer bug or not, will try gstreamer 1.16 and see if the issue is still there.

**Comment by jonaski** [comment]
Issue still there with gstreamer 1.16.

**Comment by jonaski** [comment]
Fixed https://github.com/jonaski/strawberry/commit/984abc89a82e19fb5f22eebd0196bae57df4f7ca
