### ISSUE TITLE
Seeking with mouse wheel is not working

### ISSUE THREAD

**Issue by glaubersm** [jonaski/strawberry#122]
Hi

I use strawberry-full-git on Arch Linux running KDE Plasma 5.15.4, installed from AUR.

Nothing happens when I hover over the seek bar and scroll up/down.
Seeking with the keyboard arrows works as expected.

**Comment by jonaski** [comment]
It isn't supposed to either, but I can add it.

**Comment by glaubersm** [comment]
Humm...
In strawberry settings we can read
"Seeking using a kayboard shortcut or mouse wheel"
in "Behavior" section.

**Comment by jonaski** [comment]
Fixed https://github.com/jonaski/strawberry/commit/7bcd5ba14ce7fe1f7625a24b5e09e2f4149e09dc
