### ISSUE TITLE
Equalizer feature is not working

### ISSUE THREAD

**Issue by glaubersm** [jonaski/strawberry#126]
Hi

I'm using strawberry_0.5.3-55-g7a0f668_amd64 on Neon dev unstable distribution
and strawberry-full-git on Arch Linux.
Tested both Gstreamer and VLC backends.
No change is noticeable when I enable Equalizer and select a preset.
Balance slider also has no effect.

**Comment by jonaski** [comment]
You are right, it's broken, it was working at some point, but looks like I broke it with a change I did a while back.

**Comment by jonaski** [comment]
It's fixed now, it should work with gstreamer and xine, its not implemented with VLC.
The option is now greyed out unless gstreamer or xine is selected.
I'll reopen my original issue: https://github.com/jonaski/strawberry/issues/4
