### ISSUE TITLE
Analyzer above the seek bar does work with VLC backend

### ISSUE THREAD

**Issue by glaubersm** [jonaski/strawberry#127]
Hi

I'm using strawberry_0.5.3-55-g7a0f668_amd64 on Neon dev unstable distribution
and strawberry-full-git on Arch Linux.
The analyzer above the seek bar does work with VLC backend,
it works as expected with Gstreamer backend.

**Comment by jonaski** [comment]
It only works with gstreamer and xine. Unfortunately it's not possible with VLC. I looked into it a few years back. I've disabled the right click options when VLC is selected.
