### ISSUE TITLE
Gstreamer installation is missing a plug-in

### ISSUE THREAD

**Issue by dandydon414** [jonaski/strawberry#129]
trying this again. running the latest appimage in antergos and I get this error.
I've installed every gstreamer plugin I could find, bad, good, ugly, fugly....etc....
clementine qt5 version works fine.  thanks for you hard work and help.

![image](https://user-images.githubusercontent.com/48139014/56462175-57b7b180-6384-11e9-895e-cbe2a4834b71.png)

**Comment by jonaski** [comment]
gstreamer plugins are bundled inside the AppImage, so installing plugins on your system has no affect.
What version do you use of the appimage, and what file format do you try to play?

**Comment by dandydon414** [comment]
Strawberry-0.5.3-58-ga499a70.AppImage. file type is mp3. flac files play fine

**Comment by dandydon414** [comment]
when I install from the package manager mp3 plays fine

**Comment by jonaski** [comment]
Works here.
Can you try to run it on the terminal and see what output you get?

**Comment by dandydon414** [comment]
(gst-plugin-scanner:2432): GStreamer-WARNING **: 16:28:36.302: Failed to load plugin '/tmp/.mount_StrawbE1WxSL/usr/lib/gstreamer-1.0/libgstcdio.so': libcdio.so.15: cannot open shared object file: No such file or directory

(gst-plugin-scanner:2432): GStreamer-WARNING **: 16:28:36.332: Failed to load plugin '/tmp/.mount_StrawbE1WxSL/usr/lib/gstreamer-1.0/libgstlibav.so': libavfilter.so.6: cannot open shared object file: No such file or directory

(gst-plugin-scanner:2432): GStreamer-WARNING **: 16:28:36.332: Failed to load plugin '/tmp/.mount_StrawbE1WxSL/usr/lib/gstreamer-1.0/libgstmusepack.so': libmpcdec.so.5: cannot open shared object file: No such file or directory

**Comment by jonaski** [comment]
I installed Pop Os in a virtualbox and I got the crash. They are using gstreamer 1.15.90. It might be related to that version.
```

05:02:10.212 WARN  logging:61                       free_priv_data: object finalizing but still has parent (object:0x7f85b400e360, parent:0x7f85b8227360)
05:02:10.212 WARN  logging:61                       free_priv_data: object finalizing but still has 1 parents (object:0x7f85b400e360)

(strawberry:2065): GStreamer-CRITICAL **: 05:02:10.212: gst_mini_object_unlock: assertion 'GST_MINI_OBJECT_IS_LOCKABLE (object)' failed

(strawberry:2065): GStreamer-CRITICAL **: 05:02:10.212: gst_mini_object_unref: assertion 'GST_MINI_OBJECT_REFCOUNT_VALUE (mini_object) > 0' failed

```

**Comment by dandydon414** [comment]
looks like I have 1.14.4
![image](https://user-images.githubusercontent.com/48139014/56464915-34f3c000-63b9-11e9-813d-1ce56e631709.png)

**Comment by jonaski** [comment]
Sorry, my comment wasn't meant for this issue. I think I should go to bed :)

**Comment by jonaski** [comment]
I tested it on both arch and ubuntu and confirmed the issue. The linked libraries are bundled but in the parent directory /usr/lib, but inside the appimage it doesn't find them.
Moved the gstreamer plugins directly into /usr/lib and that worked.
Fixed https://github.com/jonaski/strawberry-buildbot/commit/a3af66ff4ba1b60b09d946474e70b86c5c2ddfb3
Use the latest (Strawberry-0.5.3-61-g560000f.AppImage) and it should work.

**Comment by rmpbklyn** [comment]
**Describe the bug**
error box
'your gstreamer installation is missing a plug-in'

**To Reproduce**
double click on song to play

**Expected behavior**
song to play

**Screenshots:**
If applicable, add screenshots to help explain your problem.

**System Information:**
 - Operating system: mac high sierra
 - Strawberry Version: 0.5.5

**Additional context**
Add any other context about the problem here.

**Comment by jonaski** [comment]
@rmpbklyn AppImages won't work on macOS.
Use the latest dmg file from here: https://builds.strawbs.net/macos/
What file format do you try to play?

**Comment by Arrow-x** [comment]
same issue with 0.9.3 (QT5)

**Comment by DonPicciotto** [comment]
Ehy @jonaski I have the same issue for the windows version
