### ISSUE TITLE
"Scroll over icon to change track" feature does not work on KDE Plasma

### ISSUE THREAD

**Issue by glaubersm** [jonaski/strawberry#130]
Hi

I use strawberry-full-git on Arch Linux running KDE Plasma 5.15.4 desktop environment, installed from AUR.

I enabled "Scroll over icon to change track" option in Stranwberry settings but nothing happens when I hover over Strawberry icon in systray and move the mouse wheel.

I already reported this issue in KDE bug tracker.
https://bugs.kde.org/show_bug.cgi?id=406682

David Edmundson, a KDE dev, wrote:
"We send the SNI scroll. If they don't pick it up that's an application bug."

**Comment by jonaski** [comment]
I find no easy way to fix this.
According to https://doc.qt.io/qt-5/qsystemtrayicon.html

> All X11 desktop environments that implement the D-Bus http://www.freedesktop.org/wiki/Specifications/StatusNotifierItem/StatusNotifierItem specification, including recent versions of KDE and Unity.

But there is no mouse scroll in QSystemTrayIcon::activated().
So I've disabled the setting on KDE:
https://github.com/jonaski/strawberry/commit/4887b85b8a71383ec6ad9816a24697a80104a5d5
I'd take advice on how to fix the feature if someone can give me some input. As for now it will be disabled on KDE.
But all other Qt 5 music players use the same approach as well, either inherit QSystemTrayIcon and use event(), or use the eventfiler.

**Comment by glaubersm** [comment]
Hi Jonas
Did you read the post from David Edmundson in the following bug report?
https://github.com/jonaski/strawberry/issues/51

**Comment by jonaski** [comment]
Yes, he says we need to use StatusNotifierItem, but according to the Qt documentation QSystemTrayIcon supports StatusNotifierItem, but there is no way to catch mouse scrolling with that.
There is a library called qt-sni, but it's really old and I think it's for Qt 4.
