### ISSUE TITLE
Two notifications on KDE Plasma when Strawberry starts to play the next track

### ISSUE THREAD

**Issue by glaubersm** [jonaski/strawberry#131]
Hi

I use strawberry-full-git on Arch Linux running KDE Plasma 5.15.4, installed from AUR.

Open Strawberry settings, click "Notifications" section in the left side.
Set "Show a native desktop notification" or "Show a popup from the system tray" as "Notitication type".
Add some tracks to your playlist, start playback and wait the track to finish.
When Strawberry starts to play the next track, it shows two notifications.
See the screenshots below.
Such behavior does not occur when I change to the next track manually.

![desktop notification](https://user-images.githubusercontent.com/15967631/56471836-7faf1f80-642d-11e9-99eb-f5ffc6cffeea.png)

![popup from systray](https://user-images.githubusercontent.com/15967631/56471837-7faf1f80-642d-11e9-9a41-7f872ded4724.png)

**Comment by jonaski** [comment]
I can't reproduce this anymore.

**Comment by schmittlauch** [comment]
I can confirm this is still the case with Strawberry 0.6.8 under NixOS 20.03 and Plasma 5.17.5.

The issue only appears when using the VLC backend, not with gstreamer, and only when a track ends and the next track of the playlist is started (not when skipping to the next track).
