### ISSUE TITLE
[Feature Request] Highlight/cursor follows playback

### ISSUE THREAD

**Issue by mroova** [jonaski/strawberry#133]
Currently highlight doesn't follow playback in a playlist - it creates a little inconvenience when I stop a song with a keyboard shortcut, and later want to continue by pressing enter - playback starts with the first song on the playlist (or any other that was highlighted).

**Comment by jonaski** [comment]
You can create specific shortcut for play/pause and use that instead of enter.
I don't really want to change the highlighted song.
