### ISSUE TITLE
Add favourite button when scrobbling with Last.fm

### ISSUE THREAD

**Issue by jorgicio** [jonaski/strawberry#134]
Hi!

Clementine has a heart button to like the song one's playing and scrobbling to last.fm. Sadly, Strawberry doesn't have it.
So I'm requesting that heart-like button as a feature, I hope, in future releases.

Thanks in advance!

**Comment by jonaski** [comment]
The feature is actually implemented, but it's just missing the button in the GUI. :smiley:

**Comment by emmanuel-galindo** [comment]
Hi, is there like a shortcut to use it in the meantime?
will it make sense to spend any time trying to add it and its pull request, or is there someone already doing it?
Thx mate

**Comment by jonaski** [comment]
Done https://github.com/jonaski/strawberry/commit/4875d319dc04524aaab74673f2f232874ed8b302
