### ISSUE TITLE
"Right" word is not properly positioned in Equalizer window

### ISSUE THREAD

**Issue by glaubersm** [jonaski/strawberry#136]
Hi

I use strawberry-full-git on Arch Linux running KDE Plasma 5.15.4, installed from AUR.
We can see the bug in the screenshot below.

![equalizer](https://user-images.githubusercontent.com/15967631/56517860-62a14c00-6514-11e9-9769-07ad9821dd84.png)

**Comment by jonaski** [comment]
Fixed https://github.com/jonaski/strawberry/commit/1e886cb12c033c902b343e01047da480a6f0a9a8
