### ISSUE TITLE
Strawberry takes ~3 seconds to close settings window when I click "Ok" button

### ISSUE THREAD

**Issue by glaubersm** [jonaski/strawberry#137]
Hi

I use strawberry-full-git on Arch Linux running KDE Plasma 5.15.4, installed from AUR.
Strawberry takes ~3 seconds to close settings window when I click "Ok" button
even if I do not change any setting.
The same window is closed immediately when I click X button in the upper right corner.

**Comment by jonaski** [comment]
It saves all the configuration when you press OK or apply, it does not trace every single setting and specifically saves that, that would involve a lot of extra code.
It is not normal to take 3 seconds if you have SSD, but if you have HDD it may take that long. It depends on the speed of your computer.
I've done significant testing of strawberry on 7 different distros including opensuse, fedora, arch, debian, ubuntu, pop!os not including different variants of those, and openbsd, macos and windows. In all those cases I've been in the settings, changed something and pressed OK. I have even set up a physical machine with KDE to test some of the keyboards shortcuts issues that were reported.
Even though I think the performance with Qt 5 in general is worse on a minimal default installation of arch with kde than with opensuse with kde and some of the other distros for no apparent explainable reason that I can see.
I've seen no problems on this, even macos where the performance is horrible in general does not have that problem.

**Comment by glaubersm** [comment]
I use a 7200 rpm hard disk.
