### ISSUE TITLE
Read artwork from DSF / DSDIFF files

### ISSUE THREAD

**Issue by jonaski** [jonaski/strawberry#14]
Playing DSF / DSDIFF files now works with gstreamer 1.15 or higher (unreleased).
Support for reading embedded artwork needs to be implemented.

**Comment by jonaski** [comment]
Not yet possible since it's not supported in taglib.

**Comment by Pragathi123362** [comment]
I am using 1.20 gstreamer but still i am uable to download or get the artwork for dsf files. Is this supported in gstreamer ?
