### ISSUE TITLE
Bad performance when window, side bar and columns are resized

### ISSUE THREAD

**Issue by glaubersm** [jonaski/strawberry#140]
Hi

I use strawberry-full-git on Arch Linux running KDE Plasma 5.15.4, installed from AUR.
There is some delay when I resize Strawberry window, the side bar and the columns.
Strawberry is the only Qt5 app installed on my system with such problem.
I recorded a video to compare Strawberry and Dolphin file manager while they are resized.

https://www.youtube.com/watch?v=z1_x_ffo4hk

**Comment by jonaski** [comment]
Fixed https://github.com/jonaski/strawberry/commit/170adfd00c09c4fb285f5d09d586e6f713b714e8

**Comment by glaubersm** [comment]
Perfect!
Strawberry is my default music player now. \o/
Thank you very much Jonas.
