### ISSUE TITLE
Sorting columns in fileview

### ISSUE THREAD

**Issue by punik** [jonaski/strawberry#141]
So many years have passed, and there are still no sorting columns in the file list. Neither in clementine nor here. Impossible to find new folders by date. it terribly infuriates

**Comment by jonaski** [comment]
I don't really plan to add that, I play to improve the collection library watcher/scanner and focus on that.

**Comment by martymac** [comment]
Hello,

+1. That would be a great feature indeed :)

Just adding a "date" column to the fileview would be enough and bring something very useful.

Any change regarding that decision ?

Best regards,

Ganael.

**Comment by jonaski** [comment]
Unfortunately we lack contributors, so I don't think so, I already got to much on my list.
