### ISSUE TITLE
Tidal: No URI handler implemented for "https".

### ISSUE THREAD

**Issue by quangduz** [jonaski/strawberry#142]
Hi,
I got error message when play Tidal music: 

> No URI handler implemented for "https".
or

> No URI handler implemented for "http".

I running Strawberry Player on Audiophile Linux (base: Arch linux).
Please help

**Comment by jonaski** [comment]
You are missing gstreamer plugins, you need gsttcp and gstsoup

**Comment by jonaski** [comment]
Try gst-inspect-1.0 souphttpsrc
Make sure you got plugins-good
Closing this as it is a gstreamer plugin issue.
