### ISSUE TITLE
Icons, fonts, cover art and volume indicator look fuzzy when fractional display scaling is used on KDE Plasma

### ISSUE THREAD

**Issue by glaubersm** [jonaski/strawberry#143]
Hi

**My system:**
Operating System: Arch Linux 
KDE Plasma Version: 5.15.4
KDE Frameworks Version: 5.57.0
Qt Version: 5.12.3

Title says by itself.
I use strawberry-full-git installed from AUR.

**Steps to reproduce:**
start KDE Plasma session
open system settings > Display and monitor > Displays
click "Scale display" button
adjust "Scale" slider to 1.2 and click "OK" button
restart KDE Plasma session
open Strawberry
As we see highlighted in red in the screenshots below, some icons, some fonts, cover art and volume indicator look fuzzy. 

![files](https://user-images.githubusercontent.com/15967631/56913463-190eaf00-6a88-11e9-8a89-03cd915ceee6.png)
![main](https://user-images.githubusercontent.com/15967631/56913464-190eaf00-6a88-11e9-968a-753d8073f2ae.png)
![menu](https://user-images.githubusercontent.com/15967631/56913466-190eaf00-6a88-11e9-9c1a-9ed7d52af82d.png)
![playlists](https://user-images.githubusercontent.com/15967631/56913468-19a74580-6a88-11e9-8a57-3d97bcd8d121.png)
![queue](https://user-images.githubusercontent.com/15967631/56913469-19a74580-6a88-11e9-9967-7a388b5d90b1.png)
![engine](https://user-images.githubusercontent.com/15967631/56914022-6e978b80-6a89-11e9-9af9-fa2b366d9175.png)
![output](https://user-images.githubusercontent.com/15967631/56914023-6f302200-6a89-11e9-90d0-b13891308ade.png)
![settings](https://user-images.githubusercontent.com/15967631/56914168-cafaab00-6a89-11e9-9783-b17754f2e1fc.png)

**Comment by jonaski** [comment]
I don't think the fuzzy icons is a application issue. Those icons on the OK, Apply and Cancel buttons are standard Qt (QDialogButtonBox) and they have the same issue as you point out.
I'm surprised windows etc looks this good with scaling enabled though as nothing is really optimized for scaling.

**Comment by glaubersm** [comment]
"OK", "Apply" and "Cancel" buttons of other Qt5 apps look fine.
See the screenshot of Kate text editor below, for example.
Below is the link of the same bug with fuzzy icons (already fixed) reported against other Qt5 app
https://bugs.kde.org/show_bug.cgi?id=397106

![kate](https://user-images.githubusercontent.com/15967631/57041136-e0add300-6c37-11e9-8802-775245ab0de6.png)

**Comment by jonaski** [comment]
That's a KDE application and not really comparable. Those use kde libraries and often not Qt directly.
If you go on Help / About Qt, the buttons there are similar and that dialog is plain Qt, not code or ui files from strawberry.
I've also tested a bunch of other applications in a virtualbox, those thay use similar color icons have the same issue.
An example is QDirStat:

![image](https://user-images.githubusercontent.com/10343810/57311112-50660700-70eb-11e9-8a4d-1b7ef6004a52.png)

**Comment by glaubersm** [comment]
maybe this Qt bug causes the fizzy icons
https://bugreports.qt.io/browse/QTBUG-52444
