### ISSUE TITLE
Equalizer does not work immediately if enabled while Strawberry plays a track

### ISSUE THREAD

**Issue by glaubersm** [jonaski/strawberry#144]
Hi

My system:
Operating System: Arch Linux
KDE Plasma Version: 5.15.4
KDE Frameworks Version: 5.57.0
Qt Version: 5.12.3

I use strawberry-full-git installed from AUR.

Reproducible with Gstreamer backend:
start Strawberry 
play a track
while Strawberry plays the track, enable the Equalizer in "Tools" menu > Equalizer
and select any preset: nothing changes
play another track or restart the current track: now the Equalizer works.

**Comment by jonaski** [comment]
This is done intentional. I don't link the gstreamer equalizer elements unless it's enabled because the equalizer resamples the audio, and we don't want that unless it's enabled. So you need to restart the playback or play next track for it to take affect.

**Comment by ecruz1986** [comment]
Hi, I was about to open this issue but found this.

I'm a new user and was confused when I tried to enable the equalizer for the first time. I had a song playing, and heard no change out of enabling and tweaking the EQ. Also I got no warning telling me to stop&play, so I just thought it was completely broken.

I think the current design is not optimal, it will always confuse new users as it has confused me.
I think it could be made better and we could have a more seamless user experience. I understand the audio flow shouldn't be linked to the resampler all the time, only when the EQ is on. But I think we should be able to stop the audio flow momentarily and relink it to the EQ resampler as the user checks the "Enable equalizer" checkbox , even if we need to simulate a quick stop&play, resuming from where it left off. It might result in a "pop", but maybe that could be handled by cross-fading, or just leave it there, better have the pop than not have this feature.

What do you think?

**Comment by prbuen** [comment]
It's useful to tweak the equalizer while the song is playing. You adjust the sliders until it sounds awesome :) Thanks for that great software btw! :)

**Comment by wjandrea** [comment]
I agree with @ecruz1986. I'd rather have a momentary glitch than have to research why it isn't working.

**Comment by jonholdsworth** [comment]
Agree, I'm happy if it glitches for a moment when engaging/disengaging, it's perfectly reasonable.

**Comment by mdcclxv** [comment]
Closed?! Just like that?! Really George?

**Comment by giorgiga** [comment]
@jonaski what about a warning message in the eq window?

As it is now, it's really difficult (straight-up impossible?) to guess what's the intended behavior and one ends up thinking the eq is bugged

**Comment by jonaski** [comment]
For now I added a tooltip to the equalizer that the playback needs to be restarted for the setting to take affect.
