### ISSUE TITLE
Clear Playlist Button Has No Confirmation and Can't be undone

### ISSUE THREAD

**Issue by Delphik** [jonaski/strawberry#145]
Having the Clear Playlist button next to the Save playlist button makes it easy to misclick and wipe a playlist you intended to save. It lacks a confirmation before you wipe the playlist and offers no way to undo the action.

**Comment by jonaski** [comment]
There are both undo and redo buttons to the right of the clear playlist button, also if you right click in the playlist view.

**Comment by Delphik** [comment]
Just double checked and the issue is only with playlists of a certain size. Clearing small playlists can be undone, but large playlists (in my case 4000 songs) are not able to be restored by undo if cleared

**Comment by jonaski** [comment]
I've added a confirmation dialog if the playlist has more than 500 songs. I've also added a button to the settings where you can disable the playlist clear button, you can still access the clear function by right clicking anyway.
