### ISSUE TITLE
Missing icons when installing from deb

### ISSUE THREAD

**Issue by dsejas** [jonaski/strawberry#146]
I just installed the last .deb file for Ubuntu from `http://builds.strawbs.net/`. When I launch Strawberry, the button on the left of the window are missing, except for the "queue" button. There are no "Media", "Playlists", etc. buttons there.

Unfortunately, I don't know why this happened, so i don't know how to reproduce it.

I tried to reinstall Strawberry, but now I get a "Segmentation fault (core dumped)" message.

Please, let me know if you require additional information.

**Comment by jonaski** [comment]
There are 3 ubuntu versions, which one?

**Comment by dsejas** [comment]
Oh, yes, sorry! I am using Ubuntu 18.04.2 (Bionic Beaver), so I downloaded https://builds.strawbs.net/ubuntu/bionic/strawberry_0.5.3-88-g42de7de_amd64.deb and the two previous ones

**Comment by dsejas** [comment]
Update: I have tried installing the newer DEB files, but the behavior remains.

The strange thing is that the same happens with the appimage file.

What I could find out is that the segmentation fault occurs after reinstalling. If I delete all the configuration/cache files and directories of Strawberry, the segfault disappears, but then the problem with the buttons returns.

A few days ago I successfully installed Strawberry, but the problem started when I tried to create a .desktop file for it (now it is deleted)

**Comment by jonaski** [comment]
I have found the problem, it's bug caused by a recent change I did to the tabwidget.

**Comment by jonaski** [comment]
I found the problem, the problem is that it was not loading at all if the configuration is empty, I had QMap instead of QMultiMap so only one tab was loading when the configuratio was blank.
Try this fix when it's finished building https://github.com/jonaski/strawberry/commit/96424be0da0092984d1c9c756655764b71388136

**Comment by dsejas** [comment]
I can confirm that it works beautifully now. Thank you very much!

Oh, by the way, I would like to take the opportunity to thank you for developing Strawberry. I really loved Clementine, but the maintenance was an issue worrying me. Strawberry is the solution! Keep up the good job!!!

One final question: Should I close this issue?

**Comment by jonaski** [comment]
Thank you very much, glad you found the problem as I am just doing final testing for a new release.
