### ISSUE TITLE
Error signing into Tidal

### ISSUE THREAD

**Issue by rdmarsee** [jonaski/strawberry#148]
When attempting to connect my TIDAL account, I get the following error message:
![auth_fail_strawbs](https://user-images.githubusercontent.com/15945867/57196071-4abfc400-6f27-11e9-953e-88982700bb57.png)
It lets me proceed, but then sends the same error message when I attempt to search for music in the TIDAL tab.

Using Strawberry installed from the stable Manjaro repos.

**Comment by jonaski** [comment]
Looks like they have changed their API, or closed it down.

**Comment by tcpj** [comment]
I have no trouble accessing API using my implementation in Go.

**Comment by jonaski** [comment]
Could you share the code or the login method you use?
I send HTTP POST to: https://listen.tidal.com/v1/login/username with the query items:
https://github.com/jonaski/strawberry/blob/master/src/tidal/tidalservice.cpp#L166

**Comment by tcpj** [comment]
Sure thing: https://github.com/tcpj/tidalgo/blob/master/tidal.go#L30

**Comment by jonaski** [comment]
I use one of the android tokens. They probably have stopped supporting the login method we use.

**Comment by tcpj** [comment]
There is high probability of them disabling token you have used. That's the reason I've omitted the key itself from code. There have been some changes in android app recently I guess this has something to do with. You can always dig new key from https://play.wimpmusic.com/ since these two applications are exactly the same, except WiMP being outdated and using keys that allows you stream unencrypted FLACs.

**Comment by jonaski** [comment]
Thanks, you use the same method but a different URL, changing the API url to https://api.tidalhifi.com/v1/ works.

**Comment by jonaski** [comment]
The token works, but maybe I should make it configurable anyway.

**Comment by tcpj** [comment]
No problem. I should revisit their API, haven't look for a year but there is no major update in applications beside Masters and allowing HiFi streaming in browsers other than chrome.

**Comment by jonaski** [comment]
Fixed https://github.com/jonaski/strawberry/commit/65648f8abd52344d8b08e07e9f39df7359a97b8f
I will make a new release again to include this fix.
