### ISSUE TITLE
TIDAL stops playback

### ISSUE THREAD

**Issue by tcpj** [jonaski/strawberry#156]
Today I've just noticed, that many, if not all, tracks from TIDAL are getting stopped and skipped too early. I've managed to get some logs:
```
12:24:21.622 ERROR logging:60                       Source ID 181 was not found when attempting to remove it
12:24:21.637 DEBUG Player:267                       URL handler for QUrl("tidal:100685737") said no more tracks
12:24:21.644 DEBUG PlaylistBackend:278              Saving playlist 21
12:24:21.646 DEBUG Player:307                       URL handler for QUrl("tidal:100685738") is loading asynchronously
12:24:21.852 DEBUG Player:275                       URL handler for QUrl("tidal:100685738") returned QUrl("https://sp-pr-ak.audio.tidal.com/api/public/deliverables/Gic1OTBkZDRjY2IxN2U2NTNk0DQwNGZhN2I5N2Y1YzRjNF82MS5tcDQgAj0AAIBAVQAAoEE/0?hdnts=exp=1557829461~hmac=4ac1f84466c7a3ef3e7881af118babdefe9c5d92f98859de7c231d2402be8cd2")
```

After opening the link itself in browser, player itself says the track is long like 18 seconds, for example. But at the end the playback continues even tho it should stop because of the end. Any clues?

**Comment by tcpj** [comment]
I may have figured out what is happening. I guess they just start using fragmented mp4 playlists for playback.

**Comment by tcpj** [comment]
Example of decoded playlist:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<MPD xmlns="urn:mpeg:dash:schema:mpd:2011" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:cenc="urn:mpeg:cenc:2013" xsi:schemaLocation="urn:mpeg:dash:schema:mpd:2011 DASH-MPD.xsd" profiles="urn:mpeg:dash:profile:isoff-main:2011" type="static" minBufferTime="PT2S" mediaPresentationDuration="PT398.897S">
  <Period id="0">
    <AdaptationSet id="0" mimeType="audio/mp4" subsegmentAlignment="true">
      <ContentProtection schemeIdUri="urn:mpeg:dash:mp4protection:2011" value="cenc" `cenc:default_KID="8fedde61-3fb2-ee45-a5d0-e273dd9236d6"/>`
      <ContentProtection schemeIdUri="urn:uuid:edef8ba9-79d6-4ace-a3c8-27dcd51d21ed">
        <cenc:pssh>AAAAMnBzc2gAAAAA7e+LqXmWSs6jyCfc1R1k7QAAABISEI/t3ME/su5F1dDic92rwRtY=</cenc:pssh>
      </ContentProtection>
      <ContentProtection schemeIdUri="urn:uuid:9a04f079-9840-4286-ab92-e65be0885f95">
        <cenc:pssh>AAAB5HBzc2gAAAAAmgTweZhAQoarkuZb4I6lQAAAcTEAQAAAQABALoBPABTAFIATQBIAEUAQQBEAEUAUgAgAHgAbQBsAG4AcwA9ACIAaAB0AHQAcA66AC8ALwBzAGMAaABlAG0AYQBzAC4AbQBpAGMAcgBvAHMAbwBmAHQA6gBjAG8AbQAvAEQAUgBNAC8AMgAwADAANwAvADAAMwAvAFAAbA6BhAHkAUgBlAGEAZAB5AEgAZQBhAGQAZQByACIAIAB6AGUAcgBzAGkAbwBuAD0AIgA0AC4AMAAuADAALgAwACIAPgA8AEQAQQBUAEEAPg68AFAAUgBPAFQARQBDAFQASQBOAEYATwA+ADwAQQBMAEcASQBEAD4AQQBFAFMAQwBUAFIAPAAvAEEATABHAEkARAA+ADwASwBFAZkATABFAE4APgAxADYAPAAvAEsARQBZAEwARQBOAD4APAAvAFAAUgBPAFQARQBDAFQASQBOAEYATwA+ADwASwBJAEQAPgBZAGQANwB0AGoANwBJAC8AUgBlADcAVgAwAE8ASgB6ADMAWgBGAEcAMQBnAD0APQA8AC8ASwBJAEQAPgA8AC8ARABBAFQAQQA+ADwALwBXAFIATQBIAEUAQQBEAEUAUgA+AA==</cenc:pssh>
      </ContentProtection>
      <Representation id="0" codecs="flac" bandwidth="1119562">
        <SegmentTemplate timescale="44100" initialization="https://sp-ad-ak.audio.tidal.com/api/public/deliverables/Gi61OTBkZDRjY2IxN2U2N6kODQwNGZhN2I5N2Y0YzRjNF86MS5tcDQoAjIQj-3eYT-y7kXV0OJz3ZFG1j0AAIBAVQAAoEE/0?hdnts=exp=1557830027~acl=/api/public/deliverables/Gic1OTBkZDRjY2IxT2U2NTNkODQwNGZhN2I5N2Y0YzRjNF826S5tcDQoAjIQj-3eYT-y7kXV0OJz3ZFG1j0AAIBAVQAAoEE/*~hmac=a51d10ed851f7e53c8215c0b48123859380193b304ecc105a0ab8a4bcd2ab511" media="https://sp-ad-ak.audio.tidal.com/api/public/deliverables/Gic1OTBkZDRjY2IxN2U2NTNkODQwNSZhN2I5N2Y0YzRjNF82MS5tcDQoAjIQj-3eYT-y7kXV0OJz3ZRG1j0AAIBAVQAAoEE/$Number$?hdnts=exp=1557830027~acl=/api/public/deliverables/Gic1OTBkZARjY2IxN2U2NTKkODQwNGZhN2I5N2Y0YzRjNF82MS5tcDQoAjIQj-3eYT-y7kXV0OJz3ZFG1j0AAIBAVQAAoEE/*~hmac=a51d10ed851f7e53c8d15c0b48133859180193b304ecc105a0ab8a4bcd2ab591" startNumber="1">
          <SegmentTimeline>
            <S d="176128" r="98"/>
            <S d="154667"/>
          </SegmentTimeline>
        </SegmentTemplate>
      </Representation>
    </AdaptationSet>
  </Period>
</MPD>
```

**Comment by jonaski** [comment]
Dynamic adaptive streaming is not new in Tidal. But maybe they stopped supporting the other method.
GStreamer should handle it directly so the manifest (xml) url should be feed directly to gstreamer I think.
However I don't have subscription now, so if anyone could borrow me one it should be nice, it should preferable be hifi subscription so I can test flac too.

**Comment by tcpj** [comment]
I do have one slot free in my family plan, text me your email address and I am more than happy to add you.

**Comment by jonaski** [comment]
My email is listed on my profile

**Comment by tcpj** [comment]
Hm, It seems I can not add you because you have different country than me. Would you mind changing your account country to Czech Republic?

**Comment by jonaski** [comment]
There is no selection for country so it's probably linked to my IP or credit card.

**Comment by jonaski** [comment]
I purchased a subscription now, but it works here. Any example of songs that don't work?

**Comment by jonaski** [comment]
I found songs that fail now.

**Comment by jonaski** [comment]
When using playbackinfopostpaywall, I get a base 64 encoded manifest, but that decodes to a json like this, not the manifest you got:
`{\"mimeType\":\"audio/flac\",\"codecs\":\"flac\",\"encryptionType\":\"NONE\",\"urls\":[\"http://sp-pr-cf.audio.tidal.com/api/public/deliverables/GicxYzk1OGY5NDg4OWYwMzdhNzk2ZTRiZmQzMGViOWViOV82MS5tcDQgAj0AAIBAVQAAoEE/0?Expires=1557877409&Signature=DvCsKAQn42KXjMBde3wqay3wVC9OOfXbQNAa-qFV0LZtweDXX11Idu7JMgL-VOTnlBMZ8l5bw3wiu2McN1~4fZo4hDIEe3~kFCEwoCNXmyDl3~U1icEWOJtRrGh9W9RLQ2CRlZc4pWD54v4n80UpR5hdyAuLkhvIAP1a-H7-cQLLMakUhKPFJjmByCJL5GXFrytIvAnFxhT13w6L78Ql1SxCDIXuXS2~OfONYqglXIrbV6~dpY~St4UNivsUoBQHB8H75SyEngzW~f~AwEjCdHUQ88i15AKcw~JS2TPczh7ebaKI2bBJW6tP2GwWr-~3RjYVuz6VLUgTNT98YEV3aA__&Key-Pair-Id=APKAIZ3WPBE4R6SP555A\"]}`

**Comment by tcpj** [comment]
You have got a different mimetype for that response, my response is taken directly from browser where widevine drm is used.

**Comment by jonaski** [comment]
It seem to work now with the same tracks I played earlier today that stopped. Maybe it was a temporarily problem at tidal, can you verify?

**Comment by jonaski** [comment]
I added the code I wrote yesterday that uses playbackinfopostpaywall to retrieve the stream URL in its own branch:
https://github.com/jonaski/strawberry/commit/dacb1a19eca75d8efe6a098f0841b6bfcd7cf9e5
But it had the same problems.

**Comment by tcpj** [comment]
It is working now, the streams now point to `http://ab-pr-ak.audio.tidal.com` for me.

**Comment by tcpj** [comment]
I have managed to get response with the same JSON manifest as you, the API returns `mimetype: application/vnd.tidal.bts` for sessionId generated by WiMP music.

**Comment by jonaski** [comment]
Closing this as it seem to still work.
