### ISSUE TITLE
Two Questions Embedded Artwork, and Advantages Over Clementine

### ISSUE THREAD

**Issue by nathan2423** [jonaski/strawberry#157]
1 - My main problem with Clementine is that I want to be able to download and embed cover art in the MP3 itself.  Is that something that Strawberry can do, or that you plan?

2 - Is there a list of advantages of Strawberry over Clementine?

Thanks!

**Comment by jonaski** [comment]
You can save the embedded cover to disk if you right click on a song or album and click "edit tracks information". Click on summary and "change cover art", there is an option to save to disk.
I've added a brief overview of some of the differences from clementine here:
https://github.com/jonaski/strawberry/wiki/Differences-from-Clementine

**Comment by nathan2423** [comment]
Just checking in again.  I do not mean simply save the cover art to disk. I mean EMBED it in the MP3 itself so that when other plays play the same file they will see the same artwork.  Sorry if I was not clear but just checking in today and it seems that is not possible, but it is an advantage that some other players have that would make Strawberry complete for me.

**Comment by nathan2423** [comment]
Also I just checked your list of differences with Clementine and I applaud you - I think you are on the right track - the features you pulled out I never used.  However the embedded cover art is something I dearly miss because I do move files from place to place and use different players at times, and if the cover art is not embedded in the mp3 then I have lots of wasted effort coordinating it again. Thanks for consideration!
