### ISSUE TITLE
Update UI to QtQuick

### ISSUE THREAD

**Issue by littlebifi** [jonaski/strawberry#158]
The current UI is not scalable to 4k (3840 × 2160 ). Additionally the design of the UI is very outdated.

**Comment by jonaski** [comment]
We like it and dont want to change it.

**Comment by littlebifi** [comment]
That's very unfortunate. I've planned to implement the scalable version myself to finally be able to identify the icons on my 4k screen.

**Comment by jonaski** [comment]
I dont want to switch to QML but it would be nice to optimize for scaling.
