### ISSUE TITLE
Feature Request: Better integration of playlists

### ISSUE THREAD

**Issue by thawkins** [jonaski/strawberry#159]
It would be cool to have the following. 

1. An "Add playlist" button on tbe transcoding dialog, as an additional source of tracks to be transcoded. 

2. An "Copy to device" context menu option for sending the contents of a playlist to a device. 

Justification: Playlists are a better mecha ism for selecting files in many cases, i have several playlists that i wish to send to a device for running or swimming with.

**Comment by jonaski** [comment]
There is an option already in the playlist context menu but the music files need to be in your collection for it to work.
