### ISSUE TITLE
Feature Request: Transcode direct to a device

### ISSUE THREAD

**Issue by thawkins** [jonaski/strawberry#160]
It would be usefull to be able to set the destination of a transcode to be a device, in the vast majority of cases the device is a mounted folder, but in some cases it is not.

**Comment by jonaski** [comment]
Copying files to devices is done by the organize dialog, and not the transcoder, the idea is that you edit the properties of a device and select the format you want to transcode to, then use the copy to device in the collection view to manage songs on the devices. It isn't really easy (or necessary) to add support directly to the transcoder dialog.
