### ISSUE TITLE
Feature Request: Keyboard Accelerators 

### ISSUE THREAD

**Issue by thawkins** [jonaski/strawberry#161]
Clementine/strawberry are almost unique amongst apps in not supporting keyboard accellerators. The one I miss the most is the ctrl-shift-v paste accelerator which pastes content in to an edit field, but there are many many more that are missing.

**Comment by jonaski** [comment]
We have keyboard Accelerators. ie. ALT + M for the Music in the menu.
You can see it by the underlined character, the underlines are missing on my system, maybe something I set in qt5ct, but accelerators still work.

**Comment by jonaski** [comment]
If the underlines on the menus are missing and you are not using a qt desktop but gtk, check in qt5ct that this option is checked:
![image](https://user-images.githubusercontent.com/10343810/58136783-aed4ce80-7c2f-11e9-8d5c-858541a49068.png)
