### ISSUE TITLE
is there a reason these files don't get indexed in library?

### ISSUE THREAD

**Issue by alekksander** [jonaski/strawberry#163]
https://www.dropbox.com/s/1o0ry2m8ocu5fve/Swiecie%20Nasz%20%28CD04%20-%20Magia%20Oblokow%29.7z?dl=1

it contains original album plus .cue edited by me to refer to proper file (switched wav to ape extension)
this album is a cut out from 15 CD's series and non of them get indexed by strawberry

**Comment by alekksander** [comment]
issue closed to hide link from external lurks.

@jonaski  could i please ask for Your opinion on this case?

**Comment by jonaski** [comment]
Because there are 2 cue files, and one of them still points to .wav in the FILE, it needs to be the exact filename of the audio file. It picked up the incorrect one and used that one.
Removing the broken cue file, or editing it and it works here.

**Comment by jonaski** [comment]
By the way you can send the dropbox box link to my email so you dont have to share them here if you want, so you dont have to infringe some copyright.

**Comment by dermamred** [comment]
[OFF TOPIC]

@alekksander Thanks... I discovered something new... Marek Grechuta is really a wonderful artist... he would deserve being know by more people.

[/OFF TOPIC]
