### ISSUE TITLE
compilation of strawberry 0.5.5 fails on Fedora 30

### ISSUE THREAD

**Issue by martinkg** [jonaski/strawberry#165]
Hi,

the compilation of strawberry 0.5.5 fails on Fedora 30 with the following error message:

cd /home/martin/rpmbuild/BUILD/strawberry-0.5.5/x86_64-redhat-linux-gnu/src && /usr/bin/cc -DBOOST_BIND_NO_PLACEHOLDERS -DNDEBUG -DQT_CONCURRENT_LIB -DQT_CORE_LIB -DQT_DBUS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_NO_CAST_TO_ASCII -DQT_NO_DEBUG -DQT_NO_DEBUG_OUTPUT -DQT_NO_URL_CAST_FROM_STRING -DQT_SQL_LIB -DQT_STRICT_ITERATORS -DQT_USE_QSTRINGBUILDER -DQT_WIDGETS_LIB -DQT_X11EXTRAS_LIB -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/home/martin/rpmbuild/BUILD/strawberry-0.5.5/x86_64-redhat-linux-gnu/3rdparty/taglib/headers/taglib -I/home/martin/rpmbuild/BUILD/strawberry-0.5.5/x86_64-redhat-linux-gnu/3rdparty/taglib/headers -I/home/martin/rpmbuild/BUILD/strawberry-0.5.5 -I/home/martin/rpmbuild/BUILD/strawberry-0.5.5/x86_64-redhat-linux-gnu/src -I/home/martin/rpmbuild/BUILD/strawberry-0.5.5/src -I/home/martin/rpmbuild/BUILD/strawberry-0.5.5/x86_64-redhat-linux-gnu -I/usr/include/gstreamer-1.0 -I/usr/include/orc-0.4 -I/home/martin/rpmbuild/BUILD/strawberry-0.5.5/3rdparty/singleapplication -I/home/martin/rpmbuild/BUILD/strawberry-0.5.5/ext/libstrawberry-common -I/home/martin/rpmbuild/BUILD/strawberry-0.5.5/ext/libstrawberry-tagreader -I/home/martin/rpmbuild/BUILD/strawberry-0.5.5/x86_64-redhat-linux-gnu/ext/libstrawberry-tagreader -I/usr/include/gpod-1.0 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/uuid -I/usr/include/p11-kit-1 -I/usr/include/libusb-1.0 -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtCore -isystem /usr/lib64/qt5/mkspecs/linux-g++ -isystem /usr/include/qt5/QtNetwork -isystem /usr/include/qt5/QtConcurrent -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtSql -isystem /usr/include/qt5/QtDBus -isystem /usr/include/qt5/QtX11Extras  -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -Wall -DNDEBUG   -fPIC -o CMakeFiles/strawberry_lib.dir/engine/xinescope.c.o   -c /home/martin/rpmbuild/BUILD/strawberry-0.5.5/src/engine/xinescope.c
/home/martin/rpmbuild/BUILD/strawberry-0.5.5/src/engine/xinescope.c: In function 'scope_port_put_buffer':
/home/martin/rpmbuild/BUILD/strawberry-0.5.5/src/engine/xinescope.c:81:20: error: 'metronom_t' {aka 'struct metronom_s'} has no member named 'pts_per_smpls'
   81 |     K  = myMetronom->pts_per_smpls; /*smpls = 1<<16 samples*/
      |                    ^~
make[2]: *** [src/CMakeFiles/strawberry_lib.dir/build.make:4942: src/CMakeFiles/strawberry_lib.dir/engine/xinescope.c.o] Error 1
make[2]: Leaving directory '/home/martin/rpmbuild/BUILD/strawberry-0.5.5/x86_64-redhat-linux-gnu'
make[2]: *** Waiting for unfinished jobs....
make[2]: Entering directory '/home/martin/rpmbuild/BUILD/strawberry-0.5.5/x86_64-redhat-linux-gnu'
[ 70%] Building CXX object src/CMakeFiles/strawberry_lib.dir/engine/xineengine.cpp.o
cd /home/martin/rpmbuild/BUILD/strawberry-0.5.5/x86_64-redhat-linux-gnu/src && /usr/bin/c++  -DBOOST_BIND_NO_PLACEHOLDERS -DNDEBUG -DQT_CONCURRENT_LIB -DQT_CORE_LIB -DQT_DBUS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_NO_CAST_TO_ASCII -DQT_NO_DEBUG -DQT_NO_DEBUG_OUTPUT -DQT_NO_URL_CAST_FROM_STRING -DQT_SQL_LIB -DQT_STRICT_ITERATORS -DQT_USE_QSTRINGBUILDER -DQT_WIDGETS_LIB -DQT_X11EXTRAS_LIB -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/home/martin/rpmbuild/BUILD/strawberry-0.5.5/x86_64-redhat-linux-gnu/3rdparty/taglib/headers/taglib -I/home/martin/rpmbuild/BUILD/strawberry-0.5.5/x86_64-redhat-linux-gnu/3rdparty/taglib/headers -I/home/martin/rpmbuild/BUILD/strawberry-0.5.5 -I/home/martin/rpmbuild/BUILD/strawberry-0.5.5/x86_64-redhat-linux-gnu/src -I/home/martin/rpmbuild/BUILD/strawberry-0.5.5/src -I/home/martin/rpmbuild/BUILD/strawberry-0.5.5/x86_64-redhat-linux-gnu -I/usr/include/gstreamer-1.0 -I/usr/include/orc-0.4 -I/home/martin/rpmbuild/BUILD/strawberry-0.5.5/3rdparty/singleapplication -I/home/martin/rpmbuild/BUILD/strawberry-0.5.5/ext/libstrawberry-common -I/home/martin/rpmbuild/BUILD/strawberry-0.5.5/ext/libstrawberry-tagreader -I/home/martin/rpmbuild/BUILD/strawberry-0.5.5/x86_64-redhat-linux-gnu/ext/libstrawberry-tagreader -I/usr/include/gpod-1.0 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/uuid -I/usr/include/p11-kit-1 -I/usr/include/libusb-1.0 -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtCore -isystem /usr/lib64/qt5/mkspecs/linux-g++ -isystem /usr/include/qt5/QtNetwork -isystem /usr/include/qt5/QtConcurrent -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtSql -isystem /usr/include/qt5/QtDBus -isystem /usr/include/qt5/QtX11Extras  -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection --std=c++11 -U__STRICT_ANSI__ -Wall -Woverloaded-virtual -Wno-sign-compare -Wno-deprecated-declarations -Wno-unused-local-typedefs -fpermissive -DNDEBUG   -fPIC -std=gnu++11 -o CMakeFiles/strawberry_lib.dir/engine/xineengine.cpp.o -c /home/martin/rpmbuild/BUILD/strawberry-0.5.5/src/engine/xineengine.cpp
/home/martin/rpmbuild/BUILD/strawberry-0.5.5/src/engine/xineengine.cpp: In member function 'virtual const Scope& XineEngine::scope(int)':
/home/martin/rpmbuild/BUILD/strawberry-0.5.5/src/engine/xineengine.cpp:912:25: error: 'metronom_t' {aka 'struct metronom_s'} has no member named 'pts_per_smpls'
  912 |     diff /= myMetronom->pts_per_smpls;
      |                         ^~~~~~~~~~~~~
make[2]: *** [src/CMakeFiles/strawberry_lib.dir/build.make:4929: src/CMakeFiles/strawberry_lib.dir/engine/xineengine.cpp.o] Error 1
make[2]: Leaving directory '/home/martin/rpmbuild/BUILD/strawberry-0.5.5/x86_64-redhat-linux-gnu'
make[1]: *** [CMakeFiles/Makefile2:497: src/CMakeFiles/strawberry_lib.dir/all] Error 2
make: *** [Makefile:133: all] Error 2``

**Comment by jonaski** [comment]
What version of xine is this? Compiling with xine 1.2.9 works fine here.

**Comment by martinkg** [comment]
# rpm -qa |grep xine
xine-lib-devel-1.2.9-13.20181129hg14263.fc30.x86_64
xine-lib-1.2.9-13.20181129hg14263.fc30.x86_64

**Comment by jonaski** [comment]
Try this fix https://github.com/jonaski/strawberry/commit/cecae7cdc3d5c550d5f394894265757f17620f5a
