### ISSUE TITLE
Make Fails With Error 2

### ISSUE THREAD

**Issue by yoruba-codigy** [jonaski/strawberry#166]
After Building, Build Files Are Stored In The Source Directory

Also, When I Run `make -j8`, This Is The Output:

`[  0%] Built target singlecoreapplication
[  1%] Built target singleapplication
[ 14%] Built target tag
[ 15%] Built target libstrawberry-common
ext/libstrawberry-tagreader/CMakeFiles/libstrawberry-tagreader.dir/build.make:61: *** target pattern contains no '%'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:531: ext/libstrawberry-tagreader/CMakeFiles/libstrawberry-tagreader.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
`

**Comment by jonaski** [comment]
You are missing protobuf compiler (protobuf-c)

**Comment by yoruba-codigy** [comment]
Still Getting The Error

`[ 17%] Built target libstrawberry-common
ext/libstrawberry-tagreader/CMakeFiles/libstrawberry-tagreader.dir/build.make:61: *** target pattern contains no '%'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:533: ext/libstrawberry-tagreader/CMakeFiles/libstrawberry-tagreader.dir/all] Error 2
make: *** [Makefile:130: all] Error 2`
