### ISSUE TITLE
compilation of strawberry 0.5.5 fails on Fedora 30

### ISSUE THREAD

**Issue by martinkg** [jonaski/strawberry#168]
Hi,

the compilation of strawberry 0.5.5 fails on Fedora 30 with the following error message:

`[ 70%] Building C object src/CMakeFiles/strawberry_lib.dir/engine/xinescope.c.o
cd /home/martin/rpmbuild/BUILD/strawberry-0.5.5/x86_64-redhat-linux-gnu/src && /usr/bin/cc -DBOOST_BIND_NO_PLACEHOLDERS -DNDEBUG -DQT_CONCURRENT_LIB -DQT_CORE_LIB -DQT_DBUS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_NO_CAST_TO_ASCII -DQT_NO_DEBUG -DQT_NO_DEBUG_OUTPUT -DQT_NO_URL_CAST_FROM_STRING -DQT_SQL_LIB -DQT_STRICT_ITERATORS -DQT_USE_QSTRINGBUILDER -DQT_WIDGETS_LIB -DQT_X11EXTRAS_LIB -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/home/martin/rpmbuild/BUILD/strawberry-0.5.5/x86_64-redhat-linux-gnu/3rdparty/taglib/headers/taglib -I/home/martin/rpmbuild/BUILD/strawberry-0.5.5/x86_64-redhat-linux-gnu/3rdparty/taglib/headers -I/home/martin/rpmbuild/BUILD/strawberry-0.5.5 -I/home/martin/rpmbuild/BUILD/strawberry-0.5.5/x86_64-redhat-linux-gnu/src -I/home/martin/rpmbuild/BUILD/strawberry-0.5.5/src -I/home/martin/rpmbuild/BUILD/strawberry-0.5.5/x86_64-redhat-linux-gnu -I/usr/include/gstreamer-1.0 -I/usr/include/orc-0.4 -I/home/martin/rpmbuild/BUILD/strawberry-0.5.5/3rdparty/singleapplication -I/home/martin/rpmbuild/BUILD/strawberry-0.5.5/ext/libstrawberry-common -I/home/martin/rpmbuild/BUILD/strawberry-0.5.5/ext/libstrawberry-tagreader -I/home/martin/rpmbuild/BUILD/strawberry-0.5.5/x86_64-redhat-linux-gnu/ext/libstrawberry-tagreader -I/usr/include/gpod-1.0 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/uuid -I/usr/include/p11-kit-1 -I/usr/include/libusb-1.0 -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtCore -isystem /usr/lib64/qt5/mkspecs/linux-g++ -isystem /usr/include/qt5/QtNetwork -isystem /usr/include/qt5/QtConcurrent -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtSql -isystem /usr/include/qt5/QtDBus -isystem /usr/include/qt5/QtX11Extras  -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -Wall -DNDEBUG   -fPIC -o CMakeFiles/strawberry_lib.dir/engine/xinescope.c.o   -c /home/martin/rpmbuild/BUILD/strawberry-0.5.5/src/engine/xinescope.c
/home/martin/rpmbuild/BUILD/strawberry-0.5.5/src/engine/xinescope.c: In function 'scope_port_put_buffer':
/home/martin/rpmbuild/BUILD/strawberry-0.5.5/src/engine/xinescope.c:83:20: error: 'metronom_t' {aka 'struct metronom_s'} has no member named 'pts_per_smpls'
   83 |     K  = myMetronom->pts_per_smpls; /*smpls = 1<<16 samples*/
      |                    ^~
/home/martin/rpmbuild/BUILD/strawberry-0.5.5/src/engine/xinescope.c: In function 'scope_plugin_new':
/home/martin/rpmbuild/BUILD/strawberry-0.5.5/src/engine/xinescope.c:153:37: error: 'xine_t' {aka 'struct xine_s'} has no member named 'port_ticket'
  153 |   post_plugin->running_ticket = xine->port_ticket;
      |                                     ^~
make[2]: *** [src/CMakeFiles/strawberry_lib.dir/build.make:4942: src/CMakeFiles/strawberry_lib.dir/engine/xinescope.c.o] Error 1`

complete error messages [1] and applied patch [2]
[1] https://martinkg.fedorapeople.org/ErrorReports/strawberry/strawberry-compile-error.txt
[2] https://martinkg.fedorapeople.org/ErrorReports/strawberry/strawberry-fix-xine-metronom-compile.patch

Regards
Martin

**Comment by eclipseo** [comment]
Where does that patch comes from? It seems it is the culprit of your build failure.

**Comment by martinkg** [comment]
a fix from jonaski
[cecae7c](https://github.com/jonaski/strawberry/commit/cecae7cdc3d5c550d5f394894265757f17620f5a)

**Comment by jonaski** [comment]
I believe this is because the version of xine on Fedora is not 1.2.9 at all, but unreleased code from their vcs that breaks because we need to use the xine internal stuff for the analyzer.
I see the metronom_s struct is changed and the metronom internal stuff removed. It's only used by the analyzer but I can't ifdef that based on the xine version as the version is still 1.2.9 in the header file.

**Comment by jonaski** [comment]
You can try this workaround: https://github.com/jonaski/strawberry/commit/8b05af7ca3bb0190e0a3ee168d33c7e014d5827d
It will still compile xine but without analyzer
Or you can disable xine engine with cmake -DENABLE_XINE=OFF

**Comment by martinkg** [comment]
with the 8b05af7 commit i get this error message:

`[ 69%] Building C object src/CMakeFiles/strawberry_lib.dir/engine/xinescope.c.o
cd /home/martin/rpmbuild/BUILD/strawberry-8b05af7ca3bb0190e0a3ee168d33c7e014d5827d/x86_64-redhat-linux-gnu/src && /usr/bin/cc -DBOOST_BIND_NO_PLACEHOLDERS -DNDEBUG -DQT_CONCURRENT_LIB -DQT_CORE_LIB -DQT_DBUS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_NO_CAST_TO_ASCII -DQT_NO_DEBUG -DQT_NO_DEBUG_OUTPUT -DQT_NO_URL_CAST_FROM_STRING -DQT_SQL_LIB -DQT_STRICT_ITERATORS -DQT_USE_QSTRINGBUILDER -DQT_WIDGETS_LIB -DQT_X11EXTRAS_LIB -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/home/martin/rpmbuild/BUILD/strawberry-8b05af7ca3bb0190e0a3ee168d33c7e014d5827d/x86_64-redhat-linux-gnu/3rdparty/taglib/headers/taglib -I/home/martin/rpmbuild/BUILD/strawberry-8b05af7ca3bb0190e0a3ee168d33c7e014d5827d/x86_64-redhat-linux-gnu/3rdparty/taglib/headers -I/home/martin/rpmbuild/BUILD/strawberry-8b05af7ca3bb0190e0a3ee168d33c7e014d5827d -I/home/martin/rpmbuild/BUILD/strawberry-8b05af7ca3bb0190e0a3ee168d33c7e014d5827d/x86_64-redhat-linux-gnu/src -I/home/martin/rpmbuild/BUILD/strawberry-8b05af7ca3bb0190e0a3ee168d33c7e014d5827d/src -I/home/martin/rpmbuild/BUILD/strawberry-8b05af7ca3bb0190e0a3ee168d33c7e014d5827d/x86_64-redhat-linux-gnu -I/usr/include/gstreamer-1.0 -I/usr/include/orc-0.4 -I/home/martin/rpmbuild/BUILD/strawberry-8b05af7ca3bb0190e0a3ee168d33c7e014d5827d/3rdparty/singleapplication -I/home/martin/rpmbuild/BUILD/strawberry-8b05af7ca3bb0190e0a3ee168d33c7e014d5827d/ext/libstrawberry-common -I/home/martin/rpmbuild/BUILD/strawberry-8b05af7ca3bb0190e0a3ee168d33c7e014d5827d/ext/libstrawberry-tagreader -I/home/martin/rpmbuild/BUILD/strawberry-8b05af7ca3bb0190e0a3ee168d33c7e014d5827d/x86_64-redhat-linux-gnu/ext/libstrawberry-tagreader -I/usr/include/gpod-1.0 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/uuid -I/usr/include/p11-kit-1 -I/usr/include/libusb-1.0 -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtCore -isystem /usr/lib64/qt5/mkspecs/linux-g++ -isystem /usr/include/qt5/QtNetwork -isystem /usr/include/qt5/QtConcurrent -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtSql -isystem /usr/include/qt5/QtDBus -isystem /usr/include/qt5/QtX11Extras  -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -Wall -DNDEBUG   -fPIC -o CMakeFiles/strawberry_lib.dir/engine/xinescope.c.o   -c /home/martin/rpmbuild/BUILD/strawberry-8b05af7ca3bb0190e0a3ee168d33c7e014d5827d/src/engine/xinescope.c
/home/martin/rpmbuild/BUILD/strawberry-8b05af7ca3bb0190e0a3ee168d33c7e014d5827d/src/engine/xinescope.c: In function 'scope_port_put_buffer':
/home/martin/rpmbuild/BUILD/strawberry-8b05af7ca3bb0190e0a3ee168d33c7e014d5827d/src/engine/xinescope.c:83:20: error: 'metronom_t' {aka 'struct metronom_s'} has no member named 'pts_per_smpls'
   83 |     K  = myMetronom->pts_per_smpls; /*smpls = 1<<16 samples*/
      |                    ^~
/home/martin/rpmbuild/BUILD/strawberry-8b05af7ca3bb0190e0a3ee168d33c7e014d5827d/src/engine/xinescope.c: In function 'scope_plugin_new':
/home/martin/rpmbuild/BUILD/strawberry-8b05af7ca3bb0190e0a3ee168d33c7e014d5827d/src/engine/xinescope.c:153:37: error: 'xine_t' {aka 'struct xine_s'} has no member named 'port_ticket'
  153 |   post_plugin->running_ticket = xine->port_ticket;
      |                                     ^~
make[2]: *** [src/CMakeFiles/strawberry_lib.dir/build.make:5070: src/CMakeFiles/strawberry_lib.dir/engine/xinescope.c.o] Error 1
make[2]: Leaving directory '/home/martin/rpmbuild/BUILD/strawberry-8b05af7ca3bb0190e0a3ee168d33c7e014d5827d/x86_64-redhat-linux-gnu'
make[2]: *** Waiting for unfinished jobs....
make[2]: Entering directory '/home/martin/rpmbuild/BUILD/strawberry-8b05af7ca3bb0190e0a3ee168d33c7e014d5827d/x86_64-redhat-linux-gnu'
[ 68%] Building CXX object src/CMakeFiles/strawberry_lib.dir/engine/xineengine.cpp.o
cd /home/martin/rpmbuild/BUILD/strawberry-8b05af7ca3bb0190e0a3ee168d33c7e014d5827d/x86_64-redhat-linux-gnu/src && /usr/bin/c++  -DBOOST_BIND_NO_PLACEHOLDERS -DNDEBUG -DQT_CONCURRENT_LIB -DQT_CORE_LIB -DQT_DBUS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_NO_CAST_TO_ASCII -DQT_NO_DEBUG -DQT_NO_DEBUG_OUTPUT -DQT_NO_URL_CAST_FROM_STRING -DQT_SQL_LIB -DQT_STRICT_ITERATORS -DQT_USE_QSTRINGBUILDER -DQT_WIDGETS_LIB -DQT_X11EXTRAS_LIB -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/home/martin/rpmbuild/BUILD/strawberry-8b05af7ca3bb0190e0a3ee168d33c7e014d5827d/x86_64-redhat-linux-gnu/3rdparty/taglib/headers/taglib -I/home/martin/rpmbuild/BUILD/strawberry-8b05af7ca3bb0190e0a3ee168d33c7e014d5827d/x86_64-redhat-linux-gnu/3rdparty/taglib/headers -I/home/martin/rpmbuild/BUILD/strawberry-8b05af7ca3bb0190e0a3ee168d33c7e014d5827d -I/home/martin/rpmbuild/BUILD/strawberry-8b05af7ca3bb0190e0a3ee168d33c7e014d5827d/x86_64-redhat-linux-gnu/src -I/home/martin/rpmbuild/BUILD/strawberry-8b05af7ca3bb0190e0a3ee168d33c7e014d5827d/src -I/home/martin/rpmbuild/BUILD/strawberry-8b05af7ca3bb0190e0a3ee168d33c7e014d5827d/x86_64-redhat-linux-gnu -I/usr/include/gstreamer-1.0 -I/usr/include/orc-0.4 -I/home/martin/rpmbuild/BUILD/strawberry-8b05af7ca3bb0190e0a3ee168d33c7e014d5827d/3rdparty/singleapplication -I/home/martin/rpmbuild/BUILD/strawberry-8b05af7ca3bb0190e0a3ee168d33c7e014d5827d/ext/libstrawberry-common -I/home/martin/rpmbuild/BUILD/strawberry-8b05af7ca3bb0190e0a3ee168d33c7e014d5827d/ext/libstrawberry-tagreader -I/home/martin/rpmbuild/BUILD/strawberry-8b05af7ca3bb0190e0a3ee168d33c7e014d5827d/x86_64-redhat-linux-gnu/ext/libstrawberry-tagreader -I/usr/include/gpod-1.0 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/uuid -I/usr/include/p11-kit-1 -I/usr/include/libusb-1.0 -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtCore -isystem /usr/lib64/qt5/mkspecs/linux-g++ -isystem /usr/include/qt5/QtNetwork -isystem /usr/include/qt5/QtConcurrent -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtSql -isystem /usr/include/qt5/QtDBus -isystem /usr/include/qt5/QtX11Extras  -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection --std=c++11 -U__STRICT_ANSI__ -Wall -Woverloaded-virtual -Wno-sign-compare -Wno-deprecated-declarations -Wno-unused-local-typedefs -fpermissive -DNDEBUG   -fPIC -std=gnu++11 -o CMakeFiles/strawberry_lib.dir/engine/xineengine.cpp.o -c /home/martin/rpmbuild/BUILD/strawberry-8b05af7ca3bb0190e0a3ee168d33c7e014d5827d/src/engine/xineengine.cpp
make[2]: Leaving directory '/home/martin/rpmbuild/BUILD/strawberry-8b05af7ca3bb0190e0a3ee168d33c7e014d5827d/x86_64-redhat-linux-gnu'
make[1]: *** [CMakeFiles/Makefile2:440: src/CMakeFiles/strawberry_lib.dir/all] Error 2
make: *** [Makefile:133: all] Error 2`

**Comment by jonaski** [comment]
Fixed https://github.com/jonaski/strawberry/commit/28ee967371d16ed717c49fa02193b08c7f676d0e
