### ISSUE TITLE
Strawberry crash on Fedora

### ISSUE THREAD

**Issue by steve12l** [jonaski/strawberry#17]
I'm on Fedora 28 and so far Strawberry worked well but now when i want to listen music i have this : 

`/usr/include/c++/8/bits/stl_vector.h:932: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](std::vector<_Tp, _Alloc>::size_type) [with _Tp = float; _Alloc = std::allocator<float>; std::vector<_Tp, _Alloc>::reference = float&; std::vector<_Tp, _Alloc>::size_type = long unsigned int]: Assertion '__builtin_expect(__n < this->size(), true)' failed.
Aborted (core dumped)`

And i don't unsertsand what's wrong. Everything was fine before.

**Comment by jonaski** [comment]
This looks like a crash happening in a library and not strawberry itself, looks to be libstdc related.
What version of strawberry are you using and from where?
What songs (formats) are you trying?

**Comment by steve12l** [comment]
I use Version 0.3.1-23-gc77cb00 directly from the Strawberry website.
Mostly .mp3 songs and Strawberry worked perfectly at the beginning.
I tried to remove Strawberry, clean strawberry files and reinstall it but same problem.

**Comment by jonaski** [comment]
Try this: https://download.opensuse.org/repositories/home:/jonaski:/audio/Fedora_28/x86_64/

**Comment by jonaski** [comment]
(Version 0.3.3 that I used released now)

**Comment by jonaski** [comment]
Reopen if you still have an issue

**Comment by steve12l** [comment]
I have the 0.3.3 version and still the same problem

**Comment by jonaski** [comment]
The problem seem to be related to the analyzer. Right click on the analyzer (the blue area between the playlist and the progress bar) and select No analyzer. It should be a temporary fix.

**Comment by steve12l** [comment]
That works but I have no sound and I have sound with other software like Clementine, vlc...
I am going to search in strawberry to see if I find the problem.

**Comment by jonaski** [comment]
The crash should be fixed in commit 3694765.
No sound should be unreleated to this. Try setting output to "Wrapper audio sink for automatically detected" in backend settings.

**Comment by steve12l** [comment]
It's ok now !
Thanks for your help and answers.
Have a good day.
