### ISSUE TITLE
Logotype for Strawberry

### ISSUE THREAD

**Issue by zuurw** [jonaski/strawberry#170]
Hi, how are you? I'd like to collaborate on your open source project and propose free logo/icon design for this project. If it's something you're interested in, please, let me know!
Best Regards
Zuur

**Comment by jonaski** [comment]
Yes that would be very cool.

**Comment by zuurw** [comment]
Hi, I would like to know what do you want for this logo, can you give me something to get inspired?

Thank you!

Best Regards!

**Comment by jonaski** [comment]
We could use some unique icons especially designed for strawberry.

For example:

* New icons for the playback buttons.
* Customized icons for the tabbar and the settings.
* A new background image
* An icon we could use for the tray that would work better for drawing the track progress

If you want to make a logo for strawberry it would be inspired by some of the Strawbs album cover art, these for example:

https://www.albumartexchange.com/covers/252842-hero-and-heroine?q=strawbs+hero&fltr=ALL&sort=DATE&status=&size=any

http://www.strawbsweb.co.uk/albtrack/covrgifs/taste.jpg
