### ISSUE TITLE
Fix hardcoded icons

### ISSUE THREAD

**Issue by jorgicio** [jonaski/strawberry#175]
Hi!

I reported on Papirus icon theme repo to add the Strawberry icon. Although it's applied, I noted the icons are hardcoded, so the theme would not be applied for the tray icon. See [here](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/issues/1723) for more details. So a suggestion would be fix hardcoded icons.

Thanks in advice.

**Comment by jonaski** [comment]
What icons are hardcoded?

**Comment by jorgicio** [comment]
I think icons in general, as well as mentioned in a comment on the thread I published above. The specific line mentioned is this: https://github.com/jonaski/strawberry/blob/master/src/core/qtsystemtrayicon.cpp#L49

**Comment by jonaski** [comment]
I fixed the systemtray icon now, but don't know any others. https://github.com/jonaski/strawberry/commit/540b6eba0401ae5e4d060c44b4e9f0b399ba1483
