### ISSUE TITLE
Enable Tidal Download for albums and tracks

### ISSUE THREAD

**Issue by Fef0** [jonaski/strawberry#176]
Hey, great work as always!
Since Tidal allows to download every track/album, would be possible to implement it in Strawberry?
It is possible to download a track having its streaming url, so QNetwork or libcurl should get the job done (the first won't modify the actual dependencies either).
I think it would be a great add that actually every other bit-perfect player lacks.

**Comment by jonaski** [comment]
We don't want to allow downloads, doing that could potentially get us deleted from github.
