### ISSUE TITLE
Background album zoom feature

### ISSUE THREAD

**Issue by gianlucapettinello** [jonaski/strawberry#177]
If possible it would be great that the album cover zooms so that it fills the Playlist fully while keeping ratio. Pleaseeeee :}

**Comment by jonaski** [comment]
Already got that:

![image](https://user-images.githubusercontent.com/10343810/59553755-e66a3880-8f99-11e9-9411-9a297adb7e0f.png)

Or do you mean cut the image too?

**Comment by gianlucapettinello** [comment]
The stretch deform the album art I mean to take the widest between the width and height of the Playlist and zoom to that cutting a bit the picture, typically the height. Thanks :)

**Comment by gianlucapettinello** [comment]
Any update on this? Thanks

**Comment by m4x3t** [comment]
I'd also want that feature so I will see if I can add it.
