### ISSUE TITLE
OPUS files are quiter than MP3/FLAC files with Replay Gain

### ISSUE THREAD

**Issue by CypherNL** [jonaski/strawberry#178]
My music library has a lot of OPUS files with MP3 files and FLAC files in between. All of them are scanned with replay gain (OPUS uses R128 instead op Replay Gain).

What i hear is that if i play an OPUS file, the music plays at a lower volume than a MP3 or FLAC file. This difference is clearly noticeable.

I've tested this on MusicBee and on foobar2000 and both play the OPUS and MP3/FLAC files at the same volume (MusicBee had also this issue but is fixed on the latest versions). This is on the Windows 10 LTSB 2016 Operating System.

I'm reporting this on Arch Linux with the latest Strawberry version 0.5.5. I'm sure this issue also occurs on Windows as it's player specific than an Operating System one.

If you need more information, please let me know.

**Comment by jonaski** [comment]
It's a gstreamer issue
https://gitlab.freedesktop.org/gstreamer/gst-plugins-base/issues/210
I don't think I can do much to fix it.
