### ISSUE TITLE
macOS Native widgets on nightly builds

### ISSUE THREAD

**Issue by llucps** [jonaski/strawberry#184]
I downloaded the latest nightly build from https://builds.strawbs.org/macos/ and I was surprised to see that the interface doesn't look native at all.

![Screenshot 2019-06-20 at 06 46 29](https://user-images.githubusercontent.com/25823659/59844319-976d2c00-9328-11e9-91b2-813ed531279b.jpg)

Then I decided to compile the application myself and then all the widgets are native (tabs, scroll bars, buttons etc.)

![Screenshot 2019-06-20 at 06 47 25](https://user-images.githubusercontent.com/25823659/59844333-9f2cd080-9328-11e9-807a-8a222f88288e.jpg)

Do you know why? It's not a deal breaker, just curious to know the reason.

By the way I just realized that the nightly build only takes 123MB in memory and the one I compiled myself following the instructions in your Wiki takes up to 730MB! there must be something wrong obviously :)

Thanks,

**Comment by jonaski** [comment]
Those builds are experimental, I don't make releases for macOS. I don't have a macOS so I can't really look into it and currently there isn't any developer for macOS.

**Comment by jonaski** [comment]
According to: https://doc.qt.io/archives/qt-5.11/osx-deployment.html#qt-plugins

> Qt Plugins
> All Qt GUI applications require a plugin that implements the Qt Platform Abstraction (QPA) layer in Qt 5. For macOS, the name of the platform plugin is libqcocoa.dylib. This file must be located within a specific subdirectory (by default, platforms) under your distribution directory. Alternatively, it is possible to adjust the search path Qt uses to find its plugins, as described below.

Maybe it does not find that plugin

**Comment by jonaski** [comment]
@MartinDelille

**Comment by MartinDelille** [comment]
I don't have the issue when building locally strawberry with Qt Creator...

**Comment by MartinDelille** [comment]
Ok I think running the official `macdeployqt` tool should fix the problem.

**Comment by jonaski** [comment]
Can you try the build from here and see if that works? https://builds.strawbs.net/macos-test/
