### ISSUE TITLE
Album cover and details information subsonic support

### ISSUE THREAD

**Issue by llucps** [jonaski/strawberry#185]
Would it be possible to add the album cover and Artist/Song/Album details for Subsonic? The same way as clementine has.

Clementine:
![Screenshot 2019-06-20 at 07 01 50](https://user-images.githubusercontent.com/25823659/59844765-a56f7c80-9329-11e9-912e-e675c5b4d4e7.jpg)

Thanks,

**Comment by jonaski** [comment]
What song details? It downloads album covers or displays them directly from the url there is an setting for it.

**Comment by llucps** [comment]
Strange... I deleted the preferences and started from scratch now it shows up.. thanks!
