### ISSUE TITLE
Strawberry icon missing on macOS

### ISSUE THREAD

**Issue by llucps** [jonaski/strawberry#186]
FYI, the strawberry icon on nightly builds and self compiled is missing, although once the application is lunched it shows up on the Dock.

![Screenshot 2019-06-20 at 07 12 19](https://user-images.githubusercontent.com/25823659/59845225-e320d500-932a-11e9-8910-61babef6ca30.jpg)
![Screenshot 2019-06-20 at 07 12 47](https://user-images.githubusercontent.com/25823659/59845226-e320d500-932a-11e9-91b9-66de0131c7db.jpg)
![Screenshot 2019-06-20 at 07 12 56](https://user-images.githubusercontent.com/25823659/59845228-e320d500-932a-11e9-8733-78f91f60359a.jpg)

**Comment by jonaski** [comment]
Those builds are experimental, I don't make releases for macOS. I don't have macOS so I can't really look into it and currently there isn't any developer for macOS.

**Comment by jonaski** [comment]
@martindelille

**Comment by MartinDelille** [comment]
I personnaly use this tools that works great.

Anyway there is a problem with the application icon outside of the DMG because it should show up in the finder.

I know how to make MacOS icon for Qt but I'm not very familiar with cmake. Can you explain me how you generate the current icon so I can fix it?

**Comment by MartinDelille** [comment]
Otherwise the biggest resolution for a macos icon is 1024x1024 (because of retina display).

I saw this high res picture but that 1000x1000. Three options:

- Increase the size to 1024 with upsampling (might degrade the quality
- Increase the size without scaling the strawberry
- Generate a new 1024x1024 from an SVG or other source format

**Comment by jonaski** [comment]
I think generated the current icon using imagemagick, just coverted the png or svg to the icns file.
The icon is here;
https://github.com/jonaski/strawberry/blob/master/dist/macos/strawberry.icns

Its installed here:
https://github.com/jonaski/strawberry/blob/master/dist/CMakeLists.txt#L28

There is a svg and png file in https://github.com/jonaski/strawberry/tree/master/data/icons/full of the strawberry icon.
You can just recreate the icns file based on that if it's wrong.

**Comment by MartinDelille** [comment]
When I convert [strawberry.svg](https://github.com/jonaski/strawberry/blob/master/data/icons/full/strawberry.svg) to png, its only 38x38 wide.

**Comment by jonaski** [comment]
Looks like that svg is not the real svg at all, just a one I created using convert.
I think I never had the orignal vector graphics, so you need to use the png.
The largest I got is 1000x1000

**Comment by jonaski** [comment]
Actually I think the svg is the original one, because it says inkscape when I open it, but I get the same result as you when I try to export to png, but I don't have much clue about vector graphics

**Comment by MartinDelille** [comment]
It isn't a true SVG: if you look inside it is in fact a base 64 version of a 38x38 bitmap.

**Comment by MartinDelille** [comment]
Ok I manage fixing the bundle locally by adding the following `strawberry.app/Content/Info.plist` file:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleDisplayName</key>
	<string>strawberry</string>
	<key>CFBundleExecutable</key>
	<string>strawberry</string>
	<key>CFBundleIconFile</key>
	<string>strawberry.icns</string>
	<key>CFBundleIdentifier</key>
	<string>net.strawbs.strawberry</string>
	<key>CFBundleName</key>
	<string>strawberry</string>
	<key>CFBundleShortVersionString</key>
	<string>0.5.5.168</string>
	<key>CFBundleVersion</key>
	<string>0.5.5.168</string>
	<key>LSMinimumSystemVersion</key>
	<string>10.8</string>
	<key>NSHighResolutionCapable</key>
	<string>True</string>
</dict>
</plist>
```

<img width="712" alt="Screenshot 2019-07-17 at 21 54 23" src="https://user-images.githubusercontent.com/879889/61407198-7a069000-a8dd-11e9-93cb-78066192a3f4.png">

**Comment by jonaski** [comment]
Fixed https://github.com/jonaski/strawberry/commit/45125abb8f674e80ee259fb3007ad1f29c52581a
