### ISSUE TITLE
Warn users before opening 'lots' of directories using 'show file in browser'...

### ISSUE THREAD

**Issue by 234845** [jonaski/strawberry#187]
First of all, thanks for Strawberry, it's a pleasure to use.

I create various playlists from all my collection, which is located in many hundreds of directories within my 'music' folder. By mistake I had an entire Playlist selected (~ 500 songs) and wasn't paying attention and thinking I had just selected one track I chose 'show file in browser'.

Oops.

My OS - in this case Windows - started opening all of these directories in their own separate explorer window and I couldn't stop it :)

a few minutes later ... after my PC had pretty much ground to a halt - I managed to 'close all' and was back working again. I wonder if we could introduce an 'are you sure' warning before allowing, say, more than a dozen different 'music folders' to be opened by accident.

Thanks for your time and keep up the good work!

**Comment by jonaski** [comment]
Sure, I can add a limit.

**Comment by jonaski** [comment]
Made a limit to 50 songs, and if more than 5 is selected a confirmation box will appear.
https://github.com/jonaski/strawberry/commit/647e7e708acdb5db64a2b5f2891fcb773de2b9e9

**Comment by 234845** [comment]
Gosh! That was fast. Thank you :)
