### ISSUE TITLE
Slider cannot be used most of the time

### ISSUE THREAD

**Issue by ScrewTSW** [jonaski/strawberry#189]
The song playback slider is being overlayed by the timestamp bubble, which cases the window being moved around when clicked and dragged instead of jumping through the song.

![strawberry_song_slider_behavior](https://user-images.githubusercontent.com/16451875/60103848-9ee56880-9760-11e9-84a4-b50ec853b818.gif)

**Comment by jonaski** [comment]
I dont understand what this is about

**Comment by ScrewTSW** [comment]
Sometimes, as you can see in the gif, instead of moving the nob to change the position in track, the click and drag event moves the window instead.

Interacting with the slider should always cause the position in the track to be changed.

The behaviour of the slider itself is also strange as well, it's snapping to certain points instead of having a full granularity.

**Comment by jonaski** [comment]
I can't reproduce this here. I think it might be related to your configuration somehow.
