### ISSUE TITLE
UI getting stuck on Tidal

### ISSUE THREAD

**Issue by ScrewTSW** [jonaski/strawberry#191]
Sometimes it happens that none of the buttons work at all.
Switching between Tidal, playlists, songs and such, or even the Tidal search iteself (cannot switch between artist/album/song) If I search for some, I cannot expand the artist/album.

Using Fedora 30 (previously 29) kernel 5.1.12-300.fc30.x86_64

It used to sometimes help to quit Strawberry through the main menu, but right now I'm permanently stuck on the Tidal tab (latest 0.5.5 build from `rpm`)

**Comment by jonaski** [comment]
Try with a new configration, delete (or rename) ~/.local/share/strawberry, ~/.config/strawberry and ~/.cache/strawberry
