### ISSUE TITLE
Fedora version 30  Cannot login to Tidal - SSL handshake failed (6)

### ISSUE THREAD

**Issue by caedmon-kitty** [jonaski/strawberry#194]
Adding username and password to the Tidal settings and hitting the Login button results in a popup

"Authentication Failed
SSL handshake failed (6)"

Same username and login work in my browser.

**Comment by jonaski** [comment]
Can you open https://api.tidalhifi.com/v1/login/username ?

**Comment by caedmon-kitty** [comment]
Using browsers I get

{"status":405,"subStatus":1003,"userMessage":"Method not allowed"}

openssl s_client -connect api.tidalhifi.com:443
connects successfully.

**Comment by jonaski** [comment]
Strange. You usually get "SSL handshake failed" if the certificate is expired or not trusted.
I tested here on Fedora 30 with 0.5.5 from the repository in a virtual box and it works here.

**Comment by caedmon-kitty** [comment]
Any way to debug the dialog?

**Comment by jonaski** [comment]
Try the AppImage it will rule out any dependencies, ssl/tls support in qt / openssl.
https://github.com/jonaski/strawberry/releases/download/0.5.5/Strawberry-0.5.5.AppImage
Just chmod +x the file and run it.

**Comment by jonaski** [comment]
I added some more error output when there is a SSL error it should show a more specific error. It's in commit https://github.com/jonaski/strawberry/commit/65780e1672c5d534113a1469352f51ed945eccf6 and development builds should be ready in a few hours. (but if you use them you won't be able to go back to 0.5.5 unless you delete your db (strawberry.db) as the db schemas are not compatible anymore).
But the problem itself is probably on your system or your connection somehow.

**Comment by caedmon-kitty** [comment]
Output from running the appimage.

13:40:46.464 INFO  main:160                         Strawberry 0.5.5
__logging_message__13:40:46.611 WARN  unknown                          QFileSyst
emWatcher::removePaths: list is empty
__logging_message__13:40:46.611 WARN  unknown                          QFileSyst
emWatcher::removePaths: list is empty
13:40:46.614 DEBUG NetworkProxyFactory:55           Detected system proxy URLs:
("", "", "", "")
13:40:46.616 DEBUG WorkerPool<HandlerType>:275      Starting worker 0x7f2971ffa3
c0 "/tmp/.mount_StrawbC3nsn3/usr/bin/strawberry-tagreader" "/tmp/strawberry_5128
78241"
13:40:46.617 DEBUG WorkerPool<HandlerType>:275      Starting worker 0x7f2971ffa3
c0 "/tmp/.mount_StrawbC3nsn3/usr/bin/strawberry-tagreader" "/tmp/strawberry_1145
909467"
13:40:46.618 DEBUG WorkerPool<HandlerType>:275      Starting worker 0x7f2971ffa3
c0 "/tmp/.mount_StrawbC3nsn3/usr/bin/strawberry-tagreader" "/tmp/strawberry_4841
76500"
13:40:46.620 DEBUG WorkerPool<HandlerType>:275      Starting worker 0x7f2971ffa3
c0 "/tmp/.mount_StrawbC3nsn3/usr/bin/strawberry-tagreader" "/tmp/strawberry_2106
779903"
13:40:46.621 DEBUG WorkerPool<HandlerType>:275      Starting worker 0x7f2971ffa3
c0 "/tmp/.mount_StrawbC3nsn3/usr/bin/strawberry-tagreader" "/tmp/strawberry_8926
28161"
13:40:46.622 DEBUG WorkerPool<HandlerType>:275      Starting worker 0x7f2971ffa3
c0 "/tmp/.mount_StrawbC3nsn3/usr/bin/strawberry-tagreader" "/tmp/strawberry_1249
909663"
13:40:46.623 DEBUG WorkerPool<HandlerType>:275      Starting worker 0x7f2971ffa3
c0 "/tmp/.mount_StrawbC3nsn3/usr/bin/strawberry-tagreader" "/tmp/strawberry_5688
12662"
13:40:46.624 DEBUG WorkerPool<HandlerType>:275      Starting worker 0x7f2971ffa3
c0 "/tmp/.mount_StrawbC3nsn3/usr/bin/strawberry-tagreader" "/tmp/strawberry_9033
56775"
13:40:46.657 DEBUG logging:65                       posix_spawn avoided (fd clos
e requested)
13:40:46.681 INFO  main:54                          TagReader worker connecting
to "/tmp/strawberry_892628161"
13:40:46.681 INFO  main:54                          TagReader worker connecting
to "/tmp/strawberry_1145909467"
13:40:46.683 DEBUG WorkerPool<HandlerType>:293      Worker 0x7f2960007ec0 connec
ted to "/tmp/strawberry_1145909467"
13:40:46.683 DEBUG WorkerPool<HandlerType>:293      Worker 0x7f296000c230 connec
ted to "/tmp/strawberry_892628161"
13:40:46.699 INFO  main:54                          TagReader worker connecting
to "/tmp/strawberry_568812662"
13:40:46.699 DEBUG WorkerPool<HandlerType>:293      Worker 0x7f296000ed30 connec
ted to "/tmp/strawberry_568812662"
13:40:46.702 INFO  main:54                          TagReader worker connecting
to "/tmp/strawberry_1249909663"
13:40:46.702 DEBUG WorkerPool<HandlerType>:293      Worker 0x7f296000d730 connec
ted to "/tmp/strawberry_1249909663"
13:40:46.710 INFO  main:54                          TagReader worker connecting
to "/tmp/strawberry_484176500"
13:40:46.710 DEBUG WorkerPool<HandlerType>:293      Worker 0x7f2960006490 connec
ted to "/tmp/strawberry_484176500"
13:40:46.717 INFO  main:54                          TagReader worker connecting
to "/tmp/strawberry_903356775"
13:40:46.718 DEBUG WorkerPool<HandlerType>:293      Worker 0x7f29600105d0 connec
ted to "/tmp/strawberry_903356775"
13:40:46.725 INFO  main:54                          TagReader worker connecting
to "/tmp/strawberry_512878241"
13:40:46.725 DEBUG WorkerPool<HandlerType>:293      Worker 0x7f2960006600 connec
ted to "/tmp/strawberry_512878241"
13:40:46.725 INFO  main:54                          TagReader worker connecting
to "/tmp/strawberry_2106779903"
13:40:46.726 DEBUG WorkerPool<HandlerType>:293      Worker 0x7f296000ad30 connec
ted to "/tmp/strawberry_2106779903"
13:40:46.868 INFO  Player:788                       Registered URL handler for "
tidal"
13:40:46.868 DEBUG InternetServices:43              Added internet service "Tida
l"
13:40:46.883 DEBUG MainWindow:227                   Starting
13:40:46.915 DEBUG CoverProviders:42                Registered cover provider "l
ast.fm"
13:40:46.915 DEBUG CoverProviders:42                Registered cover provider "D
iscogs"
13:40:46.915 DEBUG CoverProviders:42                Registered cover provider "M
usicBrainz"
13:40:46.915 DEBUG CoverProviders:42                Registered cover provider "D
eezer"
13:40:46.916 DEBUG CoverProviders:42                Registered cover provider "T
idal"
13:40:46.925 DEBUG LyricsProviders:43               Registered lyrics provider "
AudD"
13:40:46.926 DEBUG LyricsProviders:43               Registered lyrics provider "
ChartLyrics"
13:40:46.938 DEBUG MainWindow:279                   Initialising player
13:40:46.938 DEBUG Player:203                       Creating equalizer
13:40:46.947 DEBUG MainWindow:289                   Creating models
13:40:46.948 DEBUG MainWindow:296                   Creating models finished
13:40:46.951 WARN  DeviceKitLister:60               Error enumerating DeviceKit-
disks devices: "org.freedesktop.DBus.Error.ServiceUnknown" "The name is not acti
vatable"
13:40:46.953 DEBUG CddaLister:115                   No CD devices found
13:40:46.958 DEBUG MainWindow:314                   Creating UI
13:40:46.959 DEBUG logging:65                       _g_io_module_get_default: Fo
und default implementation gvfs (GDaemonVfs) for ‘gio-vfs’
13:40:46.980 DEBUG ScrobblerServices:45             Registered scrobbler service
 "Last.fm"
13:40:46.980 DEBUG ScrobblerServices:45             Registered scrobbler service
 "Libre.fm"
13:40:46.981 DEBUG ScrobblerServices:45             Registered scrobbler service
 "ListenBrainz"
13:40:46.997 DEBUG MainWindow:682                   Creating playing widget
13:40:47.037 DEBUG MainWindow:723                   Loading settings
13:40:47.192 DEBUG MainWindow:801                   Started
13:40:53.221 DEBUG GlobalShortcutsSettingsPage:115  Gnome (GSD) D-Bus backend is
 unavailable.
13:40:53.221 DEBUG GlobalShortcutsSettingsPage:120  X11 backend is available.
13:41:06.522 ERROR TidalService:1078                Tidal: "SSL handshake failed
 (6)"
13:41:11.974 DEBUG GlobalShortcutBackendSystem:66   Unregistering
13:41:12.003 DEBUG WorkerPool<HandlerType>:175      Closing worker socket
13:41:12.011 DEBUG WorkerPool<HandlerType>:175      Closing worker socket
13:41:12.016 DEBUG WorkerPool<HandlerType>:175      Closing worker socket
13:41:12.019 DEBUG WorkerPool<HandlerType>:175      Closing worker socket
13:41:12.026 DEBUG WorkerPool<HandlerType>:175      Closing worker socket
13:41:12.032 DEBUG WorkerPool<HandlerType>:175      Closing worker socket
13:41:12.034 DEBUG WorkerPool<HandlerType>:175      Closing worker socket
13:41:12.037 DEBUG WorkerPool<HandlerType>:175      Closing worker socket
