### ISSUE TITLE
[Features request] Add Mood, Genre, Rating filtering (See Beatport Desktop)

### ISSUE THREAD

**Issue by Extarys** [jonaski/strawberry#197]
I'm a little shy to propose this as I'm just starting to use this software. Great work by the way!

I know some professional library manager have a lot of filtering options.

Take a look at [Beatport for Desktop](https://www.beatport.com/desktop) (it's beautiful :D). You can filter and tag by mood, genre, rating, energy, vocals, etc. (See attached image)
This could be quite a task and quite a to-do list though.

I played a little with Strawberry, but what I would love to see on a Linux music player is also a powerful organizer with the ability to have a list of all the moods and genres and check which one I want.

I know owner and contributors might not have the time but I think it would be worth investigating and keep this in mind.

**You can stop reading here.** My boyfriend love mixing music and we have a lot of Drum and Bass music unmixed, etc and it's quite a pain to find what he really needs. And it's also hard for me to browse the collection with all this different type of music. It would be so great for an open-source project to have such great features. I have more than 20,000 tracks. Some are good music, some are just vocals to mix, some I keep to have the complete album even though I don't like it... It's a library I started building when I was 12 and I never deleted a track, but it's a mess to find a good software on Linux that would allow music addicts to have one central place to manage and listen to their tunes.

![image](https://user-images.githubusercontent.com/11581433/60390917-307e0e80-9ab0-11e9-9451-8e73d83a5e84.png)

**Comment by jonaski** [comment]
Thanks for the suggestion, it's not something I plan to add unfortunately. However we might add smart playlists and dynamic playlists that might be useful for this.
