### ISSUE TITLE
[Question] Currently playing

### ISSUE THREAD

**Issue by CatPlanet** [jonaski/strawberry#200]
Is there way to grab currently playing file?
I want to migrate from mpd+ncmpcpp setup and all I need for my scripts is to grab file that is currently playing, preferably with %track_time%/%total_track_time%

**Comment by jonaski** [comment]
qdbus org.mpris.MediaPlayer2.strawberry /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Metadata

**Comment by jonaski** [comment]
I've added some info about MPRIS to the Wiki too:
https://github.com/jonaski/strawberry/wiki/Using-MPRIS2-to-get-information-and-control-playback
