### ISSUE TITLE
aiff files are not displayed

### ISSUE THREAD

**Issue by MilanLachance** [jonaski/strawberry#207]
I have a problem with strawberry v0.5.5 on Arch Linux. It seems like aiff files are not included in supported file types.

When I am browsing files in strawberry's file explorer, my aiff music files are not displayed.

Also, when I manually open a file *(Music -> Open file...)*, .aiff files are not included in the *Music* file type and I have to select *All Files (\*)* in order to see them. Once added with this method, they appear in my playlist and I can play them.

I have GStreamer's bad plugins installed.

Seems like there was a similar issue in clementine [issue 4921](https://github.com/clementine-player/Clementine/issues/4921), but it is still open.

Any help would be appreciated :)

**Comment by jonaski** [comment]
It works here. It was missing .aif .aiff in the file filter (fixed now https://github.com/jonaski/strawberry/commit/61af1d1c720fa624c8cc4c94b656da16cbe3f2a9), but it should recognize it in the collection or by dragging it to the playlist anyway.
Does this file work for you? https://github.com/jonaski/strawberry/blob/master/tests/data/audio/strawberry.aif

Arch is not following my advice to use the static tablib we provide and uses their own package of taglib which is version (1.11.1) so the problem may be there.

https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/strawberry#n26

**Comment by MilanLachance** [comment]
I have downloaded [this](https://aur.archlinux.org/packages/strawberry-full-git/) package from the AUR and it is working properly now. I'm not sure what fixed the issue since it has a lot more dependencies than the official package and has been updated more recently too.

The test file and all other aif/aiff files appear as expected.

Thanks for the quick reply!
