### ISSUE TITLE
Gstreamer plugin(s) missing

### ISSUE THREAD

**Issue by rtgilbert** [jonaski/strawberry#211]
Moving from Clementine 1.3.1 (2016) as it's not keeping up with OS changes.  Thank you!

Installed today's (July 11) dev build (dmg) for Mac OS (I'm topped out at 10.13.6 on a 2011 MBP 2.2Ghz I7 16GB):

Strawberry 0.5.5-156-g3a86a93, which installed Gstreamer

Trying to playing files (AIFF, mp3, m4a, mp4, wav) failed with error msg – Your GStreamer installation is missing a plug-in.

Installed the latest package (April 20) of Gstreamer with the intent to copy the missing plugin(s), but Emacs keeps crashing when reading 
gst-registry-0.5.5-156-g3a86a93-bin.  I don't want to just copy all of it over as there are far fewer shared libraries[dylib] in the Strawberry install.  And as it seems that some were compiled as loadable bundles[so], so... they are probably called as such.

On a whim I tried Strawberry again.  Initially same result, failing on all files.  However, the last (wav) file I double clicked instead of hitting the play button and it played!?!  Went back through the others the same way and all played but the AIFF, which does play in Clementin (So maybe I'll compare the plugins directly?).

Anyway, thought you ought to know.  When I figure out what's missing I'll post it.

**Comment by jonaski** [comment]
Sounds like it took time to register all the plugins.
Added aiff to the bundled plugins https://github.com/jonaski/strawberry/commit/adbf8495c6350d040505334491d1f5348163f9ca
The list of plugins that are bundled is here:
https://github.com/jonaski/strawberry/blob/master/dist/macos/macdeploy.py#L57

**Comment by rtgilbert** [comment]
Thanks. I've been busy and have not worked on it yet.

**Comment by rtgilbert** [comment]
So, I was lazy and just went to the most recent build, deleting (i.e. - scrubbing) the previous package.  Installed ...171 which failed to boot.  Crash report indicated QtCore.framework was missing. However, it's there.  So, being lazy I went to the previous build ...170 and ditto.  Then ...169 and ditto.  Although, libgstaiff.so is present in all three.  I'll open a new issue and keep working back through the builds, although I expected that you test each before posting so it's likely something on my end.
