### ISSUE TITLE
Ctrl+D Removes Track From Playlist

### ISSUE THREAD

**Issue by krnhotwings** [jonaski/strawberry#213]
Came across a bug where using the `ctrl+d` shortcut to queue the next song will instead remove the selected song from the playlist. Right-clicking on a track and then closing the right-click menu will temporarily fix the issue until next launch.

Running strawberry from a terminal will print the following when a track is inadvertently removed:

```
DEBUG PlaylistBackend:278              Saving playlist 5
```

OS: Ubuntu/pop os 18.10
Version: 0.5.5-7-g2b9f153
Installed and running from snap

### Steps to Reproduce
1. Launch Strawberry
2. Select a track, and press `ctrl+d` (should be removed)
3. Press `ctrl+z` to undo the removal
4. Right-click on any track to open the menu
5. Close the menu.
6. Press `ctrl+d` (track should now be queued)
7. Quit Strawberry and relaunch to reproduce behavior

**Comment by jonaski** [comment]
Works here.
Do you use keyboard shortcuts?

**Comment by krnhotwings** [comment]
I do use global shortcuts, but not for `ctrl+d`. I don't have reason to believe that it's due to shortcuts because all other applications appear to behave normally and implement their `ctrl+d` shortcuts correctly (e.g. Firefox bookmarking, etc.)

In fact, I have Clementine 1.3.1 (installed via `apt`) running alongside Strawberry 0.5.5-7-g2b9f153 (installed via `snap`) on my personal computer (PopOS 19.04) and Clementine is queuing the track normally, whereas Strawberry is still removing the track.

**Comment by jonaski** [comment]
I can reproduce it on KDE

**Comment by jonaski** [comment]
Removing the line here: https://github.com/jonaski/strawberry/blob/master/src/core/mainwindow.cpp#L596 and the shortcut is still deleting from playlist on KDE, which means it's probably coming from MPRIS.
On XFCE it's gone.

**Comment by jonaski** [comment]
I've found the problem now

**Comment by jonaski** [comment]
Fixed https://github.com/jonaski/strawberry/commit/0a71347e9a8d5e4884fc2dd48429bab59d318d77
