### ISSUE TITLE
QtCore.framework/Versions/5/QtCore, Dyld error "not loaded" (MacOS)

### ISSUE THREAD

**Issue by rtgilbert** [jonaski/strawberry#218]
[20190718 Crash Report Macos Strawberry-0.5.5.170.g045b0cd.dmg.pdf](https://github.com/jonaski/strawberry/files/3408197/20190718.Crash.Report.Macos.Strawberry-0.5.5.170.g045b0cd.dmg.pdf)

I started with Macos Strawberry-0.5.5.156 which installed without issue.  Following resolution of a different issue, [#211](https://github.com/jonaski/strawberry/issues/211), I was lazy so I went to the most recent build (...171).  Installed but would not boot giving the titled error.  The files were present in the path indicated.  Still being lazy I went back through two more builds ...170 & 169 with the same results.  Crash reports are attached as a single file.

I expect that each build is tested before posting so it's likely something on my end.  I'll look at it more tomorrow.  On a lark I reinstalled 156, opens fine, but still coming up with the plugin error after four restarts (for everything but mp4 despite the files being present sans aiff).  Maybe it's time to convert everything to flac?!?

**Comment by jonaski** [comment]
The 2019-07-17 to 2019-07-18 builds are broken. Try the latest today.

**Comment by rtgilbert** [comment]
I appreciate the effort.  

Wiped all previous files and installed Strawberry 0.5.5-177-gea6cce7 without issue.  Ran the exec from Terminal to get the runtime log (see attached).  Did four test runs on six file types (mp4, m4a, omg, ac3, flac, mp3, aif(aiff), & wav), cleaning the support folder between each.  First run seemed it liked only the mp4, m4a formats.  Looking at the log, it hung on the mp3.  Every successive selection (I was changing to other items/formats) it went back to the mp3?  Second run, hung when opening preferences to set content folder (force quit).  Third, played everything but the mp3 despite cueing it a couple times.  Fourth, similar to the third.   

This warning issued each run:
            Failed to load plugin... libgstlibav.so.   Reason: Incompatible library version: libgstlibav.so   
            requires version 8.0.0 or later, but liblzma.5.dylib provides version 6.0.0

Looked at the plugins, didn't find libgstlibav.so, lamemp3enc, or anything else that looked like an mp3 codec.

I have very few mp3s and can convert, so this isn't much of an issue for me.  However, it likely is for many others.
 
[Strawberry 0.5.5-177-gea6cce7 Terminal Saved Output.pdf](https://github.com/jonaski/strawberry/files/3412742/Strawberry.0.5.5-177-gea6cce7.Terminal.Saved.Output.pdf)

**Comment by jonaski** [comment]
Unfortunately brew does not provide lame or twolame plugins anymore, maybe a bug on their part, so it uses libav for MP3. Looks like it picks up an incompatible (older) version of liblzma on your system, try see if you can find the correct one with find / -name 'liblzma*.dylib' and make that one first in the LD path (or remove the old one if it's not used by anything).

**Comment by jonaski** [comment]
I see that lame is disabled in brew on their good plugins: https://github.com/Homebrew/homebrew-core/blob/master/Formula/gst-plugins-good.rb#L46
I opened a question on their forum: https://discourse.brew.sh/t/gstreamer-missing-lame/5387

**Comment by rtgilbert** [comment]
Have been busy and not checked in a while.  Your Homebrew post has no responses yet and didn't find anything else to suggest movement on the issue.  I have liblzma.dylib and liblzma5.dylib in a couple other places including Xcode.  I'll try your suggestion in the next few days (I'll need a break from the rebuild of my truck engine!).
