### ISSUE TITLE
Feature Request: Bookmarks within a file / track

### ISSUE THREAD

**Issue by hkockerbeck** [jonaski/strawberry#221]
Would you consider a functionality to bookmark the position in a track, with the possibility to return to the bookmarked position later?

I mostly use audio players to listen to podcasts. Some of those get quite long, sometimes multiples hours. So a feature to bookmark the current position, then listen to something else, and later come back to the bookmarked position would be really nice.

**Comment by jonaski** [comment]
It's not really something I have the time to prioritize, it's a bit of work too as we need to add a column for that in the DB so it get saved for each song.
I'll accept a PR to add it if someone wants to do it, but I don't think many people have the use for it.
