### ISSUE TITLE
Sometimes playback stops when a track ends

### ISSUE THREAD

**Issue by glaubersm** [jonaski/strawberry#222]
Hi
Sometimes strawberry stops playback when a track ends instead of start to play
the next track in the playlist.
This problem does not occur when I play the same file with other players, tested
VLC, qmmp, smplayer and gnome mpv.
I can provide a problematic file if you want.

I use strawberry 0.5.3 on Void linux.

**Comment by jonaski** [comment]
You you use gstreamer it might be  the same as https://github.com/jonaski/strawberry/issues/106 - Already fixed.

**Comment by glaubersm** [comment]
yes, I use gstreamer backend.

**Comment by jonaski** [comment]
I will probably make a new release in a the next few fix.
But to fix it till then ask void to update to 0.5.5 and apply the following 2 fixes:

Fixes track change hang:
https://github.com/jonaski/strawberry/commit/aec9df1882dab94944be86d80ddffcd1cf47bf6a.patch

Fixes a crash in tagreader:
https://github.com/jonaski/strawberry/commit/83d3725240043cf3b9a60374dc0ea672dc3dc902.patch
