### ISSUE TITLE
Feature Request: Fade out on pause and stop

### ISSUE THREAD

**Issue by GrandMasterX3** [jonaski/strawberry#223]
-Fade out on pause and stop.

Besides this simple request I want to thank you for your work. 
PD: I don't think it's a bug but my SBerry takes many seconds to populate and index the "Files" list on the left column. It also stops responding sometimes.

**Comment by m4x3t** [comment]
Check at the bottom of the "Backend" settings, fading options should be there.

**Comment by GrandMasterX3** [comment]
oh. I feel bad I didn't see it before. Thanks!
