### ISSUE TITLE
QSqlDatabase: QSQLITE driver not loaded

### ISSUE THREAD

**Issue by neongreen** [jonaski/strawberry#224]
I'm using build `Strawberry 0.5.5-180-g5533212` on macOS. It fails with the following:

```
13:52:00.460 ERROR Database:571                     db error:  QSqlError("", "Driver not loaded", "Driver not loaded")
13:52:00.461 ERROR Database:572                     faulty query:  ""
13:52:00.461 ERROR Database:573                     bound values:  QMap()
__logging_message__13:52:00.461 ERROR unknown       Couldn't create playlist
Abort trap: 6
```

Full log: https://gist.github.com/neongreen/41bad8d59898c3e24262f529d1611ac2.

**Comment by jonaski** [comment]
There should be a file called libqsqlite.dylib in strawberry.app/Contents/PlugIns/sqldrivers/libqsqlite.dylib
When you start look for the "Looking for resources in" line that shows there it tries to find it.

**Comment by jonaski** [comment]
You need to run the binary itself from strawberry.app/Contents/MacOS thats how it find the plugins in ../PlugIns under sqldrivers/libqsqlite.dylib

**Comment by neongreen** [comment]
The `PlugIns` folder does not contain anything SQL-related.

```
$ ls /Applications/strawberry.app/Contents/PlugIns/
gio-modules		gst-plugin-scanner	gstreamer		strawberry-tagreader
```

I tried running the binary from `strawberry.app/Contents/MacOS` and got the same result.

**Comment by jonaski** [comment]
I don't have a mac, but extracting the contents on linux here using 7z, the plugins are here.

```
jonas@jonas:~/Downloads/strawberry-macos/strawberry-0.5.5.180.g5533212/strawberry.app/Contents/PlugIns> ls
bearer       gst-plugin-scanner  iconengines   platforminputcontexts  printsupport  strawberry-tagreader  virtualkeyboard
gio-modules  gstreamer           imageformats  platforms              sqldrivers    styles
jonas@jonas:~/Downloads/strawberry-macos/strawberry-0.5.5.180.g5533212/strawberry.app/Contents/PlugIns> ls sqldrivers/
libqsqlite.dylib

```

**Comment by neongreen** [comment]
Ok, mystery solved: https://builds.strawbs.net/macos-test/ has working builds, https://builds.strawbs.net/macos/ has broken builds. Thanks!
