### ISSUE TITLE
crash while playing 24 bit flac

### ISSUE THREAD

**Issue by Zabanya** [jonaski/strawberry#226]
version 0.5.5.146.gaa8679d on win 10 64 bit. 
strawberry just crashes whenever I play 24-bit FLAC, tried multiple sample rate 44k, 48k and 96k. it would play 16 bit normally. I tried changing the audio default format to 16 bit or 24 bit (studio format), turn off Microsoft FLAC decoder using codec tweak but it does not help. although groove could play it easily. anything I could miss?.

**Comment by jonaski** [comment]
Did you check the application log in event viewer, it's usually logged there with the faulting module and an exception code.
I've tested with Tom Petty - Full Moon Fever 96/24 and Crosby, Stills & Nash Daylight Again 192/24, from hdtracks. No crashes.

**Comment by Zabanya** [comment]
> Faulting application name: strawberry.exe, version: 0.5.5.0, time stamp: 0x00000000
Faulting module name: libFLAC-8.dll, version: 0.0.0.0, time stamp: 0x5d1eb115
Exception code: 0xc0000005
Fault offset: 0x0002ec3c
Faulting process id: 0xb88
Faulting application start time: 0x01d541799877690e
Faulting application path: C:\Program Files (x86)\Strawberry Music Player\strawberry.exe
Faulting module path: C:\Program Files (x86)\Strawberry Music Player\libFLAC-8.dll
Report Id: 0b979848-732e-4e00-bd16-a51a3af5c5b5
Faulting package full name: 
Faulting package-relative application ID: 

i dont see anything helpful there

**Comment by jonaski** [comment]
Thats very helpful, it means libFLAC-8.dll is the component causing the crash.
I've seen cases where libFLAC-8.dll compiled in a ducker crashes, but the one compiled on a physical machine works fine.
Try replace libFLAC-8.dll in C:\Program Files (x86)\Strawberry Music Player with this one

[libFLAC-8.dll.zip](https://github.com/jonaski/strawberry/files/3423360/libFLAC-8.dll.zip)

**Comment by jonaski** [comment]
The exception code: 0xc0000005 is usually windows or anti-virus blocking the file.
If you are using DEP, try turning it off, or if you are using anti-virus try making an exception.
But I bet Windows will accept the file I attached, because it's not compiled in a docker.

**Comment by Zabanya** [comment]
thanks, it actually works.
