### ISSUE TITLE
No longer able to change audio engines after update

### ISSUE THREAD

**Issue by yekteniya** [jonaski/strawberry#227]
I updated from version 0.5.5-146-gaa8679 to version 0.5.5-188-gbd78e8c and I am no longer able to change audio engines, stuck with Gstreamer. Made sure that nothing was playing while I was in the settings. Changed back to 146 and I am again able to choose between GSreamer, Xine and VLC. 

Using Debian Buster.

**Comment by jonaski** [comment]
I decided to compile them with only gstreamer support because it caused unnecessary dependencies for users who use forks of debian and ubuntu which don't have xine or vlc packages.
So if you want xine or vlc you need to compile yourself from source.
