### ISSUE TITLE
search no longer working with Version 0.5.5-193-g41484f8

### ISSUE THREAD

**Issue by lemonzest79** [jonaski/strawberry#228]
I'm using this build on Fedora Linux 30 and searching no longer works, I've Tried things like Artist:Name, Album:Name and neither works, before just typing in the collection search box was enough to find what I wanted.

**Comment by jonaski** [comment]
Thanks for pointing it out. The regression is in commit https://github.com/jonaski/strawberry/commit/b5eb13449b8b6b6f3ced459487f26e150561363f
Fixing it now.

**Comment by jonaski** [comment]
Try https://github.com/jonaski/strawberry/commit/81caec99b769b3e91c3ed7e0b3833f9ea45494c2 when it's finished building.

**Comment by lemonzest79** [comment]
Thanks, seems to be working again :)
