### ISSUE TITLE
Visual  small changes

### ISSUE THREAD

**Issue by pepaulo** [jonaski/strawberry#231]
The suggestion I make for Strawberry is in the visual part. I believe that small changes can give you a more modern look without neglecting your entire legacy. I suggest an icon theme that is flat. On the right side I suggest replacing this gradient image which above all gives poor visibility to the icons that are on it. Make Strawberry compatible to accept KDE 5 compatible icons
![screenshot-camo githubusercontent com-2019 08 01-09_43_17](https://user-images.githubusercontent.com/7110757/62294510-77f61280-b441-11e9-8303-f23ab94df1e8.png)

**Comment by jonaski** [comment]
I don't really want to change the icons to flat ones.
But I partially agree with you about the tab bar. But it's not using an image, it picks 2 colors from the system theme and creates a gradient background from that. The code is here: https://github.com/jonaski/strawberry/blob/master/src/widgets/fancytabwidget.cpp#L466
The colors could be made configurable in the appearance settings instead.

**Comment by NucleaPeon** [comment]
I'm no fan of flat themes or icons and there is a "Use system icons" checkbox. Perhaps that could be enabled by default to make the application blend in more initially?

**Comment by jonaski** [comment]
It is possible to use custom icons too, see: https://github.com/jonaski/strawberry/wiki/Custom-icons-on-linux

**Comment by pepaulo** [comment]
Thank you. Really the custom icon theme is very easy to set. And the sidebar it is possible change the color or image background?

**Comment by jonaski** [comment]
I can add a setting for the colors in the sidebar.

**Comment by pepaulo** [comment]
Excellent. Thank you
