### ISSUE TITLE
Collection watcher is not updating album directory after rename when (parent) artist directory is renamed

### ISSUE THREAD

**Issue by jonaski** [jonaski/strawberry#233]
Collection watcher is not updating album directory after rename when (parent) artist directory is renamed first. It's solved with a simple restart.
Even though the new artist directory is updated to the songs, the new album directory is not.
This bug has been there forever, and is also in Clementine, but should be fixed.

**Comment by gianlucapettinello** [comment]
I confirm. Also when I trigger tag fetcher the window shows several possibilities but then only one is remaining and normally it is not the good one.
BTW Thanks a lot for creating new release, you are great :)

**Comment by jonaski** [comment]
You are right, it's so obviously broken too, because it finishes each song when the first tag for it is received instead of waiting for all results, fixed now: https://github.com/jonaski/strawberry/commit/be1e14df81b2c231f92292cd391ebb0700389ca0

**Comment by gianlucapettinello** [comment]
Your are great. I would love to be as good in programming as you are

**Comment by gianlucapettinello** [comment]
I just compiled git version in Archlinux from AUR and now the tag fetcher works OK.
Thanks

**Comment by jonaski** [comment]
Thanks for the kind words.
I've found this problem too now, it was watching the old parent directories that were renamed, and that caused it to inform of changes inside that directory while still using the old directory name.
I have to make a new release today or tomorrow anyway now because there was also a crash in internet services.
