### ISSUE TITLE
Wrong album grouping if album has more than one disc

### ISSUE THREAD

**Issue by alscaldas** [jonaski/strawberry#235]
Hi. Since this is the very first time I open a ticket for an issue hope I'm doing it the right way. I've just found Strawberry, have been using it for the last two days and I'm loving it, but there's something that really annoys  me in the display options. 

The display of albums which have more than one disc (which is quite common with some deluxe soundtracks) is not showing correctly.

I sort of minimized the trouble creating an advanced display option as follows:

First level: Album Artist -> Second level: Year - Album - Third level: Disc

But it doesn't completely solve the issue, as detailed in the attached image.

![Screenshot_20190804_114556](https://user-images.githubusercontent.com/29403156/62425115-b4c64180-b6ad-11e9-8da1-099f2a11c337.png)

As you can see, if the album has only one disc, it unnecessarily display a number 1 (which I noticed that converts to "-1" if the "Disc Number" tag is not set) when it would be desirable to show the list of songs directly. If the album has more than one disc it shows correctly (although in my opinion it would be more elegant if it showed something like "Disc 1", "Disc 2", "Disc n" instead of just "1, 2, 3".

I hope I made myself clear (English is not my native language).

And here's a little more information, if needed:

OS: Arch Linux
Strawbery version: 0.6.2 (installed using Pacman)

Thank you for your attention.

**Comment by jonaski** [comment]
I'm aware of this. But when ripping CD's, musicbrainz and cddb suggests tags it usually adds CD or Disc at the end of the album title for albums that have multiple discs. So most users actually have their albums with the disc/cd in the album title tag, that's why it's not an issue for most people. This is how I have my entire collection and workaround it that way. I have appended - (Disc #) to the end of all album titles that have multiple discs.
I've made strawberry strip that off automatically when fetching albums covers, lyrics and when sending scrobbles so the results there won't be affected by it. The regex pattern it uses for that is here: https://github.com/jonaski/strawberry/blob/master/src/core/song.cpp#L152

Here is an example how it looks.
![image](https://user-images.githubusercontent.com/10343810/62425478-cb36c200-b6da-11e9-9b37-097c3a9a5d3b.png)

I realize that some people way not want to have the disc in the album tag.
But I'm not sure (code-wise) how we could change the behavior of the groupings to ignore the the disc grouping for albums with only 1 disc.
I can change it to show Disc # instead, but I'm afraid it would still show Disc 1 for albums with only 1 disc.

**Comment by jonaski** [comment]
Of course we can just add a group that is called Album - Disc.

**Comment by alscaldas** [comment]
> I'm aware of this. But when ripping CD's, musicbrainz and cddb suggests tags it usually adds CD or Disc at the end of the album title for albums that have multiple discs. So most users actually have their albums with the disc/cd in the album title tag, that's why it's not an issue for most people. This is how I have my entire collection and workaround it that way. I have appended - (Disc #) to the end of all album titles that have multiple discs.
> I've made strawberry strip that off automatically when fetching albums covers, lyrics and when sending scrobbles so the results there won't be affected by it. The regex pattern it uses for that is here: https://github.com/jonaski/strawberry/blob/master/src/core/song.cpp#L152
> 
> Here is an example how it looks.
> ![image](https://user-images.githubusercontent.com/10343810/62425478-cb36c200-b6da-11e9-9b37-097c3a9a5d3b.png)
> 
> I realize that some people way not want to have the disc in the album tag.

So I probably only noticed this issue because I don't use neither Musicbrainz nor CDDB to tag my files, and do it manually being careful to use tags like "Compilation", "Disc Number" and "Total Disc", etc, instead of changing the songs titles.

But don't worry... it's more of a visual thing anyway, and not that important to the player behavior. I imagine that if there was such a group as that "Album - Disc" as you proposed it would somewhat solve it.

Thank you for your quick response.

**Comment by jonaski** [comment]
I've added album - disc grouping now.
It looks at the album title and if it already contains disc/cd it won't be appended to the grouping.
https://github.com/jonaski/strawberry/commit/140935bd8c497f06cbf6a8e710051c5f167895c4

**Comment by alscaldas** [comment]
I've just cloned and seen the changes your made. It's working perfectly now.

Thank you, I really appreciate your kindness and promptness!

**Comment by jonaski** [comment]
Great!

**Comment by KazimirPodolski** [comment]
Grouping doesn't work when disk is in the .cue and album name is correct (without "(Disc 1)" or smt). I stumpled upon such .cues:
```cue
REM GENRE "Black Metal"
REM DATE 2012
REM DISCID 2C0D1804
REM COMMENT "ExactAudioCopy v1.0b2"
PERFORMER "Elysian Blaze"
TITLE "Blood Geometry"
FILE "Elysian Blaze - Blood Geometry - CD1.flac" WAVE
  TRACK 01 AUDIO
    TITLE "A Choir for Venus "
    PERFORMER "Elysian Blaze"
    ISRC 000000000000
    INDEX 01 00:00:00
  TRACK 02 AUDIO
    TITLE "The Temple Is Falling "
    PERFORMER "Elysian Blaze"
    ISRC 000000000000
    INDEX 01 04:30:51
  TRACK 03 AUDIO
    TITLE "Sigils That Beckon Death "
    PERFORMER "Elysian Blaze"
    ISRC 000000000000
    INDEX 01 22:55:52
  TRACK 04 AUDIO
    TITLE "Blood Geometry"
    PERFORMER "Elysian Blaze"
    ISRC 000000000000
    INDEX 01 46:50:53
```

```cue
REM GENRE "Black Metal"
REM DATE 2012
REM DISCID 36114B04
REM COMMENT "ExactAudioCopy v1.0b2"
PERFORMER "Elysian Blaze"
TITLE "Blood Geometry"
FILE "Elysian Blaze - Blood Geometry - CD2.flac" WAVE
  TRACK 01 AUDIO
    TITLE "A Blade for Twilight "
    PERFORMER "Elysian Blaze"
    ISRC 000000000000
    INDEX 01 00:00:00
  TRACK 02 AUDIO
    TITLE "Pyramid of the Cold Son"
    PERFORMER "Elysian Blaze"
    ISRC 000000000000
    INDEX 01 03:45:51
  TRACK 03 AUDIO
    TITLE "Blood of Ancients, Blood of Hatred "
    PERFORMER "Elysian Blaze"
    ISRC 000000000000
    INDEX 01 25:57:61
  TRACK 04 AUDIO
    TITLE "Void Alchemy"
    PERFORMER "Elysian Blaze"
    ISRC 000000000000
    INDEX 01 62:34:14
```
Here DISCID's are different, but Strawberry doens't seem to notice it and still shows discs merged together:
![image](https://user-images.githubusercontent.com/6647438/68088005-86632880-fe8d-11e9-8ee4-97d5ca1d7005.png)
Grouping is Artist/Year - Album - Disc.
