### ISSUE TITLE
Blurry Strawberry icon in macOS

### ISSUE THREAD

**Issue by llucps** [jonaski/strawberry#236]
When Strawberry is running the icon looks blurry on the Dock and tab/selector in macOS..

When the program is not running it looks crisp and sharp.

Running
![Screenshot 2019-08-06 at 12 54 39](https://user-images.githubusercontent.com/25823659/62534522-af9df980-b849-11e9-9f11-d763810d7c99.jpg)

Not running
![Screenshot 2019-08-06 at 12 54 57](https://user-images.githubusercontent.com/25823659/62534535-b3ca1700-b849-11e9-9b72-bdc388d55a41.jpg)

**Comment by jonaski** [comment]
Looks like it's using the 64x64 icon and scaling it up to 128. I changed it to the 512x512 one instead.https://github.com/jonaski/strawberry/commit/20766c1feb96acb3007be7c7e735f8183bbb8b38

**Comment by jonaski** [comment]
Can you test the newest build from https://builds.strawbs.net/macos/ (strawberry-0.6.3.3.g4a934c9.dmg )and see if it fixed it?

**Comment by llucps** [comment]
I can confirm that is fixed.. check it out:

![Screenshot 2019-08-06 at 22 21 02](https://user-images.githubusercontent.com/25823659/62574408-bdc73680-b898-11e9-9903-a404b4655b00.jpg)

Thanks!

**Comment by jonaski** [comment]
@llucps does the latest build have native macOS look now?

**Comment by llucps** [comment]
Hi @jonaski,

Yes it's better than it was, with still a few visual glitches such as the playlist tabs (the text is truncated no matter how long it is) or the text of the header in the playlist view (text is too big).. These two things I'll try to fix them myself if I can :)

This is how it looks like now:
![Screenshot 2019-08-08 at 08 46 34](https://user-images.githubusercontent.com/25823659/62681062-0d048880-b9b9-11e9-9279-453585632962.jpg)
