### ISSUE TITLE
Accessibility Support: Zoom

### ISSUE THREAD

**Issue by gregulatore** [jonaski/strawberry#238]
I use Debian Stretch and Buster as virtual machines on my Chromebook and love running Linux apps. However, Strawbs would definitely benefit (in this user environment) from being able to scale/zoom the UI just like in VSCode. See: https://code.visualstudio.com/docs/editor/accessibility
VSCode works beautifully and adapts to the vast array of scaling options present on Chromebooks. Strawbs on the other hand presents a gigantic UI and can't be scaled. Would adding zoom/scale support controllable via Control+ / Control- shortcuts (as in VSCode) be easy or hard?

**Comment by jonaski** [comment]
It's not easy with Qt 5 widgets
