### ISSUE TITLE
Strawberry is not using default Plasma theme

### ISSUE THREAD

**Issue by tanghus** [jonaski/strawberry#242]
**Describe the bug**
Under KDE Plasma 5.X Strawberry isn't using the default theme. All other apps, including GTK and pure Qt, uses the theme.

**To Reproduce**
* Start Package manager Discover. 
* Find and install Strawberry
* Run the application

**Expected behavior**
The application should use the default theme

**Screenshots:**

![strawberry-missing-theme](https://user-images.githubusercontent.com/533222/63207555-7d518f00-c0c8-11e9-8a7c-fd63fccb366a.png)

**System Information:**
 - Operating system: Kubuntu 19.04
 - Strawberry Version:  (v.0.6.3-git)

**Additional context**
Is this maybe because it's a Snap package?

**Comment by jonaski** [comment]
I have tested this previously and it worked so I think it is related to running as a snap.
Try the 0.6.3 from https://github.com/jonaski/strawberry/releases and see if it works.

**Comment by tanghus** [comment]
Will do. Thanks

**Comment by tanghus** [comment]
What's the difference between all the different `strawberry-0.6.3-1.XXX.x86_64.rpm`?

**Comment by jonaski** [comment]
Use strawberry_0.6.3_disco_amd64.deb for Ubuntu 19.04 (disco).

fc = fedora core
lp = opensuse leap
mga = mageia
(it's the official rpm suffixes of those distros).

**Comment by tanghus** [comment]
It's much better for the eyes now, thanks :+1:
