### ISSUE TITLE
not able to connect airsonic server via https

### ISSUE THREAD

**Issue by flaun** [jonaski/strawberry#243]
Hello,
tried to connect my airsonic server to strawberry. Unfortunately I got this error: Received HTTP code 302.

Is there a workaround to fix this?
thanks for your help
![Bildschirmfoto vom 2019-08-19 15-37-54](https://user-images.githubusercontent.com/28860284/63270013-8e042f80-c297-11e9-970d-ce95902dfd7c.png)

**Comment by jonaski** [comment]
Try to open the url in a broser with /rest/ping.view at the end

**Comment by jonaski** [comment]
I think maybe your url is missing /airsonic in path?

**Comment by flaun** [comment]
Thanks for your quick answer.
With Clementine everything works just fine with the same link.

**Comment by jonaski** [comment]
It's not the same as clementine, it's written from scratch, it's using json instead of xml.
302 means redirect, maybe it's not following the redirect correctly.
I've tested with subsonic http and https, but I've only tested with airsonic using http.
What version of airsonic do you have, and what version of strawberry?

**Comment by jonaski** [comment]
Did you try to just skip the test and use refresh catalogue directly? Do you get the same error there?

**Comment by jonaski** [comment]
I set up airsonic with apache proxypass here, I can't reproduce any problems, but I've added some code to follow redirect in the ping test anyway because I see Clementine is following redirects in ping replies.

**Comment by flaun** [comment]
This happens, when I skip the test, so same problem.

![Bildschirmfoto vom 2019-08-20 17-09-42](https://user-images.githubusercontent.com/28860284/63359666-6aabb400-c36d-11e9-8eaa-ef872de3ec0e.png)

I'm using the newest airsonic (v10.4.0) and strawberry (v0.6.3.) versions.

Are you planning to release a newer version of strawberry the subsonic changes included? Than I would be able to test it.
What else could I do?

**Comment by jonaski** [comment]
When testing your url here I'm getting the same error when I skip the airsonic, because / is redirecting to /airsonic, so I would think that just changing the path to /airsonic will solve it.

**Comment by flaun** [comment]
Perfect!
adding /airsonic to the path solved the problem. Thanks for helping:)

And also thanks a lot for developing and supporting strawberry!
