### ISSUE TITLE
File Browser. Easier way to send files to playlist.

### ISSUE THREAD

**Issue by Esux** [jonaski/strawberry#245]
**Is your feature request related to a problem? Please describe.**

I have my music sorted primarily by folder name so I rely on the files viewer for finding what I want. The problem comes when sending the folder to the playlist. Having to right click and go down to replace playlist. 

**Describe the solution you'd like**
In foobar2000 you can select the folder and press enter/return and it'll send it to the playlist (replacing whats there) and it'll automatically play. This is more or less what I want. It doesn't have to be enter/return it could even be another hotkey. But basically I want a hotkey to send the folder to the playlist and start playing.

**Describe alternatives you've considered**
I can't think of another way to do it unless you included a folder view in some other area. Perhaps a sort by folder option in the collection page?

**Comment by jonaski** [comment]
Strawberry is based on collection library organized with metadata. The file view isn't very good, but is there for files that either don't have tags, or if someone wants to quickly test a file.
I don't really have the time to prioritize to improve the file view, and we want to focus on the collection library features.
But if someone else wants to work on it, PR's are welcomed.
