### ISSUE TITLE
bs2b-ladspa plugin

### ISSUE THREAD

**Issue by sten0** [jonaski/strawberry#249]
**Is your feature request related to a problem? Please describe.**
Listening to hard-panned stereo recordings from the '60s is awful with headphones.  Also, it's fatiguing to hear a lot of modern music where you'll have a really strident treble instrument in one ear or the other.

**Describe the solution you'd like**
Opt-in bs2b-ladspa plugin, which provides crossfeed.  It seems like the interface could be added to the equaliser.

**Describe alternatives you've considered**
I'm currently using the following in /etc/pulse/default.pa:
`load-module module-ladspa-sink sink_name=bs2b plugin=bs2b label=bs2b control=700,4.5`
but imho this is too technical for most users.  I also used to listen to the Beatles with a custom channel matrix remix in mplayer.  Again, much too technical.  The greatest downside to global DSP processing is that it introduces latency which negatively affects AV sync when watching videos, so it makes sense to work around this issue by just putting it in the audio player.
IIRC Audacious has a BSD-licensed implementation that could be used as a basis for Strawberry's.

**Comment by jonaski** [comment]
The easiest would be just to add a preset to the equalizer.
https://github.com/jonaski/strawberry/blob/master/src/equalizer/equalizer.cpp#L130
And it's possible that there is existing functionality in gstreamer to do the same that can be used.
But this isn't something I have time to prioritize.

**Comment by jonaski** [comment]
@sten0
FYI,
I added support for bs2b now commit https://github.com/strawberrymusicplayer/strawberry/commit/5a35099043d76935eb3d4051420a40afc3d7f033. there will be a new option in the backend settings now:
"Improve headphone listening of stereo audio records (bs2b)"
More info here:
https://gstreamer.freedesktop.org/documentation/bs2b/
