### ISSUE TITLE
Translation to Spanish, correction

### ISSUE THREAD

**Issue by Jakeukalane** [jonaski/strawberry#258]
**Improve translation for Spanish**
The menu says "Previous track"

**Expected behavior**
The menu should say "Pista anterior".

**System Information:**
 - Operating system: Manjaro 18.0.4 Illyria
 - Strawberry Version: 0.6.3

Want to know if there is another (better) way to correct this. Thanks

**Comment by jonaski** [comment]
https://github.com/jonaski/strawberry/wiki/How-to-translate

**Comment by Jakeukalane** [comment]
Can't introduce anything. https://translate.zanata.org/webtrans/translate?dswid=9614&iteration=master&project=strawberry&locale=es-ES&localeId=es#doc:src/translations/translations;search:previous;textflow:74118596

The project appears with a red padlock which means I don't have permissions I suppose.

**Comment by Jakeukalane** [comment]
Thanks. I added a bunch of them. There are some like the ones that show % that I don't know if they are XML entities or what, so I haven't translated them.
