### ISSUE TITLE
No gapless playback in Tidal streams

### ISSUE THREAD

**Issue by mroova** [jonaski/strawberry#26]
There is an extra gap of about one second between tracks - especially noticeable on live albums.
Would it be possible to have some pre-loading of the next song on the playlist to prevent this?
Strawberry version - 0.4.1
All the best.

**Comment by jonaski** [comment]
I'm aware of this. The gap depends on how long it takes load the stream url and the buffering of the stream. I actually have a really poor internet connection (through radio) at home so I probably have more gap than you.
There is a mechanism through the url handler and through gstreamer that is supposed to preload, but some of that code from Clementine (in player.cpp) don't make sense to me, almost as if it's not finished. I would like to rewrite it but it's not been a priority, at least not for now.
I'm not sure if it's possible to make it 100% gap free anyway.

**Comment by mroova** [comment]
Thank You for the info :)

**Comment by jonaski** [comment]
It works with this fix: https://github.com/jonaski/strawberry/commit/a6766f3c99c215f1594f7d507f159066d657fc09
It needs alot of testing before a new release.
So it would be nice if as many can test it and report back here, it should be tested with shuffle and repeat options too.

**Comment by mroova** [comment]
I still can't get gapless playback in Tidal streams; neither with ALSA nor Pulse Audio:
Strawberry 0.6.3, Ubuntu 18.04.3

**Comment by jonaski** [comment]
Its not working anymore for me either.
I'm not sure I will be able to fix it before my subscription expire.

**Comment by jonaski** [comment]
When testing commit a6766f3 it works, so there is something I did after then that broke it.

**Comment by jonaski** [comment]
I found the problem, this commit broke it: https://github.com/jonaski/strawberry/commit/99569081c98e118da41c053881693bb2071f47b0#diff-627fee9c47679582489a9e32c39acf2e
The bug now is that it requests the stream url again even when it was previously preloaded, so it waits for the url handler a second time.

**Comment by jonaski** [comment]
I increased the preload gap a bit too, it's perfect now

**Comment by mroova** [comment]
I've just installed 0.6.4 - now it works perfectly, thank you so much :)
