### ISSUE TITLE
Remove HTML tags from translation

### ISSUE THREAD

**Issue by Shatur95** [jonaski/strawberry#260]
Hello! I updated the Russian localization of the application and I think that non-translating characters (such us HTML) in translation is very inconvenient and bug-prone. For example:
```
<html><head/><body><p>Enter your user token found on: <a href="https://listenbrainz.org/profile/"><span style=" text-decoration: underline; color:#0000ff;">https://listenbrainz.org/profile/</span></a></p></body></html>
```

I suggest to remove it from translation using formatting (`boost::format`, `QString::arg` etc). Is it possible?

**Comment by jonaski** [comment]
I agree, but I'm not sure what's the best way to solve it.

**Comment by Shatur95** [comment]
In my pure-Qt projects I using `QString::arg`.

**Comment by jonaski** [comment]
Feel free to make a proposal in a PR if you want, I got too many others things to do already.

**Comment by Shatur95** [comment]
Unfortunately, at the moment I have a lot of other work with my projects too :(
But maybe I will do it in future.

**Comment by Shatur95** [comment]
Thank you!

Just a small suggestion. Things like this:

``` 
ret += "<p>";
ret += "<b>";
ret += tr("Clementine authors");
ret += "</b>";
```

Can be replaced with:

```
ret = QStringLiteral("<p><b>%1</b>").arg(tr("Clementine authors"));
```

It also generate QString [at compile time](https://doc.qt.io/qt-5/qstring.html#QStringLiteral).

**Comment by jonaski** [comment]
QStringLiteral is removed in Qt 6: https://conf.kde.org/system/event_attachments/attachments/000/000/112/original/Towards_Qt_6.pdf?1568789264

**Comment by Shatur95** [comment]
Yes I know. But you can write the following:

```cpp
ret += QString("<p><b>%1</b>").arg(tr("Clementine authors"));
```

And this will work for Qt5 and Qt6. But for Qt5 it is preferred to use `QStringLiteral` for such cases to generate `QString` at compile time (it Qt6 it will be performed automatically without this ugly marco).
