### ISSUE TITLE
Network remote

### ISSUE THREAD

**Issue by morfikov** [jonaski/strawberry#261]
We can read [here](https://github.com/jonaski/strawberry/wiki/Differences-from-Clementine) that `we don't have an android app as of yet`, but what about writing a config file for [anyremote](http://anyremote.sourceforge.net/)? It has already config for clementine.

**Comment by jonaski** [comment]
I guess anyone can write a config file for that?

**Comment by morfikov** [comment]
Probably. Here's the [clementine's config](https://pastebin.com/raw/DU1uSSX6):

**Comment by morfikov** [comment]
It looks like it's not that hard. The clementine's config work with some small changes (clementine->strawberry), but there's are some issues.

Basically all the controls like play/stop/mute/next/prev/vol+/vol-/seek work well. There's no parameters for shuffle/repeat so they don't work. 

There's some issue with stopping the app, and I don't know why this doesn't work because the following command do the job when run from a terminal:

    P=`ps auxc|grep strawberry$`; if [ "x$P" = "x" ]; then strawberry & else killall strawberry; fi

So the command can start/stop the app, but for some reason stopping doesn't work when called from `anyremote`.

Also bringing the app to the foreground doesn't work when it's minimized to a tray icon -- when the window is below some other windows, then it works well.

It looks like the cover of the current song can't be displayed, and there's only black background. Playlists also don't work. Probably because of `qdbus` -- I don't know what to do with it. I have to look through other anyremote configs and maybe I'll find some answers there.

**Comment by NielsMayer** [comment]
just setup kdeconnect on your linux host and use the kdeconnect app on android...

![Capture+_2019-09-20-11-11-15](https://user-images.githubusercontent.com/6306083/65349231-c4cfad00-db97-11e9-91c2-c3f9c4914c4d.png)

**Comment by jonaski** [comment]
Shuffle through qdbus works fine:
See shuffle status:
`qdbus org.mpris.MediaPlayer2.strawberry /org/mpris/MediaPlayer2 Shuffle`
To turn on or off just add true or false at the end.
The album art is using the old protcol mpris1 in the configuration.
Change it to something like
`qdbus org.mpris.MediaPlayer2.strawberry /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Metadata | grep mpris:artUrl:`

**Comment by jonaski** [comment]
It's nice if someone can add a configuration file for strawberry, but closing it as it's not really an issue with strawberry.

**Comment by gerroon** [comment]
Hi

Is it possible to use the remote with Clementine's remote app?

**Comment by RomanHargrave** [comment]
> Hi
> 
> Is it possible to use the remote with Clementine's remote app?

I imagine with minor changes, yes.

**Comment by gerroon** [comment]
Well the remote menu is not enabled in the preferences, not sure how I could enebale it.

**Comment by jonaski** [comment]
It won't work since we don't have the network remote protocol included, but if someone wants to maintain a android app we can add it back.
