### ISSUE TITLE
Strawberry hangs after playing a song from Airsonic

### ISSUE THREAD

**Issue by llucps** [jonaski/strawberry#263]
Hi, 

Starting from strawberry-0.6.3.52.ge45a0bf.dmg build and onwards, after playing a song through from an Airsonic server, Strawberry just freezes and I have to kill the app.

All previous builds are working just fine.. Do you know what did it change starting from that build?

Thanks.

**Comment by jonaski** [comment]
Yes, it's the stream discoverer that I added, it happened to me when testing on Windows, I didn't test macOS yet, but for Windows I ifdef'ed out one line of code that solved it.

**Comment by llucps** [comment]
ok, at least we know the reason :) Any fix so at least the app doesn't freeze?

Thanks

**Comment by jonaski** [comment]
This should fix it https://github.com/jonaski/strawberry/commit/d0eb1ba96e2715f78964da48d1a4caf2aacb4035

**Comment by llucps** [comment]
Yes.. It did work :)

Thanks
