### ISSUE TITLE
Qobuz Playback Stopped working

### ISSUE THREAD

**Issue by NielsMayer** [jonaski/strawberry#267]
Qobuz has been working fine with strawberry up till yesterday 19 September 2019.

Now I get an error "Invalid Request Signature Parameter" with the following dialog box:

![image](https://user-images.githubusercontent.com/6306083/65348255-8afda700-db95-11e9-9a5d-7fafb25ccd08.png)

I'm seeing this problem on multiple systems. Kubuntu/KDE18.04.3 on an Intel i7 desktop, Lubuntu w. lxqt 19.04 on an Atomic Pi, and Lxqt / Debian 10 on an Atomic Pi. Strawberry version 0.6.3-73-g2d67279 and 0.6.3-79-g2d4efd6.

On Kodi's Qobuz plugin, everything continues to work as before.

**Comment by jonaski** [comment]
I'm getting the same problem.
The code that generates the signature is here:
https://github.com/jonaski/strawberry/blob/master/src/qobuz/qobuzstreamurlrequest.cpp#L105
I don't see anything wrong with it though.
The Qobuz documentation on it haven't changed.

**Comment by NielsMayer** [comment]
Is there a way of getting an official strawberry api id/secret from api@qobuz.com and getting official support? I'm wondering if they figured out some way of discerning which client is really behind a particular id....

An official strawberry id/secret would have the additional benefit of having this excellent project listed under "Hi- Res quality compatible" at https://www.qobuz.com/us-en/discover/apps-partners alongside a very snall number of other officially supported Linux and open-source players: Kodi, Volumio.

**Comment by jonaski** [comment]
I e-mailed them several times, they don't answer e-mails.

**Comment by jonaski** [comment]
Here is the code Kodi uses:
https://github.com/tidalf/plugin.audio.qobuz/blob/master/resources/lib/qobuz/api/raw.py#L189

Here is the code Volumio uses:
https://github.com/volumio/volumio-plugins/blob/master/plugins/music_service/qobuz/qobuzApi.js#L19

The only difference I can see is they add the "intent" parameter. I tried that, but still the same error.

**Comment by NielsMayer** [comment]
Did anybody ever tell you how awesome you are?? 

Thanks for fixing this!

**Comment by jonaski** [comment]
Thanks!

**Comment by NielsMayer** [comment]
Unfortunately, this morning, Qobuz  stopped working in Strawberry. After a few attempts at re-login, etc it issued a message "too many login attempts" . Checking the Qobuz plugin in Kodi, it too is no longer allowing login. 

I'm not reopening this issue for now because I'm not sure if it is only affecting me due to the "too many login attempts" problem. I will wait a day or two and see if it resets, and also contact qobuz customer service to complain that their official Linux client -- kodi -- no longer works. Is it still working for you? Did the Kodi App ID change? Any progress on getting an official App ID for Strawberry?

Here's the error I'm seeing:

![qobuz-strawb-appid-error](https://user-images.githubusercontent.com/6306083/66065519-6e019600-e4fc-11e9-8ce3-998e5048c682.png)

**Comment by jonaski** [comment]
Looks like they revoked the app id.
No, they have not answered, I e-mailed them the first time in April 2019 and I only got an automatic e-mail back confirming the e-mail, so I don't suspect they plan to answer.
I also opened a issue in they Qobuz API documentation, but that's removed from GitHub now (or at least not public anymore).

**Comment by NielsMayer** [comment]
I noted that https://www.qobuz.com/account/devices lists a bunch of "blank" devices containing the same MAC address as my Linux Atomic Pi media centers that I run either Kodi or Strawberry on. It also said " You are limited to a maximum of 3 devices when using our mobile application. If you would like to remove an associated device, click on the Remove button." so I deleted all those devices. Not sure if it will help. Not clear if the Qobuz plugin on strawberry is leaving these numerous devices or if they're the result of other failed login attempts....

**Comment by Superhackman** [comment]
@jonaski probably the qobuz people got angry because they were using their appid and appsecret illegally with the downloaders that exist and are hosted here on github

**Comment by NielsMayer** [comment]
The responses to this issue appear to best summarise reasons for the change and current status. It's probably a good idea to watch this for future updates: https://github.com/tidalf/plugin.audio.qobuz/issues/247

**Comment by NielsMayer** [comment]
Specifically: 

> 
> From Qobuz:
> 
> Good day
> 
> Thank you for your message.
> 
> For security reasons, access to Qobuz via Kodi has been blocked for the time being.
> There is currently a danger of hacker attacks.
> We are currently in talks with Kodi to solve the problem as quickly as possible.
> We recommend bubbleupnp, Mconnect or Audirvana as alternatives.
> 
>

**Comment by NielsMayer** [comment]
Volumio got its own new key -- how about asking again for Strawberry's own new key ??? ---  now that things have probably settled down after the initial threat of lawsuits from record companies vs bulk downloaders which i believe qobuz marketing calls "danger of hacker attacks" above :-)  

https://forum.volumio.org/qobuz-temporarily-not-working-from-t12936.html

> UPDATE 23/09/2019
> 
> After a 4 days long exchange with QOBUZ technical team there is finally a solution, although not the one we were hoping for.
> They decided to revoke the API key and issue a new one, in order to allow only updated Volumio clients to access their service.
> 
> For our users it means that to access QOBUZ again, it is required to update to latest Volumio version. We are rebuilding all Volumio versions (for all officially supported hardwares), and the new version will be available tomorrow (24/09/2019).
> 
> We are sorry for those days without your favourite music, but it was not under our control and we worked as hard as possible to minimize any disruption. We will update as soon as the updates will be available.

**Comment by jonaski** [comment]
I doubt Qobuz allows the keys visible in the source code, how does Volumio handle that?
I've tried to contact them multiple times, I receive an automated answer, which means the e-mail isn't blocked by any spam filter, but they never reply me.
But maybe one of the other contributors want to try @m4x3t @gavinhoward or @MartinDelille 
A guy contacted me through the FB page that he had contacted Qobuz and received a reply, so it's pretty strange.

**Comment by gavinhoward** [comment]
I gave it a try, but I was not able to. Sorry.

**Comment by dimqua** [comment]
@jonaski any chances that you will re-add Qobuz support in the near future?

**Comment by jonaski** [comment]
I think there is a way to extract the client ID and secret from the electron application they use for windows, but the main blocker is that I don't have a subscription so I'm not able to see if it would work or not. I personally don't want to pay for a Qobuz subscription just to support it in Strawberry for work I do for free.
So either someone needs to provide a subscription or volunteer to do the support, deal with issues, etc.
With Tidal it is possible to add an extra e-mail to a family plan, if that's the case for Qobuz then that would probably work.

**Comment by dimqua** [comment]
@jonaski, I believe Qobuz provides 1 month free trial period. Wouldn't it be enough for add the support, if possible?

**Comment by jonaski** [comment]
The trial is used up, it was what I used the last time, it's not enough to have 1 month free since they might change the API again, and also if I decide to change some code that is common for streaming in Strawberry, like the URL handler, it might break something with Qobuz and I to make sure that it still work. I don't want to have a bunch of broken services like in Clementine that no-one ever fixes and that requires a paid subscription to fix. However it looks like you can play preview's of the tracks without a subscription so that so I might be able to add it back. It is however much harder to obtain a client ID and secret for Qobuz than Tidal, so very few users will probably be able to use it. I don't want to do scraping of sites or files to find them, or provide it to users in case of legal issues.

**Comment by jonaski** [comment]
Qobuz is added back.
