### ISSUE TITLE
Playlist tabs appear incorrectly

### ISSUE THREAD

**Issue by RomanHargrave** [jonaski/strawberry#268]
**Describe the bug**
After having restarted strawberry with more than one playlist open, I found that the playlist tabs - while still present - lacked any controls or titles. I closed all but one tab and re-opened them. While the act of opening corrected the problem, it resulted in the playlist tab bar being very tall.

**To Reproduce**
Start strawberry after having closed it with more than one playlist open. Observe that controls and labels are missing from the playlist tabs. Open a stared playlist and observe that the tabs now posses names and controls; however, the proportions are wildly incorrect.

**Expected behavior**
Playlist tabs are displayed correctly.

**Screenshots:**
Playlists upon opening:
![after opening](https://i.imgur.com/7dACi1o.jpg)

After opening a playlist:
![after opening a playlist](https://i.imgur.com/HNTApJI.jpg)

**System Information:**
 - Operating system: Debian Unstable (Using prebuilt package for Bullseye), 64-bit, multiarch
 - Strawberry Version: ga174528

**Additional context**
This appeared between c66c1e1 and a174528. I will do some testing to pinpoint the version that introduced the bug.

**Comment by RomanHargrave** [comment]
Strangely, after downgrading back to c66c1e1 the issue is still present.

**Comment by jonaski** [comment]
I can't reproduce this. Try with a configuration. Try rename ~/.config/strawberry/strawberry.conf so a new one is created.

**Comment by RomanHargrave** [comment]
That did indeed resolve the issue. I went though `[Appearance]` and determined that `use_custom_set` being `true` caused the problem.
