### ISSUE TITLE
Click/pop sound with ALSA

### ISSUE THREAD

**Issue by mroova** [jonaski/strawberry#27]
On changing tracks manually there is an unpleasant click/pop sound - appears only when using ALSA and selecting output device manually - I've attached a screenshot of my settings. 
No such problem when using automatic selection or PulseAudio.
Strawberry version - 0.4.1
All the best.
![screenshot from 2018-11-04 17-50-12](https://user-images.githubusercontent.com/10324822/47967185-feb8c300-e05a-11e8-864c-5cf5636e93bb.png)

**Comment by jonaski** [comment]
I have experienced this myself, but it was a long time ago, and I don't remember what soundcard or dac I had then as I've had so many.
When I try to reproduce this now, I don't see any problem on any setup. I have tested both with on board soundcard Intel PCH ALC892, Marantz HD-DAC1, Arcam irDac II and McIntosh D100. All are fine. I plugged a couple of basic PC speakers on my onboard soundcard to test right now.
I'm pretty sure it's the soundcard or the way your system is setup. And there isn't anything in the code I can try to change to fix it either.
I always uninstall and disable pulseaudio on all my systems, and on my production setup I disable onboard soundcards in bios and block others through modprobe. I only activate them when I do the final testing of the backend settings.
If you have pulseaudio active, you can try uninstall it or disable it and see if that does anything.

**Comment by mroova** [comment]
Thank You for the explanation. 
Unfortunately disabling pulseaudio didn't help.
I'll try modprobe :)
