### ISSUE TITLE
artist list click behaviour not correct

### ISSUE THREAD

**Issue by pupper68k** [jonaski/strawberry#272]
**Describe the bug**
When I click on an artist in the list of artists in the collection pane, instead of selecting that artist stawberry selects all artists going down to the one I selected. [Here is an example](https://cloud.aidanis.online/s/r6H3NRMKWYW9q9y)

Additionally, I cannot scroll in the artists pane.

**To Reproduce**
- Open Strawberry 
- Open Collection Pane
- Try to select an artist
- Try to scroll in artist pane

**Expected behavior**
I assume that only one artist should be selected, and not all the artists above the one I selected. Additionally, I assume I should be able to scroll through my artists list.

**System Information:**
 - Operating system: OpenSuse Tumbleweed
 - Strawberry Version: 0.6.3

Running on KDE.

**Comment by jonaski** [comment]
I've never seen this problem. Probably specific to settings in KDE or qt5ct, can you try with a new user with a clean user profilene and see if you get the same issue?

**Comment by pupper68k** [comment]
installed strawberry on a fresh opensuse tumbleweed install with kde plasma.
was unable to click on the "click here to add some music" area in the empty artist list.

**Comment by pupper68k** [comment]
installed strawberry 0.6.4 on an arch linux install using KDE desktop. Reproduced not being able to click on the "click here to add some music" area. Added a collection folder in settings and was able to click on individual artists after it had loaded. Once I had selected an artist in the artist selection box, any additional selections made resulted in all artists between the first selection and the second selection to be selected. (as if shift was held down).

**Comment by pupper68k** [comment]
It appears that I can scroll through the artists in the arch linux installation, however there is heavy visual artifacting, as if only the bottom half of the list is scrolling. this could either be strawberry or perhaps the dated graphics on this T61 I have running arch linux.

**Comment by pupper68k** [comment]
I dont know if it makes a difference but all of these machines were on x11 and not wayland

**Comment by jonaski** [comment]
I'm using opensuse tumbleweed too (with XFCE), up to date with the latest version of Qt, I can't reproduce any issues. I've also tested on opensuse tumbleweed with Plasma in a VM and it works there too. Also, no-one else has reported the same, so it must be something with your computer.
The only other thing I can think of is that it might be some of your music files, maybe you can backup strawberry.db and create a new directory with only some music files and try to see if you get the same issue then.
Other than that I suspect it might be related to your HW, perhaps your graphics card like you suggested yourself.
You will probably get the same issue with other applications using Qt 5 with a QTreeView in that case.
