### ISSUE TITLE
Scrobbling Album Artist instead of Artist

### ISSUE THREAD

**Issue by beescopy** [jonaski/strawberry#274]
**Is your feature request related to a problem? Please describe.**
Songs are normally tagged like this (this is for example used by the musicbrainz database):
Title = "SongTitle"
Album = "AlbumName"
Artist = "Artist1 feat. Artist2 and Artist3"
Album Artist = "Artist1"

**Last.FM gets confused when "Artist1 feat. Artist2 and Artist3" is scrobbled as Artist.**
Most times the song can't be linked to an artist page, except when all artists in this exact configuration are known to have been working together on full albums or many songs, or when the scrobbled song is indeed a single.

**The result?**
Missing Coverart and weird listening statistics.
Listening to only one Album might result in "This week you mostly listened to:
'Artist1'
'Artist1 feat. Artist2 and Artist3'
'Artist1 feat. Artist4'
'Artist1 and Artist5'
'Artist1, Artist6 & Artist7'"
instead of just:
'Artist1'

**Describe the solution you'd like**
An option to send the Album Artist information as Artist would resolve this issue.

**Additional context**
A simple checkbox "Prefer Album Artist over Artist" in the Scrobbler-Settings would be very helpful.

**thank you.**

**Comment by jonaski** [comment]
It's almost as if last.fm ignores albumArtist completely.
