### ISSUE TITLE
Album artist in lower case in playlist

### ISSUE THREAD

**Issue by mshmm** [jonaski/strawberry#275]
I've added the Album artist column to the playlist in Strawberry 0.6.5 (on Kubuntu 19.04), but unlike the Artist column, the Album artist appears in lower case. So a track by The Beatles appears as "The Beatles" in the Artist column and "beatles, the" in the Album artist column. My music collection is FLAC files with the Album Artist field in each tag (and in Title Case for each Album Artist).

**Comment by jonaski** [comment]
Thanks I didn't see that until now

**Comment by mshmm** [comment]
Thank you for the quick response :)
