### ISSUE TITLE
Cannot get any external devices to mount

### ISSUE THREAD

**Issue by Dubhain** [jonaski/strawberry#280]
**Describe the bug**
I've reported this before (under a different account), but it was marked as solved so I can't now comment on it, but it's not been solved for me. I cannot get any of my external devices to connect to strawberry - or any other media player. They all connect fine with a file manager (any of them). I can transfer files fine. Strawberry shows the device correctly, offers for me to 'double-click to open the device', but then it either does nothing at all (older devices?) or it reports and error. At no point can I get any of the device's songs up. More importantly, I can transfer songs correctly, but I can't remember how much of this we went through on the last discussion, so for now... the external devices issue just doesn't seem to be fixed for me.

**To Reproduce**
Open Strawberry, plug in an external device in MTP mode, double-click to mount/open

**Expected behavior**
The songs from the device become available, it becomes possible to transfer songs/playlists to the device

**System Information:**
 - Linux Manjaro 4.19 KDE Desktop
 - Strawberry 0.6.5

**Comment by jonaski** [comment]
Both MTP and filesystem devices works here.
MTP devices are special, you should not mount them before trying to connect.
Need more details on what devices you use.
But if it doesn't work for you in any application, the appropriate place to the report or get help with this might be your Linux distros mailing list or web forum.
The MTP library might not support all phones.

**Comment by Dubhain** [comment]
Not sure what "you should not mount them before trying to connect" means in this context. When I plug it in, KDE recognises it and asks me if I want to browse files. Do you think it's mounted it already? If so, I can't see how I could prevent that.

> Need more details on what devices you use.

Creative Zen X-Fi, Sony Xperia Miro, Sony Xperia Z2 and Sony Xperia XZ premium.

> The MTP library might not support all phones.

All those are listed on my MTP rules and KDE's file manager opens them using MTP without any trouble.

>  if it doesn't work for you in any application, the appropriate place to report or get help with this might be your Linux distros mailing list or web forum.

Yeah, I've tried that too, but no-one seems to have any answers, people seem to have universally had trouble with it, so I thought I might have some luck with those working from the other end (trying to get applications to work with different OSs). It doesn't seem, from the questions I've asked at my distro forums, like I've got anything set up wrong. It might just be that Manjaro with KDE is incompatible with media players, but In that case I'm not sure if it's Mnajaro/KDE that need to change or the media players. I'm afraid I don't know enough about it to even guess.

**Comment by jonaski** [comment]
When you connect your phone, do you select transfer files option when it pops up? Otherwise it won't work. Check that it's not mounted with: `df -h` on the teminal.
The Creative Zen X-Fi is probably not a MTP device and should mount as a filesystem device, so it should not be affected by any issue caused by MTP problems.
But you could simply test with a memory stick or SD card and see if you get the same issue with those.
I guessing permission issues.
Can you try to start strawberry from the terminal and see if there more output?
