### ISSUE TITLE
Meta key binding issue

### ISSUE THREAD

**Issue by NogradThGin** [jonaski/strawberry#281]
**Describe the bug**
Can't bind Meta key, causing an unknow key to be bound

**To Reproduce**
Just try to bind Meta (Win key) + another

**Expected behavior**
Expected to bind Meta + Key 

**Screenshots:**
![2019-10-23_19-57](https://user-images.githubusercontent.com/6053748/67420683-63a05c80-f5cf-11e9-93eb-6015c03bdc88.png)

**System Information:**
 - Operating system: Archlinux up-to-date (manual 23.10.2019)
 - Strawberry Version: 0.6.5-27-g004b000

**Comment by jonaski** [comment]
This is a bug in Qt: https://bugreports.qt.io/browse/QTBUG-62102
Will work when fixed in Qt.
