### ISSUE TITLE
Misreported bitrate with mp4 files encoded with ALAC.

### ISSUE THREAD

**Issue by lemonzest79** [jonaski/strawberry#282]
**Describe the bug**
Bitrate is misreported in the context display tab, also misreported as AAC and not ALAC.

Most of the time bitrate is reported correctly, but some times its over inflated as can be seen in the screen shot.

**To Reproduce**
Play an mp4 file encoded with ALAC (Apple Lossless Audio Codec)

**Expected behavior**
The Bitrate to be correctly reported

**Screenshots:**
![Screenshot from 2019-10-24 17-01-30](https://user-images.githubusercontent.com/40669977/67504188-d7e70880-f680-11e9-8352-66303564b931.png)

**System Information:**
 - Operating system:

Fedora 30 amd64

 - Strawberry Version:

Version 0.6.5-27-g004b000

**Additional context**

The ALAC files are encoded with ffmpeg via the abcde CD ripper script.

**Comment by lemonzest79** [comment]
Mediainfo dump.

Complete name                            : /home/lemonzest/Music/Square_Enix/Octopath_Traveler_Arrangements_-Break_&_Boost-/01.The_Frostlands.m4a
Format                                   : MPEG-4
Format profile                           : Apple audio with iTunes info
Codec ID                                 : M4A  (isom/iso2)
File size                                : 21.1 MiB
Duration                                 : 4 min 37 s
Overall bit rate mode                    : Variable
Overall bit rate                         : 639 kb/s
Album                                    : Octopath Traveler Arrangements -Break & Boost-
Track name                               : The Frostlands
Track name/Position                      : 1
Performer                                : Square Enix
Genre                                    : Soundtrack
Recorded date                            : 2019
Tagged date                              : UTC 2019-07-25 13:09:06
Writing application                      : Lavf58.20.100
Cover                                    : Yes
Comment                                  : Ripped with abcde 2.9.3
replaygain_track_peak                    : 0.7501
replaygain_album_peak                    : 0.9988
replaygain_track_gain                    : -3.04 dB
replaygain_album_gain                    : -5.26 dB

Audio
ID                                       : 1
Format                                   : ALAC
Codec ID                                 : alac
Codec ID/Info                            : Apple Lossless Audio Codec
Duration                                 : 4 min 37 s
Duration_LastFrame                       : -17 ms
Bit rate mode                            : Variable
Bit rate                                 : 636 kb/s
Nominal bit rate                         : 1 411 kb/s
Channel(s)                               : 2 channels
Sampling rate                            : 44.1 kHz
Bit depth                                : 16 bits
Stream size                              : 21.1 MiB (100%)
Default                                  : Yes
Alternate group                          : 1

**Comment by jonaski** [comment]
I'm aware of the bitrate bug, I play 99% FLAC myself, but I recently tested with some MP3 and MP4 files and I saw the bug too.

**Comment by jonaski** [comment]
The bitrate problem is fixed now. But identifying ALAC as its own format is a bit more tricky since it's the MP4 container, it's identified as just MP4 by both taglib and gstreamer.
