### ISSUE TITLE
Remember column size, shown/hidden columns

### ISSUE THREAD

**Issue by Obigre** [jonaski/strawberry#292]
When i resize the columns in the main playlist window and decide which one i want to see, if i quit Strawberry and come back to it, all columns are back to the default layout. I'm not really into bitrate and all, but i do want to see the year the album came out !
Would be nice if it remembered these preferences :) columns hidden, column shown, and their size. 👔

**Comment by jonaski** [comment]
It works fine here.
It usually happen if there is a crash on exit, so it won't get a chance to save before quitting. Usually caused by a linked library, symbol collisions, etc.
Since you give zero information about anything and it's not possible to reproduce we can't fix it.

**Comment by Obigre** [comment]
Oh sorry i thought it was a missing feature, i'll try to reproduce it. It might have happened because i chose to shutdown the computer without closing Strawberry first.

**Comment by jonaski** [comment]
That's probably why.
It was originally saving immediately on each change, but that causes slowness for users with non-SSD, and additional wear for users with SSD.
I think that just saving on exit like we have now is the best way and should work in most cases.

**Comment by Obigre** [comment]
That was definitely why. I'm a new Linux user and was not really closing Strawberry when i thought i was. Strange ! Thanks for your answers anyway :)
