### ISSUE TITLE
double click on album cover to change its size or open file location

### ISSUE THREAD

**Issue by alekksander** [jonaski/strawberry#293]
this is a request to add preferable action on double clicking cover visible in library viewer. two convenient possibilities are changing its size (toggle big and small) or opening file location.

![Screenshot_20191110_161511](https://user-images.githubusercontent.com/3148302/68546346-8a370380-03d5-11ea-8d55-5e04ae0b9af7.png)

**Comment by jonaski** [comment]
Not sure I want this.
