### ISSUE TITLE
Add ability to display custom track fields in "Context" tab

### ISSUE THREAD

**Issue by ilevantis** [jonaski/strawberry#30]
It would be useful to have the information being displayed in the Context tab be a bit more customisable. 

The way the custom notification message is currently managed would be a perfect way to manage this tab.

**Comment by jonaski** [comment]
You know you can right click and check/uncheck what you want?

**Comment by ilevantis** [comment]
Currently the options on right clicking for me are:
- Show song technical data
- Show engine and device
- Show albums by artist
- Show song lyrics

I see no way to customise the panel containing "%title% - %artist% - %album%".

E.g. I want to change the order of those, or show the song year or track number etc.

**Comment by jonaski** [comment]
Making the top text configurable like the OSD (notifications) is pretty easy. However making it more adjustable like changing the order involves a lot of work. But it could work like the fancy tabbar with moving the icons/text.

**Comment by gavinhoward** [comment]
I can probably take this issue, but expect slow progress.

**Comment by gavinhoward** [comment]
@jonaski I think I have a solution, but I want your approval before I just jump in.

I will add a `Context` section to the settings dialog. This is where the settings can be changed.

Like the OSD notifications, there will be `Title` and `Summary` settings that can be customized by text. I will reuse as much as I can.

However, below the text settings will be a list of items:

* Summary
* Cover
* Technical Data
* Engine and Device
* Albums by Artist
* Song Lyrics

The order above will be the default order, but the order can be changed. (See below.)

Each of these list items will have four elements:

* A checkbox to enable/disable the item.
* The label.
* An up arrow that, when clicked, will move the item up one place in the list.
* A down arrow that, when clicked, will move the item down one place in list.

Obviously, the up and down arrows will be disabled if the item is at the top or bottom, respectively.

How does that solution sound?

**Comment by jonaski** [comment]
Sounds great

**Comment by gavinhoward** [comment]
I just read through this again, and I realized that I might have read it wrong. @ilevantis did you want to change the order of everything, or just the song info in the title and summary? The latter would be much easier.

**Comment by ilevantis** [comment]
Just the song info summary section is all I'm interested in. The rest of the items in the context panel are not items I use.
