### ISSUE TITLE
Playlists blank on restart - Database error

### ISSUE THREAD

**Issue by nertia** [jonaski/strawberry#302]
**Describe the bug**

Strawberry does not save the contents of playlists on close. Playlist 1 is populated with the first three albums that were added to it after install (these were added automatically and began to play while my first large music directory was added) replacing any changes I make to it. Any subsequent playlists I create load up blank. If I manually save the playlists in my home directory, they can be loaded  using 'load playlist' and are populated as expected.

Additionally, at an undetermined time, Strawberry shows a dialog box titled "Strawberry Error" with the contents:

`Database: *** in database main *** On tree page 18 cell 2: Rowid 16432 out of order Page 1102: btreeInitPage() returns error code 11 On tree page 18 cell 0: Rowid 5240 out of order Page 80 is never used Page 81 is never used Page 82 is never used Page 83 is never used Page 84 is never used Page 85 is never used Page 86 is never used`

**To Reproduce**
Change contents of playlist 1, create additional playlists and populate from library, restart Strawberry.

**Expected behavior**
On Startup Strawberry should load previously used playlists in the same state as when it was closed.

**System Information:**
 - Operating system: Debian 10
 - Strawberry Version: 0.6.6-2-g45e9dd9
 - Installed via .deb package

**Additional context**
The database error dialog does not appear to correspond with a full collection rescan or at startup, but does appear within 5-10 Minutes of run.

**Comment by jonaski** [comment]
Your database is corrupt

**Comment by nertia** [comment]
How should I delete the corrupt database? I have removed the directory, restarted strawberry an the re-added the directory, but on the initial scan the database error dialog appears almost immediately. Should I re-install Strawberry?

**Comment by jonaski** [comment]
Run:
```
sqlite3 ~/.local/share/strawberry/strawberry/strawberry.db
pragma integrity_check;

```
You can try to remove ~/.local/share/strawberry/strawberry/strawberry.db and start with a new database, be sure to close strawberry first.
If it happens again check your hdd for failure.

**Comment by nertia** [comment]
The sql check returned errors, I deleted the database and re-added the directory without errors so far. Unfortunately the HDD with the music on is showing errors, so is probably the root of the problem.

Thank you for your help, I like this software and its focus on simplicity and musical fidelity.
