### ISSUE TITLE
Opening Strawberry creates a second icon in dock.

### ISSUE THREAD

**Issue by TheGreatestJannet** [jonaski/strawberry#305]
**Describe the bug**
When I favourite Strawberry in Grome 3.34 and click on it to open it a new Strawberry icon appears instead meaning there are now two icons on the dock.

**To Reproduce**
1. Favourite Strawberry
2. Open it
3. Watch as a new icon appears.

**Expected behavior**
A second icon shouldn't appear on the dock when opening it.

**Screenshots:**
![Screenshot from 2019-11-17 11-06-29](https://user-images.githubusercontent.com/51300636/69006683-64a47f80-092a-11ea-85a6-496d50dfd617.png)

**System Information:**
 - Operating system: Arch Linux
 - Strawberry Version: 0.6.6

**Additional context**
While the screenshot shows the Dash to Dock Extension I can confirm that it happens even if the extension is disabled.

**Comment by jonaski** [comment]
Try adding StartupWMClass=strawberry to the desktop file.

**Comment by TheGreatestJannet** [comment]
Thanks that works. Does that mean that the package for Arch needs to be updated with this to fix it?
