### ISSUE TITLE
Regression; "Pressing previous in player" "Restart song..." config not working

### ISSUE THREAD

**Issue by KangarooCreativeTeam** [jonaski/strawberry#306]
**Describe the bug**
After upgrading Strawberry, the config "Pressing previous in player will..." has stopped working to what I had prior set it to; "Restart song, then jump to previous track if pressed again"

**To Reproduce**
1.  Make sure config  >  Behavior  >  "Pressing previous in player will..." is set to; "Restart song, then jump to previous track if pressed again"
2.  Play some music
3.  Either press "previous track" button in interface, or press it's keyboard shortcut
4.  In both cases, it immediately jumps to the previous track

**Expected behavior**
1.  It should work as expected; by either pressing "previous track" button in interface, or pressing it's keyboard shortcut, it should jump to the start of the track, & then back to the previous track if pressed again.

**Debugging**
1.  Set config  >  Behavior  >  "Pressing previous in player will..." to; "Restart song, then jump to previous track if pressed again"
2.  Save config
3.  Exit Strawberry (100% close it down - no strawberry process running)
4.  Launch Strawberry
5.  Check config  >  Behavior  >  "Pressing previous in player will..."
6.  Find it will have reverted to it's default state;  "Jump to previous song right away"

**Debugging - FURTHERMORE**
1.  Backup (copy) Strawberry config file; $HOME/.config/strawberry/strawberry.conf
2.  Run debugging steps above (change & save config as described)
3.  Run diff against the live & prior backed up Strawberry config file
4.  Confirm that this specific config has NOT been set in the config file  (both files are still identical)

**System Information:**
 - Operating system:  Arch Linux x64  (Linux 5.3.11-zen1-1-zen)
 - Strawberry Version:  strawberry 0.6.6-1

**Additional context**
* I was using Arch AUR strawberry-full-git (0.6.5.r27.g004b000) (live compiled from that git commit)  >  The "restart song" was 100% confirmed working
* Then I switched to Strawberry v0.6.5 (pre-compiled binary in Arch official repo)  >  I'm 99% certain it was also working here
* Then I switched to Strawberry v0.6.6 (pre-compiled binary in Arch official repo)  >  this bug is encountered

**Thoughts**
So; it's looking like this is a regression between v0.6.5 & v0.6.6, & the setting is now no longer updated (or is now possibly missing entirely from the config file). 
(I've looked through the git commits between those releases; but unfortunately I can't work out if anything has caused this.  I tried :(

Sorry for the long / verbose post - I've tried to provide helpful info, and to respect your bug report template ^_^

(Thank you for Strawberry!  The sound quality is amazing!  (I'm a recent convert from Clementine...)).

**Comment by jonaski** [comment]
Thanks for the detailed report.
Looks like both "Pressing "Previous" in player will..." and "Double clicking a song in the playlist will..." is broken.
Even though they are in the GUI, the whole loading and saving of those settings are gone from the code. That has to be much longer back than previous version.
Fixing it now.

**Comment by jonaski** [comment]
Fixed https://github.com/jonaski/strawberry/commit/71fa5acc74fabae02f8b0a5b45da3a56b97db080
