### ISSUE TITLE
Moodbars for Youtube-ripped opus-files are not created or used

### ISSUE THREAD

**Issue by v-fox** [jonaski/strawberry#307]
**Describe the bug**

When opus file ripped from Youtube by [a browser extension](https://addons.mozilla.org/en-GB/firefox/addon/youtube_downloader_webx/) (or youtube-dl, I presume) and played, not only they lack ability to store tags, but worse, mood-files are not created nor ones made by Clementine are read from the files' directories. Instead the bar of previously played file is stuck.

**To Reproduce**

* Download [a webm/opus video clip from Youtube](https://www.youtube.com/watch?v=KnTlc-9anqE).
* Add it to playlist and play.
* See no moodbar and .mood-file.

**Expected behavior**

Moodbar.

**Screenshots:**

**System Information:**
 - Operating system: openSUSE Tumbleweed 20191116
 - Strawberry Version: 0.6.6

**Comment by v-fox** [comment]
Ah, I just added parent directories that hold those video clips to collections, did database update and restarted. That returned the player to its senses. Not sure if feeding it directories of mostly video-files is optimal solution.

It still behaves weirdly with those files: if imported in non-m3u playlist, they are silently skipped. And when they not skipped, some of them (particularly mp4 video-files with internal audio-tracks) show '-' instead of even a filename. Although, that one is probably because they can have tags but those are empty and the player does not try replacing empty title names with file-names.

**Comment by jonaski** [comment]
I tested on a MP4 with youtube-dl, worked fine here, showed up with filename and editing tags works too.
How did you convert it to Opus?

**Comment by v-fox** [comment]
I didn't convert anything. I downloaded them as is: mp4 (sometimes with external aac audio) for some files and webm/opus for most which is default for Youtube now. I've got '-' named tagless-files mp4 when I imported m3u playlist from Clementine, if imported in any other format, those files are just skipped. Opus files from Youtube thought do not allow tags and always show filenames as titles.

**Comment by jonaski** [comment]
We only support audio files, some video files might still work as long as taglib reads them, I could not reproduce any problems with any MP4 downloads from the firefox youtube downloader extension you mentioned.

**Comment by v-fox** [comment]
I was initially talking about audio-files. It seems part of the cause was absence of parent directories for those files from Collection directory list, the other part is something inexplicable that was worked around by exporting as m3u and re-importing the playlist. After that moodbars and filenames started to appear for them.
