### ISSUE TITLE
Disabling automatic lyrics/cover lookup

### ISSUE THREAD

**Issue by CatPlanet** [jonaski/strawberry#310]
Currently there is no option to disable lyrics lookup and cover art lookup, resulting in 3 hits for lyrics and 3 hits for covert art per song.

I'd like to have an option to opt out from these featureas as I, first of all, don't use them and secondly, it notifies 6 third party services every time I listen to a song which makes me a bit uncomfortable.

**Comment by jonaski** [comment]
You can right click in the context while song is playing disabling lyrics, uncheck "search automatically" to disable cover fetching.
