### ISSUE TITLE
Multiple count of the same Album + Album tracks list is incomplete during Tidal Search

### ISSUE THREAD

**Issue by Fef0** [jonaski/strawberry#313]
**Describe the bug**
First of all thanks for the new update, being able to see the "Explicit" albums is really cool!

With the latest update during Tidal Search of an Artist, each album is counted multiple times.
Plus some of the tracks don't show up in Explicit albums even tough they're on Tidal Store page.

**To Reproduce**
I searched for "Serj Tankian" as Artist and you can see the issue with "Harakiri" album.
If you go to https://store.tidal.com/it/search/ and search "Serj Tankian Harakiri" you'll see that there are actually 5 albums, all the same (it must be a Tidal error tough), not 10.

**Expected behavior**
It should count each album once and it should count every track in the album, not just a few.

**Screenshots:**
![Screen1](https://user-images.githubusercontent.com/19290442/69376538-bb071a80-0caa-11ea-8ddc-a694a213af46.png)
![Screen2](https://user-images.githubusercontent.com/19290442/69376539-bb071a80-0caa-11ea-8fc7-4732e7a4e12c.png)
![Screen3](https://user-images.githubusercontent.com/19290442/69377008-ad9e6000-0cab-11ea-8e0a-d8fa6bb0c9eb.png)

**System Information:**
 - Operating system: Arch Linux 5.3-11
 - Strawberry Version: commit b7d360d

**Comment by jonaski** [comment]
Thanks for testing it. I had to revert the commit from yesterday.
Tidal returns Explicit also for single songs on the album. So we have to add the Explicit to the album title when receiving the albums, not the songs. Will reopen the other issue.
