### ISSUE TITLE
KScreenlocker on KDE 5.16.5 and QT 5.13.2 while strawberry is playing segfaults

### ISSUE THREAD

**Issue by NucleaPeon** [jonaski/strawberry#316]
**Describe the bug**
https://bugs.kde.org/show_bug.cgi?id=414555

I will play some songs in strawberry and when I lock the screen, the lock screen background will appear but it will flicker between that and a black screen infinitely and I won't get a login prompt. Looking at the logs in journalctl shows segfaults. See the bugs.kde.org link for stack traces.
This does not occur when playing music with DragonPlayer or JuK.

**To Reproduce**
Play a song in strawberry and lock the screen (Ctrl+L). 
Currently on Version 0.6.6-54-gc1ec568f, but it effected a previous version I built.

**NOTE**: If strawberry is stopped, this issue will not present itself. Only when it is playing will I get a segfault.

**Expected behavior**
Lock screen should show the media player widget with the current song.

**Screenshots:**
I can take some photos on request.

**System Information:**
 - Operating system: Gentoo 2.6 up-to-date with KDE plasma 5.16.5 and QT 5.13.2 
 - Strawberry Version: 0.6.6-54-gc1ec568f built from git using master branch.

**Additional context**
This only started to occur after I did an update to strawberry (using git, a previous revision), qt (from 5.13.1 I think) and some kde packages including kscreenlocker. Strawberry used cmake and the others used emerge.

I thought it was a kde issue, but I think perhaps its an issue with how strawberry integrates with the kscreenlocker, perhaps there was an api/abi change that broke previous behaviour. Whether this is a valid bug or not, this is my experience and reproduceable.

To get out of the screen flickering, I change to another tty, log in and run `loginctl unlock-session 1`, then switch back to initial tty. I have to restart my machine to prevent kwin from doing multiple segfaults over time, though it doesn't completely break my workflow.

In the mean time, I will update plasma to 5.17.3 and report back.

**Comment by jonaski** [comment]
Strawberry isn't integrated with kscreenlocker or any KDE components at all.
I'm pretty sure this bug is in KDE.
Try disabling the system tray icon and see if the crash in kscreenlocker is gone.

**Comment by NucleaPeon** [comment]
After updating plasma, I am no longer able to reproduce it (though time will tell, I've only attempted to reproduce it a couple times)
Thanks!
