### ISSUE TITLE
Add Strawberry to Chocolatey

### ISSUE THREAD

**Issue by b16r05** [jonaski/strawberry#318]
I have opened a request to add strawberry to Chocolatey before I try it out. Check it out here: https://github.com/chocolatey-community/chocolatey-package-requests/issues/739

I hope it is lighter than clunky Clementine : )

**Comment by jonaski** [comment]
Thanks for submitting Strawberry to Chocolatey. I started on it a long time ago but never had time to finish it. I think it was working but wasn't really sure. I'm not very familiar with Chocolatey packaging.
