### ISSUE TITLE
[bug] Library UI Pane behaving unexpectedly

### ISSUE THREAD

**Issue by shsorbom** [jonaski/strawberry#32]
# System Information
 **OS:** KDE Neon 5.14.3
**QT Version:** 5.11.2
**Strawberry Version:** 0.4.1 Release, Behavior also observed in 36-g77e5d02 build
# Bug Symptoms
Folders in the library paine don't always expand/collapse when clicked. The folders that are non responsive cannot be added to the main playlist. Also possibly related: content, queue, and playlist buttons to the left of the library pane are not resposive when clicked, except for the fact that they show being selected.

**Comment by jonaski** [comment]
Are you referring to the file view or the collection view?

**Comment by jonaski** [comment]
I use the same version Qt, but I don't see this issue. Maybe its related to the desktop environment or some settings or theme in KDE?

**Comment by shsorbom** [comment]
It could be theme related. I usually use Oxygen, but I just switched to Breeze, and everything miraculously worked as expected.
