### ISSUE TITLE
Left menu / playlist window issue when not using Breeze theme.

### ISSUE THREAD

**Issue by nickorange47** [jonaski/strawberry#321]
The Oxygen and Fusion themes (possibly others) seem to cause an issue, where if you click on the left menu (context, collection, files, playlists, queue, devices), then it doesn't change to that item - just a partial highlight (see image - I've click on playlists, but selection remains on Collection). 

The list of playlists was also behaving strangly (could not grab/drag the scroll bar, and multiple entries would get selected at the same time).

The problem goes away when using the Breeze theme, which can be forced with the following if you want to use a different theme elsewhere:
$ QT_STYLE_OVERRIDE=Breeze strawberry

I've only tried this on two KDE Neon systems so far.
![Screenshot_20191203_173531](https://user-images.githubusercontent.com/58483718/70076508-d5b88800-15f6-11ea-8a77-d567098c29bc.png)

**Comment by jonaski** [comment]
Does it work if you turn off using system icons in the setting?

**Comment by nickorange47** [comment]
Thanks for your reply.

I've just checked, and no - the issue remains regardless of whether use system icons are checked or not (and restarting strawberry each time it's changed). The issue is also the same what ever the menu is set to (large/plain/small/tabs/icons).

Regarding the scrollbar in playlist view issue (also occurs except when using Breeze), it seems it's mostly only grabable by the bottom half of the scrollbar - the top half doesn't respond to clicks. It will sometimes spit out the follow errors when trying to grab / move in and out of focus of the scrollbar - not sure if it's related:
__logging_message__07:36:05.750 WARN  unknown                          QXcbConnection: XCB error: 8 (BadMatch), sequence: 2422, resource id: 73400544, major code: 130 (Unknown), minor code: 3
__logging_message__07:36:05.766 WARN  unknown                          QXcbConnection: XCB error: 8 (BadMatch), sequence: 2523, resource id: 73411170, major code: 62 (CopyArea), minor code: 0

**Comment by jonaski** [comment]
Is this the same issue as #279?

**Comment by jonaski** [comment]
I can reproduce this on KDE with Oxygen theme. I have found the problem, it's related to the device view, the device view itself is added to as a widget to the tabbar instead of the parent container.

**Comment by nickorange47** [comment]
That's great, thanks for tracking it down & for the update on the cause!
