### ISSUE TITLE
French translation now completed

### ISSUE THREAD

**Issue by david-geiger** [jonaski/strawberry#322]
Hi,

I'm the Mageia strawberry package maintainer.

Now the French translation is completed on zanata.

Please add it, thanks in advance!

Regards,
David

**Comment by jonaski** [comment]
Added now. Thanks

**Comment by david-geiger** [comment]
I made some French translation fixes on zanata right now, are you informed when there are modification?

**Comment by jonaski** [comment]
No, but I have a crontab job on a machine that pulls / pushs the changes.

**Comment by stroibe974** [comment]
French translation updated today.
