### ISSUE TITLE
There are also a German Languagepack?

### ISSUE THREAD

**Issue by boospy** [jonaski/strawberry#323]
Hello all, 

and very thanks for the this really good musicplayer. Much more bugs are solved (from old Clementine). Player did'nt stuck on playing :) 

So is there a german languagepack for the player, or an option to set my language, or only english this time?

Thanks and best regards

**Comment by jonaski** [comment]
No there isn't German because it's not finished. Only 60% translated.
https://github.com/jonaski/strawberry/wiki/How-to-translate

**Comment by boospy** [comment]
Thanks for the information. Nice Weekend!
