### ISSUE TITLE
Uploading collection stuck at 0%

### ISSUE THREAD

**Issue by josephzitt** [jonaski/strawberry#324]
Since installing Version 0.6.7 from Brew on my Mac running High SIerra (currently on Version 0.6.7-4-g09ed2b9), Strawberry hasn't been updating the collection. The bottom of the window shows "Updating collection 0%..." with the spinning icon forever. Everything else works well.

**Comment by jonaski** [comment]
The collection watcher is different on macOS, it does not use functionality in Qt like Linux and Windows, but uses native system calls instead.
