### ISSUE TITLE
No alsa devices in dropdown

### ISSUE THREAD

**Issue by zewelor** [jonaski/strawberry#330]
**Describe the bug**
When installed via snap, there is no devices in backend output devices dropdown, when using ALSA directly

**To Reproduce**
Install via snap on ubuntu, Tools > Settings > Backend to select "Output to a sound card via ALSA" 

**Expected behavior**
Devices dropdown

**Screenshots:**

**System Information:**
 - Operating system: Ubuntu 19.10
 - Strawberry Version: 0.6.7

**Additional context**
Installed via snap

From dmesg:

```
audit: type=1400 audit(1577133265.157:382): apparmor="DENIED" operation="open" profile="snap.strawberry.strawberry" name="/etc/asound.conf" pid=13429 comm="strawberry" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
```

**Comment by jonaski** [comment]
Works fine here. Just tested a clean install of Ubuntu 19.10 in virtualbox. Something is blocking strawberry from accessing the alsa library directly. Did you verify that alsa is connected in snap connections?
![image](https://user-images.githubusercontent.com/10343810/71534958-a0a40a80-2902-11ea-9b85-da93e44ef894.png)

**Comment by zewelor** [comment]
I've verified that alsa was connected. I've removed /etc/asound.conf . Problaby that path is not whitelisted in ubuntu snap ? I've removed that file and now it works.
