### ISSUE TITLE
Gstreamer missing plugin for aac stream

### ISSUE THREAD

**Issue by hornetster** [jonaski/strawberry#332]
**Describe the bug**
Have only had this issue recently (2 weeks? Since a rebuild), that when trying to play an aac stream (eg in Aus, all ABC aac streams  - http://live-radio01.mediahubaustralia.com/DJDW/aac/), receive message "Your Gstreamer installation is missing a plug-in."

**To Reproduce**
Open Strawberry and attempt to play aac stream.

**Expected behavior**
Stream just plays

**Screenshots:**

**System Information:**
 Opensuse Leap 15.1 all updates applied.
Strawberry original installed version: 0.6.3-lp151.2.3.1
Have also tried version from https://www.strawberrymusicplayer.org/ : 0.6.7-1.lp151.

**Additional context**

**Comment by jonaski** [comment]
You need the gstreamer plugin for faad which is in gst-plugins-bad, I think also it should work with gstreamer-plugins-libav.

**Comment by hornetster** [comment]
As an update:
Ended up adding the Packman repo, and changing gstreamer packages to that - worked.
Thanks.
