### ISSUE TITLE
FLAC from SMB share: playback stops before end of track

### ISSUE THREAD

**Issue by tigerdognew** [jonaski/strawberry#333]
**Describe the bug**
When playing FLAC files from an SMB share, playback stops 10-15 seconds before end of track. Happens with most, if not all, FLAC playback.  Problem does not happen with MP3 playback.  Problem does not happen if same file is played from local disk instead of network share.  

**To Reproduce**
Add music from SMB shared folder.
Play FLAC file.
Music stops 10-15 seconds before end.
Playback stops.

**Expected behavior**
Song plays through to end of track, then proceeds to next track.

**Screenshots:**
![Screenshot_2019-12-26_11-31-28](https://user-images.githubusercontent.com/6300233/71488079-828bbc80-27d3-11ea-87c8-06857160726b.png)

**System Information:**
 - Operating system:  Xubuntu 19.10  Linux 5.3.0-24
 - Strawberry Version: 0.6.7

**Additional context**
May be a gstreamer issue, or gstreamer invocation issue.  Same problem exists with Clementine and some other gstreamer-frontend players, _but not all._  Problem does not happen with Parole (gstreamer based) or with Audacious or with VLC.  

Debug log:
[Strawberry-gstreamerErrorPlayingFromSMB.txt](https://github.com/jonaski/strawberry/files/4003328/Strawberry-gstreamerErrorPlayingFromSMB.txt)

**Comment by Fef0** [comment]
Can't replicate the issue.
I'm actually using Strawberry 0.6.7-7-gf2005c3 built from source on Arch Linux with an SMB shared folder and got no issues at all, everything works as intended and tracks play as they should.
Maybe you have an old version of gstreamer, try to update it

**Comment by tigerdognew** [comment]
@Fef0, what version of gstreamer and of gvfs are in your system.  The gstreamer folks indicate this may be a gvfs issue. Or maybe Arch does not use gvfs/fuse to mount smb?

**Comment by Fef0** [comment]
@tigerdognew GStreamer Core Library version 1.16.2, but I didn't use gvfs/fuse, I used cifs. 
I then mounted the remote directory into a local one by editing /etc/fstab.

**Comment by tigerdognew** [comment]
@Fef0 that explains the different behavior and confirms that we're on the right track with gvfs/fuse.  I think I will close this issue, since it's readily apparent the problem is not with Strawberry.
