### ISSUE TITLE
Translation: question about "&" symbols

### ISSUE THREAD

**Issue by Fef0** [jonaski/strawberry#336]
Hi, I've almost completed the Italian translation for Strawberry but there are a few weird words containing "&" symbol, like ```a&lbums```, ```p&lughw```, ```&Play```, and many many others...
What do I have to do? Left them as is? Or translate them, including the "&" symbol?

PS. There's an error in one of the sentences to translate, take a look here: https://translate.zanata.org/webtrans/translate?project=strawberry&iteration=master&localeId=it&locale=en-US#view:doc;doc:src/translations/translations;textflow:65516671;untranslated:show;fuzzy:show;rejected:show

**Comment by jonaski** [comment]
It's shortcuts, you can see them as underlined letters in the settings, menues, etc. ie you press the ALT key + the underlined letter.
I haven't really added those manually, it's something Qt Creator have done automatically when I've worked on the UI's, so it's a bit coincidental that some of it have them, it should probably be worked on.
You can just remove the & from the translated word, or place it where you think it's appropriate.

**Comment by Fef0** [comment]
Okay, I also edited my original message, you can see that there's an error that was automatically generated I think

**Comment by jonaski** [comment]
The HTML is not really an error, it's because the UI files have text styles, but I've moved most of it out of the UI files so there is only the macos specific ones left I think.

**Comment by Fef0** [comment]
Okay, I'll also translate that, no problem

**Comment by jonaski** [comment]
You just need to copy it over and edit the text but keep the html codes in place.

**Comment by Fef0** [comment]
Ok, finished. 
I'm closing this issue, thank you :+1:
