### ISSUE TITLE
GUI freezes when clicking it while the external drive starts up

### ISSUE THREAD

**Issue by Zobrob** [jonaski/strawberry#337]
I'm already in love with this player. Here a small bug I encountered:
**Describe the bug**
I have my music collection on an external drive with power saving enabled. So when I stop the music and leave for e.g. 20min the drive stops spinning. Now when I click on resume in the player the drive starts up again. At this moment if I close the GUI (to system tray) it freezes and I need to force close the application.

**System Information:**
Win10, Strawberry 0.6.7

**Comment by jonaski** [comment]
This is probably due to synchronous file system IO. Either Qt or gstreamer is triggering it. I'm not sure if it's fixable at all.
I think the best solution is to just turn off power save on the HDD. Spinning up and down the HDD might cause more wear than just having it running anyway.
