### ISSUE TITLE
Safeguard playlists from being nuked !

### ISSUE THREAD

**Issue by v-fox** [jonaski/strawberry#339]
**Describe the bug**

Interface of the player has impractical "clear" button that only creates danger of irrecoverably destroy playlists and "Undo" button may not be available randomly (probably, with "big" playlists, maybe with non-starred playlists) and is certainly is unavailable if player is restarted or has crashed.

**To Reproduce**
* Misclick and weep.

I just lost a playlist that I was collecting for months due to mouse misclicking while I was cleaning keyboard from some gunk and pushed it with elbow. At least, I was backing up my main "favourites" playlist periodically into a file but that one was gone.

I was able to restore older version of it by manually backing up auto-backup of the database from ~/.local/share/strawberry/strawberry/strawberry.db.bak BEFORE closing the player. After closing I replaced current, spoiled version with the old ones but it also had older versions of other playlists which I had to restore from exported copies, made beforehand.

This is not something that a user should expect from music collection manager.

**Expected behaviour**
* Not having dangerous buttons on the main interface of the player, especially near useful buttons.
* NOT having hotkeys for destructive actions such as "playlist clear".
* "Undo" button actually working all the time unconditionally.
* Auto-export saved playlists periodically, keep few copies and don't allow un-starring them ?
* Not closing issues of irrecoverable data destruction due to defective UI design. 

**System Information:**
 - Operating system: openSUSE Tumbleweed
 - Strawberry Version: 0.6.7

**Additional context**
https://github.com/jonaski/strawberry/issues/145
https://github.com/jonaski/strawberry/issues/325

**Comment by jonaski** [comment]
Adding a confirmation when there are over 500 songs:
![image](https://user-images.githubusercontent.com/10343810/71760054-b3e14800-2eb7-11ea-9ec9-176bded21337.png)
