### ISSUE TITLE
appearances: have animated icon as in clementine

### ISSUE THREAD

**Issue by alekksander** [jonaski/strawberry#34]
would it be possible to have an animated icon as it is currently in clementine? seems like a cool kids feature, but it's actually really useful. additional setting for easy customizing it would be overkill.

**Comment by jonaski** [comment]
I had it before I put the code on gitihub, but it didn't look good with the strawberry icon so I removed it.
If someone makes a better tray icon that works with the track progress I'll put it back.

**Comment by alekksander** [comment]
Thank for replying. What are Your expectations? Is classic monochrome strawberry fruit okay?

**Comment by alekksander** [comment]
there is plenty of icons to grab here:
https://www.flaticon.com/search?word=strawberry&order_by=1&color=1

if You choose one @jonaski i could make „fulfillment” for it

**Comment by jonaski** [comment]
Colors would be best

**Comment by jonaski** [comment]
I think fading to grey or a faint image could be worth a try and see how it looks.
If you want to try, the code is still there, just commented:
https://github.com/jonaski/strawberry/blob/master/src/core/systemtrayicon.cpp#L48

For fading between 2 png images you can look at the code I wrote for the Context that fades the album cover image, it's here:
https://github.com/jonaski/strawberry/blob/master/src/context/contextview.cpp

Another option would be to find someone who could create a new vector image to use in the system tray icon that could be a sliced strawberry or something so that is is more round.

**Comment by jonaski** [comment]
I'm also open for the underline thing you suggest.

**Comment by alekksander** [comment]
my skilled friend promised to sit down to it during his free time. hopefully there will be a commit or ready png to criticize soon.

**Comment by alekksander** [comment]
i'm experimenting with kde plasma icon set for strawberry. if i complete it (currently struggling with time and proper svg conversion) would You be willing to include it in official strawberry repo as an alternative icon set for plasma users, or should i rather keep it as private fork?

**Comment by jonaski** [comment]
Maybe, but I'd like to see it first :)

**Comment by jonaski** [comment]
I think I prefer the one we got already, but thanks for the effort anyway.
Maybe create an alternative fading progress on the current icon would be sufficient.

**Comment by alekksander** [comment]
![image](https://user-images.githubusercontent.com/3148302/52655258-10c8be00-2ef4-11e9-9649-284f21e652c8.png)
![image](https://user-images.githubusercontent.com/3148302/52655541-ab290180-2ef4-11e9-9fac-af0b2a250e0c.png)

work for breeze icon set is progressing, but i still need way more time

**Comment by jonaski** [comment]
I've added support for custom icons. https://github.com/jonaski/strawberry/commit/d575ab0b2b260e91ef813a6a622f54bb3c2999f1
You can place icons in ~/.local/share/strawberry/strawberry/icons
Subfolders there should be 22, 32, 48 and 64. And using the same names as the icons in https://github.com/jonaski/strawberry/tree/master/data/icons it should load them instead.

We can get back to creating the animated icon in the tray later.

**Comment by alekksander** [comment]
@jonaski how to use this piece before compiling:
https://github.com/jonaski/strawberry/blob/master/src/core/systemtrayicon.cpp#L48 ?

**Comment by jonaski** [comment]
Remove the // before the 3 lines here: https://github.com/jonaski/strawberry/blob/master/src/core/systemtrayicon.cpp#L70
