### ISSUE TITLE
Scrobbler does not work for LastFm

### ISSUE THREAD

**Issue by petihegyi** [jonaski/strawberry#341]
I am using strawberry 0.6.8 on Arch Linux. Everything is set up to scrobble to lastfm correctly (I am logged in, and scrobbling is enabled), but the scrobbles still not arrive on my lastfm page. When I start strawberry from the terminal, the debug messages say that both the "now playing" and the scrobble events are sent correctly, none of them appear on my lastfm profile.

 - Operating system: Arch Linux
 - Strawberry Version: 0.6.8

I have tried both the package from the official Arch repos (`strawberry`) and the AUR (`strawberry-git`). Both behaved the same.

**Comment by jonaski** [comment]
Are you sure the "work in offline mode" is off?

**Comment by petihegyi** [comment]
That did the trick. Sorry for the obvious issue, I misunderstood something. Thanks for the quick reply!

**Comment by Hawkhobo** [comment]
Thought this would be a good issue to add this: for other folks having problems with scrobbling on an Arch Linux build, in `~/.config/strawberry/strawberry.conf`, under the `[LastFM]` section header, `enable` may be set to `false`. Checking `Enable` for scrobbling in the software settings was not overwriting this value for me. Editing the config file fixed it!
