### ISSUE TITLE
Snap crashes under Wayland on Eoan

### ISSUE THREAD

**Issue by monochromec** [jonaski/strawberry#344]
**Describe the bug**

When executed as a snap, the application dies with the following error message: 

6:06:17.469 INFO  main:154                         Strawberry 0.6.8
16:06:17.469 INFO  main:155                         "Ubuntu Core 18 18 - (linux 5.3.0-26-generic) [x86_64]"
__logging_message__16:06:17.470 ERROR unknown                          This application failed to start because it could not find or load the Qt platform plugin "wayland-egl"
__logging_message__16:06:17.470 ERROR unknown                          in "".
__logging_message__16:06:17.470 ERROR unknown                          
__logging_message__16:06:17.470 ERROR unknown                          Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.
__logging_message__16:06:17.470 ERROR unknown                          
__logging_message__16:06:17.470 ERROR unknown                          Reinstalling the application may fix this problem.
Aborted (core dumped)

Reinstalling the snap *doesn't* solve the problem. :-)

**To Reproduce**

1) Install the snap
2) Run strawberry from the command line.

**Expected behavior**
UI should open.

**Screenshots:**

**System Information:**
 - Operating system: Stock Eoan
 - Strawberry Version: Stable from repo: 0.6.8+git

**Additional context**

Perhaps this is related: https://forum.snapcraft.io/t/problem-launching-qt-snaps-in-wayland/7055 ?

More info needed? Just get in touch.

**Comment by jonaski** [comment]
Did you try to install qtwayland5 through snap like the article says?

**Comment by monochromec** [comment]
Not sure how do this as the link seems to relate to a packaging issue when building the snap (there is no package called qtwayland5).

**Comment by jonaski** [comment]
`snap install qtwayland5`

**Comment by jonaski** [comment]
I already added it as a dependency in the snap so if you update snap it should probably work.

**Comment by monochromec** [comment]
snap install qtwayland5

results in:

error: snap "qtwayland5" not found
