### ISSUE TITLE
No Tidal support on OpenBSD?

### ISSUE THREAD

**Issue by jocap** [jonaski/strawberry#35]
Hi!

I just spent quite a while compiling Strawberry using the OpenBSD port linked on strawbs.org, but I'm not finding any Tidal or Deezer settings?

The settings screen looks like this:

![settings](https://user-images.githubusercontent.com/92702/50250517-ef0df780-03d8-11e9-9367-5a97598aa07f.png)

Best regards,
John

**Comment by jocap** [comment]
Thank you! That worked. Maybe a disclaimer could be added to https://strawbs.org/?

**Comment by jonaski** [comment]
If you send me the updated files I can update the port.
