### ISSUE TITLE
Portable app on Windows

### ISSUE THREAD

**Issue by Superpiffer** [jonaski/strawberry#350]
I would like to use Strawberry on my work pc but I don't have administrator rights so I can't install it. Is it possible to use it as a portable app? Or maybe install it in a different folder without administrator rights? 
Thanks.

**Comment by jonaski** [comment]
You can install it on another computer with administrator permissons, then you can just copy the C:\Program Files\Strawberry Music Player, all the files needed to run are in that folder and it should to place that directly in your user profile too.

**Comment by Superpiffer** [comment]
Ok, no problem. Instead of installing on another pc, I decompress the exe file with 7-Zip and it works normally. Thanks anyway!
