### ISSUE TITLE
Alsa backend device reference change every reboot

### ISSUE THREAD

**Issue by Ealrann** [jonaski/strawberry#351]
First, thank you very much for strawberry. Finally a good audiophile music player on linux.

Well, I guess there is a linux solution to this problem, but I have to admit: I never really understood/trusted the alsa configuration files. So I tend to prefer to configure the front end software (strawberry).

**Is your feature request related to a problem? Please describe.**
When I reboot my computer, the device address of my (usb) backend change (hw:2,0 <-> hw:1,0). So I have to re-set it in the settings.

**Describe the solution you'd like**
Since I use my laptop at different locations, with different devices, the best solution for me would be: 
the capability to rank the devices to use, by name. Then, strawberry would use the most ranked device which is available.

**Describe alternatives you've considered**
Simply remember the name of the last used devices (rather than the location), and pick one randomly.

**Comment by jonaski** [comment]
You need set index in modprobe for the card, there is some documentation here:
https://wiki.archlinux.org/index.php/Advanced_Linux_Sound_Architecture
