### ISSUE TITLE
Song rating capability

### ISSUE THREAD

**Issue by Ealrann** [jonaski/strawberry#352]
I was used to rate my songs to generate playlists. I would love to be able to do it in Strawberry :D. I have no need of something graphic (but I guess it would be better?), simply editing the raw variable would be enough.

FMPS_RATING looks like to be the standard/most common tag for rating, but I don't mind if you use another one (I can convert my songs). My only request is to be able to store it directly in the song tags (and not in a database).

**Comment by jonaski** [comment]
There already is an issue for this https://github.com/jonaski/strawberry/issues/259
