### ISSUE TITLE
Store new album covers inside the MP3

### ISSUE THREAD

**Issue by DJDiaper** [jonaski/strawberry#356]
Hey all,

I would like to request if it's possible to store the album cover fetched via the cover manager in the MP3 itself. As a DJ I have to open the songs in different software as well and there the covers aren't updated. Thanks in advance for adding this, or showing me the sollution

**Comment by jonaski** [comment]
It's called embedded cover art, there is already an issue for it: https://github.com/jonaski/strawberry/issues/286
