### ISSUE TITLE
cannot build

### ISSUE THREAD

**Issue by alekksander** [jonaski/strawberry#36]
what i get is:

`[ 22%] Building CXX object src/CMakeFiles/strawberry_lib.dir/playlist/playlisttabbar.cpp.o

[ 22%] Building CXX object src/CMakeFiles/strawberry_lib.dir/playlist/playlistundocommands.cpp.o
/home/aleksander/strawberry/src/context/contextalbumsview.cpp: In member function 'virtual void 
ContextAlbumsView::contextMenuEvent(QContextMenuEvent*)':
/home/aleksander/strawberry/src/context/contextalbumsview.cpp:408:14: error: unused variable 'regular_elements_only' [-Werror=unused-variable]
   const bool regular_elements_only = songs_selected == regular_elements && regular_elements > 0;
              ^~~~~~~~~~~~~~~~~~~~~
[ 22%] Building CXX object src/CMakeFiles/strawberry_lib.dir/playlist/playlistview.cpp.o
[ 22%] Building CXX object src/CMakeFiles/strawberry_lib.dir/playlist/songloaderinserter.cpp.o
cc1plus: all warnings being treated as errors
src/CMakeFiles/strawberry_lib.dir/build.make:2677: recipe for target 'src/CMakeFiles/strawberry_lib.dir/context/contextalbumsview.cpp.o' failed
make[2]: *** [src/CMakeFiles/strawberry_lib.dir/context/contextalbumsview.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:438: recipe for target 'src/CMakeFiles/strawberry_lib.dir/all' failed
make[1]: *** [src/CMakeFiles/strawberry_lib.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
`

any ideas?

**Comment by jonaski** [comment]
Looks like compiling without gstreamer was broken. Fixed now in https://github.com/jonaski/strawberry/commit/517285085a0ed5bbc0fbd5f9be9857d34ced54dc
