### ISSUE TITLE
sidebar bugs

### ISSUE THREAD

**Issue by alekksander** [jonaski/strawberry#37]
i've discovered two bugs with the „sidebar”. 
https://i.imgur.com/dMr3lt9.png
1. titles have unnecessary signs in it
2. selecting icons on top won't be remembered upon application restart

this is (pre-compiled) version 0.4.2-12-g1706ba5 running on ubuntu based system.

**Comment by alekksander** [comment]
typing:
`kwriteconfig5 --file kdeglobals --group Development --key AutoCheckAccelerators "false"`
fixed redundant „&” signs 

i've just tried minimizing to taskbar & minimizing to tray few times. afterwards i shut app from it's menu. that didn't help to save preferred tabs view. 

okay, i will pull and build from source once it's ready and report for changes and eventual further bugs. 

Thanks!

**Comment by jonaski** [comment]
Reopen if this not fixed in https://github.com/jonaski/strawberry/commit/0d7e12e781f565d3ce227859d3a5232217577e76
