### ISSUE TITLE
strawberry crashes on wayland session

### ISSUE THREAD

**Issue by alekksander** [jonaski/strawberry#42]
i don't have the knowledge to judge whether it's strawberry, qt, or wayland issue.

 here is output from terminal:

`aleksander@B75TN:~$ strawberry
12:39:13.166 INFO  main:154                         Strawberry 0.4.2
12:39:13.284 DEBUG NetworkProxyFactory:55           Detected system proxy URLs: ("", "", "", "")
12:39:13.289 DEBUG WorkerPool<HandlerType>:277      Starting worker 0x7f4df25b7420 "/usr/local/bin/strawberry-tagreader" "/tmp/strawberry_46862655"
12:39:13.291 DEBUG WorkerPool<HandlerType>:277      Starting worker 0x7f4df25b7420 "/usr/local/bin/strawberry-tagreader" "/tmp/strawberry_136968786"
12:39:13.305 INFO  main:54                          TagReader worker connecting to "/tmp/strawberry_46862655"
12:39:13.306 DEBUG WorkerPool<HandlerType>:295      Worker 0x7f4ddc0064f0 connected to "/tmp/strawberry_46862655"
12:39:13.305 INFO  main:54                          TagReader worker connecting to "/tmp/strawberry_136968786"
12:39:13.306 DEBUG WorkerPool<HandlerType>:295      Worker 0x7f4ddc007b70 connected to "/tmp/strawberry_136968786"
__logging_message__12:39:13.397 WARN  unknown                          Icon theme "Papirus-Dark" not found.
__logging_message__12:39:13.398 WARN  unknown                          Icon theme "gnome" not found.
12:39:13.429 DEBUG QxtGlobalShortcutBackend:39      registering
__logging_message__12:39:13.430 WARN  unknown                          QSocketNotifier: Invalid socket 33 and type 'Read', disabling...
__logging_message__12:39:13.430 WARN  unknown                          QSocketNotifier: Invalid socket 28 and type 'Read', disabling...
__logging_message__12:39:13.431 WARN  unknown                          QSocketNotifier: Invalid socket 22 and type 'Read', disabling...
12:39:13.435 ERROR Database:571                     db error:  QSqlError("10", "Unable to fetch row", "disk I/O error")
12:39:13.435 ERROR Database:572                     faulty query:  "select COUNT(distinct artist) from songs WHERE unavailable = 0"
12:39:13.435 ERROR Database:573                     bound values:  QMap()
12:39:13.436 ERROR Database:571                     db error:  QSqlError("10", "Unable to fetch row", "disk I/O error")
12:39:13.436 ERROR Database:572                     faulty query:  "select COUNT(distinct album) from songs WHERE unavailable = 0"
12:39:13.436 ERROR Database:573                     bound values:  QMap()
12:39:13.436 ERROR Database:571                     db error:  QSqlError("10", "Unable to fetch row", "disk I/O error")
12:39:13.436 ERROR Database:572                     faulty query:  "SELECT ROWID, path FROM directories"
12:39:13.436 ERROR Database:573                     bound values:  QMap()
KCrash: crashing... crashRecursionCounter = 2
KCrash: Application Name = strawberry path = /usr/local/bin pid = 7149
KCrash: Arguments: /usr/local/bin/strawberry 
KCrash: Attempting to start /usr/lib/x86_64-linux-gnu/libexec/drkonqi from kdeinit
sock_file=/run/user/1000/kdeinit5__1

[1]+  Stopped                 strawberry
aleksander@B75TN:~$ __logging_message__12:39:46.855 WARN  unknown                          QSocketNotifier: Invalid socket 7 and type 'Read', disabling...
__logging_message__12:39:46.855 WARN  unknown                          QSocketNotifier: Invalid socket 15 and type 'Read', disabling...
__logging_message__12:39:46.862 WARN  unknown                          QSocketNotifier: Invalid socket 17 and type 'Read', disabling...`

**Comment by jonaski** [comment]
Looks like database corruption, and possible disk failure.
There error is this: QSqlError("10", "Unable to fetch row", "disk I/O error")

**Comment by jonaski** [comment]
If the database works on another machine, it may be the version of sqlite or qt sqlite plugin perhaps?

**Comment by alekksander** [comment]
same system, same hardware only difference is display server

**Comment by jonaski** [comment]
Do:
```
cd ~/.local/share/strawberry/strawberry/
sqlite3 strawberry.db
SELECT ROWID, path FROM directories;

```
Does that work?

**Comment by alekksander** [comment]
it lists paths to my collection properly and afterward:
`sqlite> __logging_message__13:16:46.885 WARN  unknown                          QSocketNotifier: Invalid socket 7 and type 'Read', disabling...
__logging_message__13:16:46.885 WARN  unknown                          QSocketNotifier: Invalid socket 15 and type 'Read', disabling...

`

**Comment by jonaski** [comment]
The log errors are not related, they probably something that just got delayed from when you started strawberry.
At least that confirms the DB and sqlite is fine. It may be related to the QSocketNotifier error.
