### ISSUE TITLE
Monkey's Audio support

### ISSUE THREAD

**Issue by alekksander** [jonaski/strawberry#45]
strawberry is not properly reading .ape files i've tried in other players and there is no problem with finding track timing and titles. what strawberry sees for:

https://paste.ubuntu.com/p/XDsNfyQxXQ/

is:

![image](https://user-images.githubusercontent.com/3148302/50727209-0c043380-1118-11e9-8fb5-d0015da3b35a.png)

**Comment by jonaski** [comment]
APE tags are supported, but not monkey audio files, should be use to implement since it seem to be supported in taglib.
Could you send me a couple of files I can test with?

**Comment by alekksander** [comment]
https://www.dropbox.com/s/vp2cneh1t1j80to/CD01.tar?dl=1

**Comment by jonaski** [comment]
Thanks. Fixing it now.

**Comment by jonaski** [comment]
Fixed in https://github.com/jonaski/strawberry/commit/a11f43520ed65423e8d066d9859250dfeba17f30

![image](https://user-images.githubusercontent.com/10343810/50730332-3c18fa00-114b-11e9-8683-090bfdc5479d.png)

**Comment by alekksander** [comment]
Thank You!
