### ISSUE TITLE
[BUG][TIDAL] can't pause while buffering

### ISSUE THREAD

**Issue by rijnhard** [jonaski/strawberry#53]
if the song is buffering and you try to pause it just won't, the play icon doesn't toggle at all.

**Comment by jonaski** [comment]
Can't reproduce. What engine do you use?

**Comment by rijnhard** [comment]
Sorry for the delay, Gstreamer

**Comment by userofryzen** [comment]
@jonaski Maybe it's not the better place to post this but..
I have this problem too in addition to another one that is:
when you are over a slow( or bad/unstably) connection strawberry ( at least with tidal) fails sometimes to buffer in the meaning that time over time, sometimes 1, sometimes 4 times each song the app keeps that way eternally
![image](https://user-images.githubusercontent.com/33232977/181507019-c515ccce-be2c-4041-a7f4-4e39738417cd.png)

on the other hand you can stop (not pause) and play aganin yourself and the song is gonna get buffered. Or to change the song too. 

It's like strawberry with bad connections fails to send to server the "send me more info" and if it fails it won't try again itself so you have to stop and resume manually..
For example, right now I have this problem, strawberry can be buffering at 0 percent like hours wihout doing nothing but if I press stop, change song, or by the way select another time on the progress bar( I mean in advance or the inverse) the song starts to buffer again.. until strawberry fails again and keep buffering at 0 percent.


Maybe putting in strawberry a code that retrys to download that part of the song if it's buffering at 0 much time is neeeded. I'll keep connected to that issue if you want to tell me someting

**Comment by userofryzen** [comment]
I have selected 5 second less of the song and right now is playing after buffer like in 1 second.. so I think it can be a bug because another apps tryes to download at slow connection circunstances and strawberry not

**Comment by userofryzen** [comment]
the connection I'm using is bluetooth by the way, I think you can reproduce my situation easily sharing internet with your phone
