### ISSUE TITLE
Resume only works for playlist number 1

### ISSUE THREAD

**Issue by TheHarveyBirdman** [jonaski/strawberry#55]
Seems strawberry only remembers track position (resume playback position after closing strawberry) for a given file if its in your collection. If for example you download a podcast and add it to a playlist regardless of if the playlist is saved or not, it will not remember playback time / position.

If its feasible It would be nice if I didn't have to add files I will only listen to once, to strawberry's database / collection in order to take advantage of this feature.

Thank you.

EDIT:
Upon further testing it appears playback will resume but only on the default playback queue / playlist not additional playlists you create. This isn't an issue for me if I have to do it that way, feel free to close.

**Comment by alekksander** [comment]
if i may add my two cents… „Show in file browser…” is also only available if file is indexed in collection. this isn't crucial to have since „Edit track information…” is showing file path and we can copy/paste it, but still would be a nice touch.

**Comment by jonaski** [comment]
That does not make sense. The resume feature does not depend on the collection at all. In fact the playlist items stored the same song data that is in the collection, so when you add something from the collection it stores it as well in the playlists.
All that that I can think of, is that it has something to do with the file format, or the path where you add it from.

**Comment by jonaski** [comment]
OK. I saw your edit now

**Comment by jonaski** [comment]
The signal for resuming playback on startup is sent when the first playlist is loaded, so if the song to resume is in another playlist that isn't loaded yet. Working on a fix to this.

**Comment by jonaski** [comment]
Fixed https://github.com/jonaski/strawberry/commit/ca140388d927dcab8ca622fb21aa5400b8dce3ac
