### ISSUE TITLE
Native Icon Theme Support

### ISSUE THREAD

**Issue by Korvox** [jonaski/strawberry#56]
Its something Clementine has that Strawberry seems to have removed.
On the same topic, it should probably be the default on Linux to inherit the system icon theme all the time and just use the qt4 / kde4 icon bundle Clementine had on Windows and OSX.

**Comment by jonaski** [comment]
The system icon themes don't have suitable alternatives for like the vinyl I got.
Also it won't work for the tab bar and for the settings. Just a few menus.
We would have to test it with different icon themes, on different desktops to see how it looks.
It's a lot of work for little gain, I can't prioritize it now I'm afraid. Maybe later.
Also the use system theme in Clementine don't work very well in my opinion, some icons from the system icons are too small, it does not look good, there is no check for required size
