### ISSUE TITLE
[macOS]Cant play music

### ISSUE THREAD

**Issue by hype3** [jonaski/strawberry#58]
macOS 10.14.2

When I click on a music file: Your GStreamer installation is missing a plugin-in.
Strawberry does only have support for GStreamer backend for now?
On Clementine I don't have to choose any backend at all. It just works is this something that can be done in future updates?

**Comment by jonaski** [comment]
If you compiled from source you need to install gstreamer plugins too.
If you used the development builds, you need to copy the folder to /Applications

**Comment by hype3** [comment]
I used the development builds you have built. I moved Strawberry to Applications.

**Comment by hype3** [comment]
It's a 320 kbps MP3 file... If you need more info just ask.

**Comment by jonaski** [comment]
Looks like the lame plugin isn't included, so it's not strange that it didn't play mp3. Fixing it now.

**Comment by jonaski** [comment]
Should be fixed in 22c476d
So try the latest build 0.5.1.9.g22c476d

**Comment by hype3** [comment]
I tested 0.5.1.10.gb35c641 and now it works! Thank you.

**Comment by jonaski** [comment]
That's strange.
I'm afraid someone else needs to look at that as it works on linux, and I don't have a mac, I just borrowed one for a short while to make it build and run.

**Comment by hype3** [comment]
It works sometimes after a lot of clicking it moves where I clicks. I could also grab it and move it around but something feels strange. Works as normal on Clementine qt4 is there some builds of clementine qt5 version somewhere? Maybe its the same on that one so I can test.
