### ISSUE TITLE
Backport live scanning from vranki's Clementine fork

### ISSUE THREAD

**Issue by vranki** [jonaski/strawberry#60]
My fork has some improvements never taken into official Clementine.

Most important is live scanning. It adds scanned albums to library during the scan, 
instead of waiting until scan has finished.

https://github.com/vranki/clementine

It's probably easy to cherry-pick the relevant git commits.

(Strawberry has been scanning my collection for 3 working days now and is at 98%, library still empty).

**Comment by jonaski** [comment]
I will certainly look into it, like I said in my e-mails.
But the time it takes to scan is not the main issue, I got over 15500 songs and it finished in a few seconds. If it takes several days there is obviously something more wrong with some of your files or you system.
The main issue with the collection (library) watcher in my opinion is file tracking and updating the tag changes to the DB, which there have been different proposals to Clementine to solve.

**Comment by jonaski** [comment]
I've added your changes with some modifications to it's own branch for testing: https://github.com/jonaski/strawberry/tree/livescanning
First impression is good, but it does not follow the correct grouping in the model during updating of the songs.

**Comment by jonaski** [comment]
My bad, it's not the grouping, it was just various artists songs.

**Comment by jonaski** [comment]
Added #199 

@vranki I think it should be possible to also improve the updating if we calculate compilations per directory, since it's updated per directory that makes sense now. That would fix the updating to show various artists songs correctly immediately.

**Comment by jonaski** [comment]
@vranki Your fork has a problem in the watcher. New dirs aren't watched, because they are cleared here:  https://github.com/vranki/Clementine/blob/master/src/library/librarywatcher.cpp#L149 so they never gets watched, because thats done here: https://github.com/vranki/Clementine/blob/master/src/library/librarywatcher.cpp#L121
