### ISSUE TITLE
Localizations packs

### ISSUE THREAD

**Issue by pavbaranov** [jonaski/strawberry#64]
First of all - thanks for your job!
Can you consider to add localizations packs/template or something like this, to strawberry? I can help to translate into Polish.

**Comment by jonaski** [comment]
If more contributors join this might be added, but right now it is too much work to maintain.
It also requires a service where people can edit translations.
Clementine uses Transifex, but it is not a free service.

**Comment by jonaski** [comment]
@pavbaranov 
I've added support for translations now
If you want to help translate, see:
https://github.com/jonaski/strawberry/wiki/How-to-translate
