### ISSUE TITLE
No DSD playback

### ISSUE THREAD

**Issue by pfelipm** [jonaski/strawberry#66]
First of all, congratulations for this great player!

DSF / DSDIFF playback does not seem to be working right now (using 0.5.2 but also tried with some binaries under 0.5.1). Using Gstreamer backend in Ubuntu 18.04. Files are indexed and DSD format is correctly identified but do not play:

![seleccion_630](https://user-images.githubusercontent.com/12829262/51799071-dcc77a80-221c-11e9-98e3-202247558bfa.png)

I've tried with my own SACD rips and also with free samples downloaded from here:

http://www.2l.no/hires/

Thanks!

---
By the way, not many people seem to know about this little gem, I've published a small [review](https://www.audioplanet.biz/t101634-strawberry-mini-analisis-tidal-en-bitperfect-en-linux-y-mas-cosas) in Audio Planet (a Spanish audio forum).

**Comment by jonaski** [comment]
You need GStreamer 1.15.1 with libav of the same version

**Comment by pfelipm** [comment]
Thanks, I am currently using 1.14.1. Will try to update.

**Comment by jonaski** [comment]
It's released but it is a development version, so it may not be available on distros yet, but there may be a repository that has it.
https://github.com/GStreamer/gstreamer/blob/master/RELEASE
