### ISSUE TITLE
No Deezer support 

### ISSUE THREAD

**Issue by pfelipm** [jonaski/strawberry#67]
In my setup (Ubuntu 18.04, Strawberry 0.5.2 build) Deezer menu options do not appear:

![seleccion_631](https://user-images.githubusercontent.com/12829262/51799182-c28e9c00-221e-11e9-836a-afe859ab962d.png)

Thanks and best regards!

**Comment by jonaski** [comment]
It is explained in #21
It is hard to compile with deezer support on linux, deezer needs to fix their library.
