### ISSUE TITLE
Albums with cue sheet and single audio file show and play as one song

### ISSUE THREAD

**Issue by pfelipm** [jonaski/strawberry#68]
...for instance, this one:

![seleccion_633](https://user-images.githubusercontent.com/12829262/51799295-249bd100-2220-11e9-8369-45b2d6cc2892.png)

Album is playable, but only one song appears and you can't move between songs. Is this the expected behaviour?

Thanks and best regards.

**Comment by jonaski** [comment]
No, its not expected behavior. I use almost entirely flac, but I dont use cue, I will do some testing when I get the time

**Comment by jonaski** [comment]
I ripped a CD to flac cue using k3b. It lists it as individual tracks.
Try changing WAVE to FLAC at the end of FILE in the cue file.

**Comment by pfelipm** [comment]
I've changed WAVE > FLAC inside the cuesheet and done a full rescan. Now it works as expected, thanks.

Anyway, WAVE as a filetype should work, shouldn't it?  In fact, according to cue specs WAVE should be the right type for flacs, if I am not wrong.

**Comment by jonaski** [comment]
I'm not sure. I will look into it.
The CD I ripped has FLAC at the end of FILE.
Here is the cue file:

```
REM Cue file written by K3b 18.12.1

PERFORMER "Jethro Tull"
TITLE "Too Old To Rock 'N' Roll CD1"
FILE "Jethro Tull - Too Old To Rock 'N' Roll CD1.flac" FLAC
  TRACK 01 AUDIO
    PERFORMER "Jethro Tull"
    TITLE "Prelude"
    INDEX 01 00:00:00
  TRACK 02 AUDIO
    PERFORMER "Jethro Tull"
    TITLE "Quiz Kid"
    INDEX 01 00:53:32
  TRACK 03 AUDIO
    PERFORMER "Jethro Tull"
    TITLE "Crazed Institution"
    INDEX 01 04:56:72
  TRACK 04 AUDIO
    PERFORMER "Jethro Tull"
    TITLE "Salamander"
    INDEX 01 09:32:70
  TRACK 05 AUDIO
    PERFORMER "Jethro Tull"
    TITLE "Taxi Grab"
    INDEX 01 12:25:51
  TRACK 06 AUDIO
    PERFORMER "Jethro Tull"
    TITLE "From A Dead Beat To An Old Greaser"
    INDEX 01 16:16:41
  TRACK 07 AUDIO
    PERFORMER "Jethro Tull"
    TITLE "Bad Eyed And Loveless"
    INDEX 01 20:28:17
  TRACK 08 AUDIO
    PERFORMER "Jethro Tull"
    TITLE "Big Dipper"
    INDEX 01 22:39:02
  TRACK 09 AUDIO
    PERFORMER "Jethro Tull"
    TITLE "Too Old To Rock ?n? Roll: Too Young To Die!"
    INDEX 01 26:12:13
  TRACK 10 AUDIO
    PERFORMER "Jethro Tull"
    TITLE "Pied Piper"
    INDEX 01 31:46:15
  TRACK 11 AUDIO
    PERFORMER "Jethro Tull"
    TITLE "The Chequered Flag (Dead Or Alive)"
    INDEX 01 36:22:71
  TRACK 12 AUDIO
    PERFORMER "Jethro Tull"
    TITLE "From A Dead Beat To An Old Greaser"
    INDEX 01 41:46:20
  TRACK 13 AUDIO
    PERFORMER "Jethro Tull"
    TITLE "Bad Eyed And Loveless"
    INDEX 01 45:56:06
  TRACK 14 AUDIO
    PERFORMER "Jethro Tull"
    TITLE "Big Dipper"
    INDEX 01 48:08:24
  TRACK 15 AUDIO
    PERFORMER "Jethro Tull"
    TITLE "Too Old To Rock ?n? Roll: Too Young To Die!"
    INDEX 01 51:44:46
  TRACK 16 AUDIO
    PERFORMER "Jethro Tull"
    TITLE "The Chequered Flag (Dead Or Alive)"
    INDEX 01 57:27:72

```

**Comment by jonaski** [comment]
Tried to change my cue to WAVE, and it still works, and I checked the sourcecode and it makes no use of the file type.
So I think it might have been the rescan and fixed it for you.

**Comment by pfelipm** [comment]
I've just checked other albums with cue sheets and their tracks are correctly identified and displayed now with no cue sheet file edit whatsoever. It is a little bit odd, but as you suggest, it might have been an initially faulty scan ¿?.
