### ISSUE TITLE
[ALSA] Allow fade out again

### ISSUE THREAD

**Issue by mroova** [jonaski/strawberry#70]
Hello :)

I'm aware of this:
#48 

It's true that cross fade doesn't make any sense as it breaks playback.
Still, could You consider allowing "fade out when stopping a track" and "fade out on pause / fade in on resume"? These options don't break playback, and help to make stopping or pausing music much less abrupt, at least IMHO :)

All the best :)

**Comment by jonaski** [comment]
I think that's the reason why I initially didn't disable the fading.
But it still breaks if you immediately play again after stopping, so I don't think I want to do that.
