### ISSUE TITLE
Could not compile on MacOS

### ISSUE THREAD

**Issue by achere** [jonaski/strawberry#71]
When I'm running make -j8 on MacOS Mojave, it is giving me error
`ld: library not found for -lchromaprint`
I have installed chromaprint along with other dependencies
`Warning: chromaprint 1.4.3 is already installed and up-to-date`
I couldn't google this issue, so opening here. Any suggestions?

**Comment by jonaski** [comment]
Just do: export LIBRARY_PATH=/usr/local/lib
Then make again
