### ISSUE TITLE
Subsonic support?

### ISSUE THREAD

**Issue by rogerizo** [jonaski/strawberry#72]
Hi are you planning on adding subsonic support?

Thanks

**Comment by jonaski** [comment]
Not sure. Will think about it.

**Comment by birdkiwi** [comment]
Waiting for this feature! Clementine still works, but UI sucks on HiDPI.

**Comment by jonaski** [comment]
Added Subsonic support now: https://github.com/jonaski/strawberry/commit/7b54cef23b9163638069ee045c1fb512c52ed14b
