### ISSUE TITLE
Use cover artwork as translucent background for main panel/playlist

### ISSUE THREAD

**Issue by sylvainsab** [jonaski/strawberry#74]
This is something I've always wanted to see in Clementine but did not have time to push, and it feels close to what the now defunct and once great Amarok would have implemented.

I would love to have the cover art for the current playing track/album displayed as the main panel/playlist background image. This would only need a few settings regarding where/how to locate cover pictures (mine are in album folder named after %artist - %album.jpg) and desired transparency level.

Perhaps also it could be enhanced to display cover art pictures for each album's total tracks following eachother in a playlist, i.e. for instance if my playlist consists of three albums in a row, have all three covers take up each the space of their corresponding tracks, no more no less. This sounds a bit more hazardous. Just an idea.

In any case, many thanks for keeping this software going - whether it's named Clementine or anything else. Amarok was actually one of the main reasons I was coming back to KDE and I was disappointed to see it had lost its place as a main component of the software suite. (note : it seems it is back now after an update has been published in march 18 ? weird)

**Comment by sylvainsab** [comment]
Dropped the suggestion to Amarok's developping team : https://bugs.kde.org/show_bug.cgi?id=404126

**Comment by jonaski** [comment]
We already got this, here:
![image](https://user-images.githubusercontent.com/10343810/52518858-d6d88d00-2c51-11e9-94d7-df7d0657abf7.png)

**Comment by sylvainsab** [comment]
Great ! I didn't see it at first.

I've got a lot of minor issues I could adress, but I'm going to keep it major for now.

May I help by translating the interface & menus in my language - French ?

**Comment by sylvainsab** [comment]
On that note, I am not a fan of the current (dynamic) cover artwork being displayed under my (all-time) static collection. Especially when it is redundant with that feature.

I reopened this instead of a new issue, but also I'm listening to a track that for some reason has a very large (multiple performers) 'artists' tag and this shows up in the excessive use of space there, rendering library browsing uncomfortable.

**Comment by jonaski** [comment]
I added an option to disable the playing widget.
https://github.com/jonaski/strawberry/commit/c0fb35f6b9e81b00d98f13733fb945b1d4d1fe5e

**Comment by jonaski** [comment]
@sylvainsab 
I've made some huge improvements to the custom / album cover background and added quite a few settings for displaying the background image in different ways. The way it was before was pretty ugly in my opinion so I never used the setting.
You can now select where the album cover is positioned, the max size, and options for stretching it to fit the entire playlist background without cutting the cover on top and bottom.

![image](https://user-images.githubusercontent.com/10343810/54958800-5054e200-4f57-11e9-8f28-5b3a90f089b4.png)
