### ISSUE TITLE
Can't set Alt+Shift+Enter as a shortcut (for stopping after current track)

### ISSUE THREAD

**Issue by sylvainsab** [jonaski/strawberry#75]
Alt+Shift+Enter is the default global shortcut I use for "stop after current track." I cannot set it in Strawberry however, but another shortcut works.

Setting this shortcut in Kate works fine, so it seems related to Strawberry.

**Comment by jonaski** [comment]
Fixed https://github.com/jonaski/strawberry/commit/676f8dc8be5c80d4808c6bb1d60be26899e092f0
