### ISSUE TITLE
tray tooltip is not displayed properly [kde]

### ISSUE THREAD

**Issue by alekksander** [jonaski/strawberry#77]
strawberry tray tooltip has miss–arranged  text:
![image](https://user-images.githubusercontent.com/3148302/52522260-25eae600-2c83-11e9-9579-f55dc53c3102.png)
![image](https://user-images.githubusercontent.com/3148302/52522373-d4dbf180-2c84-11e9-9159-22f415fd1c97.png)
 (please don't mind green icon, i'm still in process of experimenting with theming)

i remember it used to be the case with clementine as well. can anyone confirm?

**Comment by jonaski** [comment]
Works for me on XFCE.
A KDE specific problem most likely.
It has the newlines in the wrong place.
Maybe the problem is here somewhere:
https://github.com/jonaski/strawberry/blob/master/src/widgets/osd.cpp#L321

**Comment by alekksander** [comment]
how about:
https://github.com/jonaski/strawberry/blob/master/data/misc/playing_tooltip.txt

**Comment by jonaski** [comment]
You are right. The code that sets the tooltip is here:
https://github.com/jonaski/strawberry/blob/master/src/core/qtsystemtrayicon.cpp#L221

Maybe KDE does not like html tables.

**Comment by jonaski** [comment]
I tried changing the table tag to use border="1", but no borders shows up, so it means it ignores the table tags completely, but it loads the image and thats a img tag.

**Comment by jonaski** [comment]
I've created a simple workaround for KDE.
Showing the tooltip with simple newlines instead of a table.
I tested to use stylesheet, but that did not work at all.
https://github.com/jonaski/strawberry/commit/d3b3c309fa9f7bafda0a9b13b82aab90dbc5f52d

The systray icon is probably redundant anyway on KDE, since there is a player icon that shows both the album cover and song retrieved through MPRIS.

**Comment by jonaski** [comment]
I'm open to removing the tooltip on KDE

**Comment by alekksander** [comment]
i've been thinking about it and „testing” usage without it and the only loss seem to be a loss of a habit. personally i'm good with removing the tooltip despite my biased feelings, but on the other hand folks who don't use media player plasmoid will be left without any information about status… but are there any strawberry users who don't use default media player, playbar2 or such widget? i doubt.

**Comment by alekksander** [comment]
![image](https://user-images.githubusercontent.com/3148302/54812283-0e901700-4c8b-11e9-9d72-b8d66593b030.png)

latest build has some additional symbols, but beside it's okay – entries are in correct lines now
