### ISSUE TITLE
Tidal search

### ISSUE THREAD

**Issue by amian84** [jonaski/strawberry#78]
When I search artist, the album list is not complete. For example if I search "Dream Theater", I can't see the EP album "Paralyzed". If I search "Dream Theater Paralyzed", then i can found the ep ... I think that the correct behavior is if you try find it by artist name should show me all ablums / ep

**Comment by amian84** [comment]
Or maybe has posibility to search by Artist

**Comment by jonaski** [comment]
The results returned from Tidal for a album search isn't very accurate if you only search by artist. This isn't something I can fix. It's what Tidal does. You can increase the limit in settings if you want more results.
However I agree that there should be an artist search too, it's added this now.
https://github.com/jonaski/strawberry/commit/35f448c34fc527450b65153d89cb87c88745036c
It works much better when you want all the albums for an artist.

I've also fixed so album artist is set for songs and the default is now to group by album artist.
