### ISSUE TITLE
Appimage or Flatpak?

### ISSUE THREAD

**Issue by 38github** [jonaski/strawberry#8]
I really want to try this software since Clementine is qt4 and hasn't been updated in a long time. The problem is that I am using a distro (Solus) that does not support the packages being offered on your website. Is it too much to ask for either an Appimage or Flatpak so that we can try it or use it on a distro?

**Comment by jonaski** [comment]
I'm not familiar with Appimage or Flatpak, but I will add it to my TODO-list and look more into it if someone doesn't do it first, will leave the issue open.

**Comment by jonaski** [comment]
I'm building AppImages through buildbot now. Can you try this:
https://builds.strawbs.net/appimage/

**Comment by TheAssassin** [comment]
Would be nice if you could include the scripts or whatever to use to build the AppImages in the repo.

**Comment by jonaski** [comment]
@TheAssassin 
What repo?
I'ts here: https://github.com/jonaski/strawberry-buildbot/blob/master/config/master/strawberry/builders.py#L370

**Comment by TheAssassin** [comment]
Ah, I see. I've used the GitHub search without success, but it's there. Sorry for the noise.
