### ISSUE TITLE
Strawberry icon is incorrect on KDE Plasma Wayland session

### ISSUE THREAD

**Issue by glaubersm** [jonaski/strawberry#80]
Hi
I use 0.5.2 version on Arch Linux. As we can see in the screenshow below, Stranberry icon is incorrect when I use KDE Plasma Wayland session (the icon is correct under X11).
I also see the same Wayland generic icon when I use the task switcher by pressing alt+bab.

![strawberry](https://user-images.githubusercontent.com/15967631/52970881-2dea0a80-3394-11e9-9b48-b7f556cf17fa.png)

**Comment by alekksander** [comment]
wouldn't that be an issue with wayland rather than strawberry?

**Comment by glaubersm** [comment]
No. I reported the same issue to devs of several apps, almost all bugs are already fixed.
Here is an example
https://github.com/olive-editor/olive/issues/451

**Comment by jonaski** [comment]
I suspect that Wayland looks for the icon in from the desktop file.
Does it work if you rename strawberry.desktop to org.strawbs.strawberry.desktop ?
The desktop file is usually in /usr/share/applications

**Comment by glaubersm** [comment]
> Does it work if you rename strawberry.desktop to org.strawbs.strawberry.desktop ?
yes \o/

**Comment by jonaski** [comment]
Fixed https://github.com/jonaski/strawberry/commit/e594cf299e778a1a07f3a3748920acfd0d4ebca0
