### ISSUE TITLE
future of playlist looks

### ISSUE THREAD

**Issue by alekksander** [jonaski/strawberry#81]
hello!
are there plans to change default playlist view? there are better ways to display all needed info than in one single line. here are two examples of what i find a good playlist design:

![image](https://user-images.githubusercontent.com/3148302/53174954-3f791f80-35eb-11e9-9546-3d6e8d200181.png)

![deskt 26 09 17 bez](https://user-images.githubusercontent.com/3148302/53175502-5cfab900-35ec-11e9-8107-7527da257e3d.png)

this way we wouldn't have long names cut in the middle like now:

![image](https://user-images.githubusercontent.com/3148302/53175171-b7474a00-35eb-11e9-8116-a568cb78f81c.png)

![image](https://user-images.githubusercontent.com/3148302/53175590-929fa200-35ec-11e9-9bcd-1abbaf93fcd1.png)

so in my opinion we would gain not only in aesthetic aspect, but also improve readability.

**Comment by ccoenen** [comment]
This layout only works if you play complete albums. Could you post a screenshot with a pretty randomized playlist?

**Comment by alekksander** [comment]
it's true, it's much better at work with complete albums, but it's not unbearable with mixed artists – i've done that too, and it's something to get along with. unfortunately first picture is from internet, and second is mine, but from different OS. i will try to remember and boot it to screenshot what You have requested.

**Comment by jonaski** [comment]
I actually like this, as I mostly play entire albums.
What player is the first screenshot from? Looks like it's not using a collection library, but a file browser view.
In case we add this it should should be 2 playlist views, a separate playlist view for albums and songs.
Maybe it could switch automatically between the modes based on if entire albums are in the playlist or not.

**Comment by alekksander** [comment]
I think it's from Noise, or whatever default music player in elementary os is called now. The only problem I'm having with it is that it doesn't show tracks properties. It could be fixed by Smart column showing bit depth for lossless files and bitrate for lossy. Bitrate is useless for lossless files anyway.

**Comment by jonaski** [comment]
This may be as simple as squeezing the album cover on the left side of the rest of columns and adding a header on top of each album. But I'm not sure how to do it in Qt, and perhaps the playlist model needs to be changed to a QAbstractItemModel. It probably involves more work than it seems.
I don't really have time to prioritize this now, as I have to study a lot of things to figure out how to do it. (But I really like the suggestion). We can perhaps re-open this at some later point.
I don't really want the issue tracker filled up with stuff that might not get done in the near feature so I'm closing it for now, but if someone else wants to do this now, I will try to help out.

**Comment by alekksander** [comment]
it's one of the things i will remember about. thanks for straight clarification on the subject.

**Comment by alekksander** [comment]
how about what i called „smart column” previously? is there a chance to see it sooner than re–designed playlist? Bitrate is useless for lossless files, and bit depth is useless for lossy files. one column with data of bitrate  and sample rate such as 320kbps/44.1kHz for lossy files, and the same column giving bit depth instead of bitrate – 16bit/48kHz for lossless files is doable? it makes more sense rather than having useless information of bitrate for let's say flacs, as bitrate for flacs is more of a „how much data is in there” rather than an information about quality.

**Comment by jonaski** [comment]
I don't want to mix bitrate and samplerate in one column.
But I had a similar approach for combining samplerate and bit depth in one column, but I removed it.

**Comment by alekksander** [comment]
i'll just drop that here in case it's ever usefull

https://github.com/CDrummond/cantata

(has qt5 ui that displays covers in playlists – somewhat of what was requested)
