### ISSUE TITLE
Random playlist / Playlist continuation

### ISSUE THREAD

**Issue by ccoenen** [jonaski/strawberry#85]
I am switching over from [Media Monkey](https://www.mediamonkey.com/), and it has one setting that I keep enabled: At the end of a playlist you can automatically add random songs from your library. Better yet: You can tell it to always have X number of upcoming songs. So, if you have set this to 10, for example, there will always be at least 10 more things to play.

If you're jumping to a song close to the end of the playlist, it will simply add a few more to the list, so that there's always something to choose from.

On Clementine, I used the smart playlist "50 random songs" (I've seen #28) to mostly the same effect, yet I like Media Monkeys behaviour better for general background music. In that scenario you don't always want to specifically decide what to listen to, but you also don't want the music to "run out".

**Comment by jonaski** [comment]
I believe Clementine got the same feature, it's called "Dynamic Random Mix".
We might add this later, but right now I don't have time to prioritize it.

**Comment by Anrock** [comment]
Can this be reopend, so I can track the issue to know when it's implemented? So far it's the only reason when I'm still staying on Clementine.

**Comment by jonaski** [comment]
I worked on it, but there is a few issues so I have not merged it yet, I will update https://github.com/jonaski/strawberry/issues/132 with the progress.
