### ISSUE TITLE
Ability to switch off software volume.

### ISSUE THREAD

**Issue by chunky70** [jonaski/strawberry#86]
I think it would be great to have the ability to switch off the volume control as it's not needed when streaming to an external DAC. Also another feature i would like to see is buffering audio to RAM memory. Audiophiles would love these features. Thank you for your excellent work!

**Comment by jonaski** [comment]
100% volume would do the same as not settting the volume.
But I'll try to see if I can add an option to disable it as a few people have requested it.

**Comment by chunky70** [comment]
Thank you. Loving this player!!


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Jonas Kvinge <notifications@github.com> Date: 05/03/2019  23:37  (GMT+00:00) To: jonaski/strawberry <strawberry@noreply.github.com> Cc: chunky70 <chunky70@mail.com>, Author <author@noreply.github.com> Subject: Re: [jonaski/strawberry] Ability to switch off software volume. (#86) 
100% volume would do the same as not settting the volume.

But I'll try to see if I can add an option to disable it as a few people have requested it.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/jonaski/strawberry","title":"jonaski/strawberry","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/jonaski/strawberry"}},"updates":{"snippets":[{"icon":"PERSON","message":"@jonaski in #86: 100% volume would do the same as not settting the volume.\r\nBut I'll try to see if I can add an option to disable it as a few people have requested it.\r\n"}],"action":{"name":"View Issue","url":"https://github.com/jonaski/strawberry/issues/86#issuecomment-469903889"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/jonaski/strawberry/issues/86#issuecomment-469903889",
"url": "https://github.com/jonaski/strawberry/issues/86#issuecomment-469903889",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by jonaski** [comment]
Done
https://github.com/jonaski/strawberry/commit/3e658845d2f9119d0bbf880986cfde4a865e9a2a
