### ISSUE TITLE
bring back (was it removed?) the Clementine moodbar

### ISSUE THREAD

**Issue by G-9999** [jonaski/strawberry#87]
I'm finding Strawberry more inviting than Clementine -- just discovered it earlier today. However, one feature I really miss is the auto-generated moodbars. These allow the presentation of audio energy in certain points of a track and make skipping to these sections much easier. Was this feature removed for some particular reason? It can be completely disabled if a user does not prefer to use it in Clementine.

**Comment by jonaski** [comment]
It might be added later, but for now I don't have time to prioritize it, it's a big job just to maintain the features we got. It would also have to be fixed as it's causing crashes.

**Comment by jonaski** [comment]
I've added the moodbar now. I never really understood the purpose of it, but you explained it in a good way, I can see that it can be useful.
https://github.com/jonaski/strawberry/commit/907d18a83a692ed95d44961f7cdce56033564564
