### ISSUE TITLE
Feature: if track is available in different qualities, only take  highest one into playlist.

### ISSUE THREAD

**Issue by mandree** [jonaski/strawberry#95]
Greetings,

I often save my CD-ripped or purchased music in multiple formats, say, FLAC for home use and M4A/MP3 or OGG for mobile use. This means I have the same track in several formats on my computer. I would appreciate a feature/option that would check if I am adding the same track multiple times in various formats (say, when moving an album into a play list) and that only the highest quality or bitrate format be added. I understand that Vorbis 112 kbit/s may be better than MP2 128 kbit/s so I am wondering if there needs to be an (editable) preference list or this feature be limited to just choose between lossless ("pick any")/lossy.

**Comment by jonaski** [comment]
You can change group by to Format / Artist / Album.
I've also added an option now to group by format, which will show filetype (samplerate / bitrate):

![image](https://user-images.githubusercontent.com/10343810/55281716-f0847f80-5338-11e9-803c-473813ce7d47.png)
