### ISSUE TITLE
Scrobblers doesn't work as expected

### ISSUE THREAD

**Issue by Menelkir** [jonaski/strawberry#96]
It used to work until a week ago (not sure if it helps, but I've just tested with clementine and still works). Now every time I've listening to a song, it'll appear that is scrobbling in my profile and shortly after the song finished, the entry disappears. It happens to last.fm, libre.fm and musicbrainz.
I've tested 0.5.2, 0.5.3 and the -git version, both have the same issue. I've tried to delete all configurations and start fresh, same problem.

**Comment by Menelkir** [comment]
Here's the relevant log about scrobbling.

`10:48:51.459 DEBUG ScrobblerServices:45             Registered scrobbler service "Last.fm"
10:48:51.459 DEBUG ScrobblerServices:45             Registered scrobbler service "Libre.fm"
10:48:51.459 DEBUG ScrobblerServices:45             Registered scrobbler service "ListenBrainz"
10:48:55.913 DEBUG AudioScrobbler:119               Sending now playing for song "Reptile"
10:51:21.862 DEBUG AudioScrobbler:127               Scrobbling song "Reptile" at 146
10:52:23.361 DEBUG ScrobblerCache:145               Writing scrobbler cache file "/home/menelkir/.cache/strawberry/strawberry/librefmscrobbler.cache"
10:52:52.361 DEBUG ScrobblerCache:145               Writing scrobbler cache file "/home/menelkir/.cache/strawberry/strawberry/lastfmscrobbler.cache"
10:52:57.361 DEBUG ScrobblerCache:145               Writing scrobbler cache file "/home/menelkir/.cache/strawberry/strawberry/listenbrainzscrobbler.cache"
`

**Comment by jonaski** [comment]
When songs show up, but are not scrobbled, it means that "playing now" is sent, but not scrobbles.
Sounds like it's in offline mode.
Make sure offline mode is not checked in the settings.
Offline mode means that scrobbles are cached, but never sent to the server.
The intent with the offline mode is if you don't have an internet connection, but still want to scrobble (without getting errors) to the cache so it can be sent later. I realize it should probably be named different so it's not misunderstood.

**Comment by Menelkir** [comment]
You're right, it was the offline mode. 
Maybe keeping the name but having a short description on that like "(delay the scrobbling while not having internet)".

**Comment by Extarys** [comment]
I'm not sure if I have a similar issue. Can I ask where is the 'Offline mode' thing? I couldn't find it. I'm trying to scrobble to ListenBrainz. Also, where can I find the logs? (Sorry :smile: )

If it doesn't solve my problem I will open a new issue.

**Comment by Menelkir** [comment]
Tools -> Settings -> Scrobble.
From the top: First option is "Enable" and the next one is "Work in offline mode (only cache scrobbles).

I'm using 0.5.5 anyways.

**Comment by Extarys** [comment]
That was fast but, Hmmmm, Huston!
I'm using 0.5.5 too. Can't find that button. I feel like an idiot :laughing: 

![Screenshot from 2019-06-29 20-10-37](https://user-images.githubusercontent.com/11581433/60390690-2c4ef280-9aaa-11e9-86e2-75ac7a03a69c.png)

![image](https://user-images.githubusercontent.com/11581433/60390699-6e783400-9aaa-11e9-848b-1662fab842c5.png)

**Comment by Menelkir** [comment]
![strawberry-options](https://user-images.githubusercontent.com/42952551/60390733-ad5eb780-9ab3-11e9-9700-36c66d79c9dc.png)

**Comment by Menelkir** [comment]
![strawberry-options](https://user-images.githubusercontent.com/42952551/60390767-265e0f00-9ab4-11e9-96fb-9e5219609f22.png)

**Comment by Menelkir** [comment]
Maybe it's something from the configuration of your build. I'm using arch linux and this one is from the distribution repositories.

**Comment by jonaski** [comment]
@Extarys Can you scroll up and check that the top option "enabled" is checked?

The settings may look a bit off on a Gtk based desktop. The best is to use utility called qt5ct and configure qt5 and select gtk2 on style.
![image](https://user-images.githubusercontent.com/10343810/60390871-48ba5180-9ae1-11e9-9a7a-feb0cc7aba2f.png)

**Comment by Extarys** [comment]
*facepalm*

Thanks @jonaski it wouldn't let me scroll up - I never even saw when I installed it and configured it that there was an 'Enable' option. Know I know why devs complains about theming :rofl: 

It's now enabled.

![image](https://user-images.githubusercontent.com/11581433/60390883-49d28b00-9aaf-11e9-8aa4-19aa6f03bea4.png)

:heart: thank you very much to you both.
