### ISSUE TITLE
Some compile error along the lines of build.make:61: *** target pattern contains no '%'.  Stop.

### ISSUE THREAD

**Issue by rubyFeedback** [jonaski/strawberry#97]
Hello Jonas,

Not sure if this is worth reporting, but I'll just report it anyway.

I was following the instructions made available at:

https://www.strawbs.org/

In particular git checkout.

The commands I did were:

    git clone https://github.com/jonaski/strawberry

    mkdir strawberry-build

    cd strawberry-build
    
    cmake ../strawberry

After ~15% II got an error though. I will copy paste the result:

[ 15%] Building CXX object 3rdparty/qocoa/CMakeFiles/Qocoa.dir/qsearchfield_nonmac.cpp.o
[ 15%] Building CXX object 3rdparty/qocoa/CMakeFiles/Qocoa.dir/qbutton_nonmac.cpp.o
[ 15%] Building CXX object 3rdparty/qocoa/CMakeFiles/Qocoa.dir/qprogressindicatorspinning_nonmac.cpp.o
[ 16%] Building CXX object 3rdparty/qocoa/CMakeFiles/Qocoa.dir/moc_qsearchfield.cpp.o
[ 16%] Building CXX object 3rdparty/qocoa/CMakeFiles/Qocoa.dir/moc_qbutton.cpp.o
[ 16%] Building CXX object 3rdparty/qocoa/CMakeFiles/Qocoa.dir/moc_qprogressindicatorspinning.cpp.o
[ 16%] Building CXX object 3rdparty/qocoa/CMakeFiles/Qocoa.dir/qrc_qsearchfield_nonmac.cpp.o
[ 16%] Building CXX object 3rdparty/qocoa/CMakeFiles/Qocoa.dir/qrc_qprogressindicatorspinning_nonmac.cpp.o
[ 16%] Linking CXX static library libQocoa.a
[ 16%] Built target Qocoa
[ 17%] Generating core/moc_workerpool.cpp
[ 17%] Generating core/moc_closure.cpp
[ 17%] Generating core/moc_messagehandler.cpp
[ 17%] Generating core/moc_messagereply.cpp
Scanning dependencies of target libstrawberry-common
[ 17%] Building CXX object ext/libstrawberry-common/CMakeFiles/libstrawberry-common.dir/core/closure.cpp.o
[ 17%] Building CXX object ext/libstrawberry-common/CMakeFiles/libstrawberry-common.dir/core/logging.cpp.o
[ 17%] Building CXX object ext/libstrawberry-common/CMakeFiles/libstrawberry-common.dir/core/messagehandler.cpp.o
[ 17%] Building CXX object ext/libstrawberry-common/CMakeFiles/libstrawberry-common.dir/core/messagereply.cpp.o
[ 17%] Building CXX object ext/libstrawberry-common/CMakeFiles/libstrawberry-common.dir/core/waitforsignal.cpp.o
[ 17%] Building CXX object ext/libstrawberry-common/CMakeFiles/libstrawberry-common.dir/core/workerpool.cpp.o
[ 17%] Building CXX object ext/libstrawberry-common/CMakeFiles/libstrawberry-common.dir/core/moc_closure.cpp.o
[ 17%] Building CXX object ext/libstrawberry-common/CMakeFiles/libstrawberry-common.dir/core/moc_messagehandler.cpp.o
[ 18%] Building CXX object ext/libstrawberry-common/CMakeFiles/libstrawberry-common.dir/core/moc_messagereply.cpp.o
[ 18%] Building CXX object ext/libstrawberry-common/CMakeFiles/libstrawberry-common.dir/core/moc_workerpool.cpp.o
[ 18%] Linking CXX static library liblibstrawberry-common.a
[ 18%] Built target libstrawberry-common
ext/libstrawberry-tagreader/CMakeFiles/libstrawberry-tagreader.dir/build.make:61: *** target pattern contains no '%'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:588: ext/libstrawberry-tagreader/CMakeFiles/libstrawberry-tagreader.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

Not entirely sure what the problem is.

My host system is:

g++ (GCC) 8.3.0
GNU ld (GNU Binutils) 2.32.51.20190213

Quite old glibc though (version 2.23); qt should be the latest aka 5.12.2. All compiled from
source.

cmake version is at: 3.14.1

Not sure if the above is helpful to you or not, but feel free to proceed how you want to anyway,
this is really just meant as a one-channel feedback to you. :)

Thanks for reading!

**Comment by jonaski** [comment]
I've seen this before. You are missing some protobuf compiler related packages. Install what you can find starting with protobuf-c

**Comment by dc740** [comment]
Same happened to me.
I got weird warning and it wouldn't compile:

    CMake Warning at /usr/share/cmake-3.13/Modules/FindProtobuf.cmake:495 (message):
      Protobuf compiler version doesn't match library version 3.6.1

So I installed:
`sudo apt install protobuf-c-compiler protobuf-compiler libprotobuf-c-dev libprotobuf-dev`

The warning is gone and now I can compile. I don't know which of those packages fixed it.
