### ISSUE TITLE
0.5.3 deb doesn't install on Xenial due to newer dependencies versions

### ISSUE THREAD

**Issue by sylvainsab** [jonaski/strawberry#98]
dpkg is telling me that dependencies are not satisfied
```
:~$ sudo dpkg -i ./strawberry_0.5.3_amd64.deb 
...
dpkg: des problèmes de dépendances empêchent la configuration de strawberry :
 strawberry dépend de libcdio13 (>= 0.83) ; cependant :
  Le paquet libcdio13 n'est pas installé.
 strawberry dépend de libchromaprint0 (>= 0.2) ; cependant :
  Le paquet libchromaprint0 n'est pas installé.
 strawberry dépend de libprotobuf9v5 ; cependant :
  Le paquet libprotobuf9v5 n'est pas installé.
```
when I actually have newer versions of these installed, with different names : libcdio17, libchromaprint1, libprotobuf10

**Comment by jonaski** [comment]
Even after apt update and upgrade, xenial still got libcdio13, libprotobuf9v5 and libchromaprint1
Also according to: https://packages.ubuntu.com/xenial/amd64/libcdio13/filelist
Same with protobuf and chromeprint:
https://packages.ubuntu.com/xenial/amd64/libprotobuf9v5/filelist
https://packages.ubuntu.com/search?suite=default&section=all&arch=any&keywords=libchromaprint&searchon=names

So did you install those packages from another repository or are you using a different versjon of ubuntu?

**Comment by jonaski** [comment]
Sounds like you are using bionic, it has libchromaprint1, libcdio17 and libprotobuf10

**Comment by sylvainsab** [comment]
Indeed, I use the LTS

**Comment by sylvainsab** [comment]
My bad, I downloaded the wrong package... everyting's fine now. Thanks again.
