### ISSUE TITLE
ampersand character appears in left panel section names

### ISSUE THREAD

**Issue by sylvainsab** [jonaski/strawberry#99]
![Screenshot_20190403_023611](https://user-images.githubusercontent.com/34339895/55444963-410a1000-55b9-11e9-8d23-73bdeb8e7cfe.png)

**Comment by jonaski** [comment]
The ampersands in the fancy tabbar is likely a bug in KDE
See: https://bugs.kde.org/show_bug.cgi?id=337491
You can try this:
kwriteconfig5 --file kdeglobals --group Development --key AutoCheckAccelerators "false"
